### ISSUE TITLE
Z Aware elements

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#110]
When adding starting points or creating features having those features z aware would be a need for some customers and International Distributors. 

This could be done by passing a elevation service to add-in thru an option in the properties dialog box.

**Comment by mfunk** [comment]
@topowright Can you describe what the output would be like? Are they expecting 3D range rings that follow the terrain from the surface? I would have assumed if they wanted 3D for many of these features they would have the same elevation and would 'float' over the surface. If they are sampled from the terrain an oblique view would obscure many of the lines/circles/etc.

**Comment by lfunkhouser** [comment]
@topowright please provide additional details/requirements.

**Comment by lfunkhouser** [comment]
Closing. No known use case or clear requirements.
