### ISSUE TITLE
Author of Addin Should Be "Esri" 

### ISSUE THREAD

**Issue by mcalamito** [Esri/distance-direction-addin-dotnet#139]
Currently, it is "ESRI"  (as is the Visibility Addin). I know it is something little, but trying to follow suit with other Addins and with the Esri marketing practices.

**Comment by mfunk** [comment]
@dhagens @pHill5136  @kgonzago 
Not sure the exact process to test this. If I go to Add-In Manager and test today's build (12/16/16) then there is a *Created by: Esri* tag. I could assume its the same as "Author" but need to make sure this is correct.

![image](https://cloud.githubusercontent.com/assets/3093182/21268137/5a85fb48-c362-11e6-93c2-a65ca3fc7389.png)

**Comment by mfunk** [comment]
Talked with @kgonzago and this is probably the only thing it could be. Closing this one out.
