### ISSUE TITLE
Zoom to Graphic Extent after Graphic Created

### ISSUE THREAD

**Issue by mcalamito** [Esri/distance-direction-addin-dotnet#150]
after creating a graphic, the map should be zoomed to graphic extent by default. If the user is drawing within their current extent, they can see their graphic being created. If they are manually inputting parameters and those parameters fall outside their current extent, they should be automatically taken to the graphics extent.

**Comment by dhagens** [comment]
@mcalamito, please verify with next Jenkins build.

**Comment by mfunk** [comment]
Testing Procedure:
1) Zoom into California (Monterey area).
2) Enter lines/circles/ellipses/range rings around 13SCU7353073185 (Kirtland AFB, Albuquerque, NM)
3) Does it zoom?

* [ ] ArcMap 10.3.1
* [ ] ArcMap 10.4.1
* [ ] ArcMap 10.5
* [ ] ArcGIS Pro 1.4
