### ISSUE TITLE
Revisit - Graphics Should be Created Without a Fill by Default

### ISSUE THREAD

**Issue by mcalamito** [Esri/distance-direction-addin-dotnet#151]
Instead of creating graphics with a fill, I strongly believe graphics should be created without a fill, and allowing the user to add a fill if desired. 

Especially in the case of ArcGIS Pro, after creating Range Rings and Saving As KML (Pro can add KML in v1.3), there is currently no way to change the Range Rings to have no fill. Therefore, you cannot see the rings, just a giant filled circle.

**Comment by mfunk** [comment]
@dhagens @pHill5136 
This is fixed on ArcMap 10.3.1, 10.4, and 10.5. But it is still an issue on Pro 1.4:

**Comment by pHill5136** [comment]
Updated to empty fill for polygons. Changed outline color to red for graphic to be consistent with rangerings rendering. pull request: https://github.com/Esri/distance-direction-addin-dotnet/pull/187

**Comment by pHill5136** [comment]
fyi: @nfeuerstein @dhagens fixed this... pull request: #187

**Comment by mfunk** [comment]
Checked latest and we are using un-filled symbols:

![image](https://cloud.githubusercontent.com/assets/3093182/21330699/981b2396-c5f3-11e6-9e7a-abf1b72cc514.png)
