### ISSUE TITLE
Snapping to Features When Interacting with Map in ArcMap

### ISSUE THREAD

**Issue by mcalamito** [Esri/distance-direction-addin-dotnet#152]
When interacting with map to create center points, end points, etc., snapping to existing features would be a huge workflow asset. It currently works in ArcGIS Pro and is a big enhancement. Having this available in ArcMap is crucial.

**Comment by jmccausland** [comment]
addressed in #153, verify at the next build

**Comment by mfunk** [comment]
Testing this by adding point, line, polgon features to map, then using Map Point tool on each of the four tabs to see if it will snap to features or not and then test with editor snapping settings.

* [ ] ArcMap 10.3.1
* [ ] ArcMap 10.4.1
* [ ] ArcMap 10.5
* [ ] ArcGIS Pro 1.4

**Comment by mfunk** [comment]
Looking good so far. What I was expecting is that the tools use the ArcMap snapping environment, and it seems they do as the tool picks up the snapping symbol/layer name (10.3.1 example).
![image](https://cloud.githubusercontent.com/assets/3093182/21274481/504b681e-c37d-11e6-957c-913a179f3a34.png)

**Comment by mfunk** [comment]
Tested against Point, Vertex, Edge, Endpoint with options on and off in Desktop.
