### ISSUE TITLE
Save As - Select Output - KML - is followed by "Choose Location to create KMZ file" diaglog

### ISSUE THREAD

**Issue by pshowalter** [Esri/distance-direction-addin-dotnet#159]
@jmccausland @dhagens 

Perhaps use  KMZ  throughout the work flow since we don't offer a straight KML file save.

![image](https://cloud.githubusercontent.com/assets/6842145/16703138/fe72935e-4538-11e6-9896-b8a4ec659476.png)

![image](https://cloud.githubusercontent.com/assets/6842145/16703177/54596680-4539-11e6-83a0-c51cff7aad15.png)

**Comment by pHill5136** [comment]
Updated labels to read 'KMZ' instead of 'KML' pull request: https://github.com/Esri/distance-direction-addin-dotnet/pull/186

**Comment by pHill5136** [comment]
@nfeuerstein fixed this... Updated labels to read 'KMZ' instead of 'KML' pull request: #186

**Comment by mfunk** [comment]
**Save As** dialog now reads as KMZ and not KML

![image](https://cloud.githubusercontent.com/assets/3093182/21330748/d3a57790-c5f3-11e6-82e9-dcb154ad8e21.png)
