### ISSUE TITLE
Distance and Direction labels have way too many decimal places and the label doesn't have spaces

### ISSUE THREAD

**Issue by mfunk** [Esri/distance-direction-addin-dotnet#164]
From Asana PBI Description:

Description:

The labels for the lines created with the Distance and Direction add-in in ArcMap has way too many decimal places.  I'm pretty sure it's measuring to the molecular level.  I would think two decimal places would be sufficient.  The label also should have spaces to make it more legible.

Definition of Done:

Labels for lines created with the Distance and Direction add-in look nice and appropriate - just enough decimal places (probably 2) and spaces where it makes sense.

---

 Additionally:
Assumptions:
- labels for each of the geometry types built by the Distance and Drieciton Add In
- Fix is for ArcGIs Pro as well as ArcMap
- Some kind of test is included to verify this now, and in the future (regression).

**Comment by nfeuerstein** [comment]
@mfunk was this resolved?

**Comment by mfunk** [comment]
Looks good in 10.3.1:
![image](https://cloud.githubusercontent.com/assets/3093182/21320784/14107e92-c5c7-11e6-899f-e43080eed3d1.png)

![image](https://cloud.githubusercontent.com/assets/3093182/21320792/18364d3a-c5c7-11e6-9fbb-7fadf976e66e.png)

![image](https://cloud.githubusercontent.com/assets/3093182/21320803/1b63d59a-c5c7-11e6-9b67-41100c6aff39.png)

And 10.5.1:
![image](https://cloud.githubusercontent.com/assets/3093182/21320937/8bf8377e-c5c7-11e6-9f73-6e6275f8d863.png)

But Pro 1.4 doesn't draw labels (never did):

**Comment by mfunk** [comment]
@nfeuerstein @lfunkhouser 
I'm going to suggest that we close this one out, as the problem is resolved in ArcMap, but knowing that the Add-In in Pro doesn't produce any labels at all. This should be a separate issue anyway. Logged this one as #192.
