### ISSUE TITLE
Distance and Direction widgets throws errors when out of bounds

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#165]
This issue is only reproducible in Visual Studio.

Issue: When map is zoomed out and your mouse pointer hovers over a blank area, the following error is thrown:

````jcode
An exception of type 'System.Runtime.InteropServices.COMException' occurred in DistanceAndDirection.dll but was not handled in user code

Additional information: The operation was attempted on an empty geometry.
````

**Comment by jmhauck** [comment]
This issue only occurs for some of the display coordinate types.

Additional steps to repro:

1) Launch ArcMap from the Visual Studio solution provided
2) Add > Basemap > Imagery with Labels
3) Zoom out past the extent of the basemaps tiles
4) On the Distance and Direction window click Edit Properties
5) Choose UTM as the Display Coordinate
6) Hover over some of the white space outside of the extent of the basemap

**Comment by Thargoids** [comment]
I am having trouble recreating this issue with the steps provided.

Config: Windows 8.1, Visual Studio 2013, ArcMap 10.3.1.

**Comment by ACueva** [comment]
Guys, I'm a little confused.  Who's working on this issue?  I've reproduced this issue for @jmhauck and @pHill5136.  I was under the impression it's been fixed?

**Comment by Thargoids** [comment]
I think what happened is that I was looking for bugs to work on and came to this one which was unassigned at the time. Please ignore me if I have added confusion :)

**Comment by ACueva** [comment]
Tested against latest build.  Error no longer occurs.
