### ISSUE TITLE
Mils to Degrees

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#166]
As a user it seems that what is drawn on the screen is off by 90 degrees. When I get the preview feature of my graphic it is not the same as the final graphic. This only happens when a user chooses mils as angle.

**Comment by topowright** [comment]
@ACueva this is the bug that you found. Good find.

**Comment by ACueva** [comment]
Not sure procedure.  Assigning to @nfeuerstein to add to backlog.?

**Comment by ACueva** [comment]
Assigning to @pHill5136.  I believe this is the bug you fixed?

**Comment by lfunkhouser** [comment]
@pHill5136 Is this issue resolved and ready to be verified?

**Comment by mfunk** [comment]
Tested this with *Orientation* on the **Ellipse** tab. Where I used 4000, 5000, 6000 Mils (full circle is approximately 6283 Mils):

![image](https://cloud.githubusercontent.com/assets/3093182/21331060/753775d0-c5f5-11e6-8559-8f8b0915ed17.png)

Also tested with *Angle* on the **Lines** tab. Here I used 0, 1000, 2000, 3000, 4000 Mils:
![image](https://cloud.githubusercontent.com/assets/3093182/21331287/778aed0c-c5f6-11e6-8c97-4fdbbd59fb97.png)
