### ISSUE TITLE
Distance and direction rings need to be more intuiative

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#167]
User interface is clunky.  Wasn't sure what I needed to do to make the rings show up.

Process is:
Select center point tool
Click on pointer tool
Click on map
Enter distance between Rings
Enter Number of Radials
Press enter on keyboard

As a user I had no idea that's how I got rings to draw.
Why does the distance between rings default to 0?

Suggest adding "submit" button?

**Comment by pHill5136** [comment]
@nfeuerstein @kgonzago This tool works as designed. After filling all fields the user must hit the Enter key. Do we want to add a submit button or is this best tackled through documentation and adding submit as an enhancement in future version?

**Comment by nfeuerstein** [comment]
@pHill5136 - addressed through documentation this release, if its not already.

**Comment by Dbarnes1** [comment]
@nfeuerstein this is part of documentation right now. Closing
