### ISSUE TITLE
UTM coordinates always off by 1

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#169]
Not sure if this a bug or not.
Whatever value that's entered UTM will always be off by 1.

![coordinateconversion_screencapturedtandpro](https://cloud.githubusercontent.com/assets/3093940/19973625/fbc05832-a1a2-11e6-8914-be610f2766b5.PNG)

In addition, when expected outputs are checked against
http://egeoint.nrlssc.navy.mil/web_geographic_translator/faces/tabbed_transform.jsp
it is also off by 1.

**Comment by jmccausland** [comment]
@ACueva This should be added to the CC repo.  What version of ArcMap and Pro are you running?  I can't reproduce this issue with your test data at 10.5 Desktop or Pro 1.3.1

**Comment by ACueva** [comment]
@jmccausland Good call, i'll move this to the right Repo.  If you look at the image above you can see what i'm referring to.  MGRS. USNG both end in 90.  UTM ends with 89.  If we plug that same value into http://egeoint.nrlssc.navy.mil/web_geographic_translator/faces/tabbed_transform.jsp UTM ends in 90.

**Comment by ACueva** [comment]
This issue was moved to Esri/coordinate-conversion-addin-dotnet#141
