### ISSUE TITLE
Distance and Direction line should be an arrow

### ISSUE THREAD

**Issue by jmhauck** [Esri/distance-direction-addin-dotnet#171]
Logged in reference to asana task:

Description:
Given that the tool is called Distance and Direction, the output needs to be an arrow (showing direction) and not just a line.

Definition of Done:
The result calculation (from creating lines of bearing with Distance and Direction widget) is displayed as a legible label on the map along with an arrow (from start to end point).

**Comment by jmhauck** [comment]
What is currently observed:

![noarrow](https://cloud.githubusercontent.com/assets/2170893/20942360/50a892f4-bbb8-11e6-83fc-11134766b705.png)

**Comment by jmhauck** [comment]
This is what is observed after the commit above:

![image](https://cloud.githubusercontent.com/assets/2170893/20942672/a378cc50-bbb9-11e6-9902-8f691be14f0b.png)

@nfeuerstein @kgonzago was the expectation that this would involve a change to the text that is displayed as well? If so could I have more details about that part of it?

**Comment by kgonzago** [comment]
@jmhauck what you implemented is spot on.

**Comment by jmhauck** [comment]
@kgonzago great!

**Comment by Dbarnes1** [comment]
![image](https://cloud.githubusercontent.com/assets/13024357/20945675/0d27222a-bbbd-11e6-8377-836611fec54d.png)
verified fixed in 10.4.1

**Comment by elinz** [comment]
@jmhauck @kgonzago I reopened this issue. Arrow heads are now being added to circles, ellipses, and rings (and the radials).  The arrow head should only be added to lines created by the Lines tool. This addin was released on the download site today with this issue.

![image](https://cloud.githubusercontent.com/assets/4635490/20991491/b3e47f96-bc93-11e6-963c-6520727fc0c5.png)
