### ISSUE TITLE
Save As does not show text for Distance and Direction

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#178]
_From @topowright on December 8, 2016 22:34_

The Distance and Direction Add-in has the ability to save features locally. Currently the text does not show up: 

![image](https://cloud.githubusercontent.com/assets/5488313/21030359/0ca8754e-bd96-11e6-8339-f5ba8d8db62b.png)

## Expected Behavior
I would expect to see Save to shapefile, feature class or kml

## Current Behavior
No text is showing up in the dialog box. 

## Steps to Reproduce (for bugs)

1. Create a graphic
2. Click the Save As Button
3. Dialog box will show up 
4.

## Your Environment
Windows 8 ArcGIS pro 1.4 build 7156

_Copied from original issue: Esri/military-tools-for-arcgis#78_

**Comment by lfunkhouser** [comment]
_From @pHill5136 on December 14, 2016 21:49_

@topowright @nfeuerstein Checked this in pro 1.4 build 7179. Labels are appearing in the SaveAs dialog.

**Comment by Dbarnes1** [comment]
I can also verify this works on Pro 1.4 (I'm still on build 7039). closing issue. 

![image](https://cloud.githubusercontent.com/assets/13024357/21229942/2884e610-c298-11e6-8b24-81c25a99c614.png)
