### ISSUE TITLE
Distance And Direction: Radials for rings are not created at the correct length in ArcGIS Pro

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#181]
_From @elinz on December 5, 2016 18:45_

When I use the Rings function on the Distance And Direction addin the length of the radials created do not have the correct length. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/4635490/20897633/fb6e6506-bad7-11e6-9ae6-bf2d375d5817.png)

## Expected Behavior

The length of the radials created should match the radius of the outer most ring.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: ArcGIS Pro 1.3.0 final
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 8.1 Enterprise 64 bit
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#67_

**Comment by lfunkhouser** [comment]
_From @elinz on December 5, 2016 18:58_

We know that at least for 1.2 and 1.3 we can't create geodetic lines so the "Number of Radials" parameter should be hidden/disabled or removed.

**Comment by lfunkhouser** [comment]
_From @kgonzago on December 5, 2016 20:48_

@nfeuerstein @topowright Should we remove Radials from Distance and Direction Pro 1.2/1.3 entirely?

**Comment by lfunkhouser** [comment]
_From @nfeuerstein on December 5, 2016 21:17_

@kgonzago - Distance and Direction is dead in 1.2 all together.  For 1.3, we should probably remove radials if there is no way to fix it.  It seems to me that 1.3 doesn't support radials.

**Comment by lfunkhouser** [comment]
_From @Dbarnes1 on December 5, 2016 21:22_

@nfeuerstein would an alternative to removing radials in 1.3 be to include a known issue about radials not working properly in our documentation? This is what we are currently doing in regards to line creation in the add-in. See this PR: https://github.com/ArcGIS/arcgis-solutions-website/pull/4608/files

**Comment by lfunkhouser** [comment]
_From @nfeuerstein on December 5, 2016 21:32_

@Dbarnes1 yes, that is an alternative.  The bottom line is that lines aren't supported, we can either document that geodesic lines aren't supported or we can remove the option.  Which is more feasible?

Documenting it puts the onus on the user to understand its not supported, and removing it puts the onus on us.

**Comment by lfunkhouser** [comment]
_From @Dbarnes1 on December 5, 2016 21:36_

@nfeuerstein I think updating the documentation with a known issue for pro 1.3, and then removing the functionality for lines and radials in pro 1.4 would be the most suitable option considering the current technical limitations.

**Comment by lfunkhouser** [comment]
_From @nfeuerstein on December 5, 2016 21:40_

Sounds like a plan.  Any issues with that @kgonzago?

**Comment by lfunkhouser** [comment]
_From @kgonzago on December 9, 2016 13:44_

I like that plan. This is similar to #68. Once issue persists when testing with Pro 1.4, the line and radials will be removed entirely.

**Comment by lfunkhouser** [comment]
_From @elinz on December 9, 2016 16:11_

@kgonzago I installed the latest build of Military Tools for ArcGIS that I believe was built on 1.3 SDK and the same issue exists.

**Comment by elinz** [comment]
@kgonzago Still an issue at Pro 1.4. See #180.

**Comment by mfunk** [comment]
@kgonzago @pHill5136 
Just an FYI, none of the Distance and Direction lines are geodesic, this means the **Line** tab features as well as the radials on the **Rings** tab.

![image](https://cloud.githubusercontent.com/assets/3093182/21330097/b0edde3e-c5f0-11e6-8fb4-3a30f80a1ce6.png)

![image](https://cloud.githubusercontent.com/assets/3093182/21330169/087f4b4c-c5f1-11e6-961a-e082ad155749.png)

**Comment by pHill5136** [comment]
@nfeuerstein @kgonzago I hid the radials label and text box on range rings and commented out the lines tab. pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/193

**Comment by mfunk** [comment]
*Lines* tab is removed:
![image](https://cloud.githubusercontent.com/assets/3093182/21355675/c69e0bd0-c683-11e6-9c9c-0dc8c7c02f0b.png)

And Radials option is removed from **Rings**
![image](https://cloud.githubusercontent.com/assets/3093182/21355705/e1a6ed66-c683-11e6-8fdc-4923049e9ca5.png)
