### ISSUE TITLE
Pro 1.2 - Distance and Direction add-in doesn't open

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#182]
_From @elinz on November 4, 2016 17:19_

I navigate to the "MILITARY TOOLS" ribbon, click on "Distance and Direction" add-in and no interface for the tool is opened.

## Expected Behavior

The interface for the tool should open when the user clicks on it.

## Current Behavior

I navigate to the "MILITARY TOOLS" ribbon, click on "Distance and Direction" add-in and no interface for the tool is opened. Interfaces for the other add-in's, i.e. Convert Coords, Visibility, and Military Symbol Editor are displayed when clicked on.

## Steps to Reproduce (for bugs)

1. Install the Military Tools for ArcGIS using the .bat file
2. Open Pro 1.2 final, and create a new project
3. Click on the "MILITARY TOOLS" ribbon
4. Click on the "Distance and Direction" add-in. No interface for the add-in is opened

## Your Environment

* Version used: Military Tools for ArcGIS built on 04 Nov 2016 09:06
* Environment name and version (e.g. Chrome 39, node.js 5.4): ArcGIS Pro 1.2. final (5023)
* Operating System and version (desktop or mobile): Windows 7 Enterprise 64 bit
* Link to your project:
NOTE: I'm using remote desktop to access this particular windows machine.

_Copied from original issue: Esri/military-tools-for-arcgis#38_

**Comment by Dbarnes1** [comment]
@lfunkhouser we never released this on Pro 1.2, so can we close this out?

**Comment by nfeuerstein** [comment]
No distance and direction for Pro 1.2 - closing out.
