### ISSUE TITLE
Poor tooltip name and description for Distance and Direction addin (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#184]
When I hover over the Distance and Direction addin the following tooltip is displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21274600/ec088732-c37d-11e6-9d61-4cfb336e2ee0.png)

"Show Distance and Direction" - there is no reason to use the verb "Show". Users know that the tool will open or do something.

"Add-in command to show Distance and Direction." - This doesn't help the user at all. We should be describing what the user can do with the addin. Look at other tools and see how they describe the tool.

**Comment by elinz** [comment]
Here is the description part of the tootip that we can use:

"Interactively create geodetic lines, circles, ellipses, range rings, and distance calculations based on time and rate. Created graphics can be saved to feature classes, shapefiles, and KMZ files."

**Comment by mfunk** [comment]
PR merged, waiting to see if it gets into the newest builds.

**Comment by mfunk** [comment]
@pHill5136 
Not seeing the change in 10.4.1 from today's build 1067.

![image](https://cloud.githubusercontent.com/assets/3093182/21725976/80a0a0ec-d3ef-11e6-916d-85d7e6b3cf47.png)

**Comment by BobBooth** [comment]
@mfunk @pHill5136 @nfeuerstein @lfunkhouser - the tool tips for all three should have similar style & content. Right now Visibility's is the same, and Coordinate Conversion's tip is "Displays Coordinate Conversion" - maybe a little better, but not as descriptive as @elinz's suggestion.

**Comment by mfunk** [comment]
Checked again and still seeing above screenshot in 10.4.1 as of today's build.

**Comment by joebayles** [comment]
Verified.
