### ISSUE TITLE
Poor tooltip name and description for Distance and Direction addin (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#185]
When I hover over the Distance and Direction addin the following tooltip is displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21275099/0f07c8b8-c380-11e6-9439-13499a38ea62.png)

"Show Dockpane" - there is no reason to use the verb "Show". Users know that the tool will open or do something. The name should have the addin name.

"Show Distance and Direction Dockpane" - This doesn't help the user at all. We should be describing what the user can do with the addin. Look at other tools and see how they describe the tool.

**Comment by pHill5136** [comment]
@nfeuerstein @elinz Updated tooltip pull request: https://github.com/Esri/distance-direction-addin-dotnet/pull/188

**Comment by elinz** [comment]
@pHill5136 Tooltip for addin missing description. I'm asking the team if we already have a short description for each of the addin's already written.

**Comment by mfunk** [comment]
Looking good here.
![image](https://cloud.githubusercontent.com/assets/3093182/21330599/0e34ab66-c5f3-11e6-87dc-697fb88c38db.png)

**Comment by elinz** [comment]
@pHill5136 @mfunk This is not good. We need a description of what the tool does. I received something from Product management. I'll see if I can condense to a two sentence description.

**Comment by mfunk** [comment]
@elinz do you have an example of a correct one that you can share?

**Comment by elinz** [comment]
@mfunk I'm trying to come up with one right now.

**Comment by elinz** [comment]
@mfunk @pHill5136 Here is the description part of the tootip that we can use:

"Interactively create geodetic circles, ellipses, range rings, and distance calculations based on time and rate. Created graphics can be saved to feature classes, shapefiles, and KMZ files."

I'll update #184 to reflect a slightly different description for the ArcMap addin.

**Comment by mfunk** [comment]
@pHill5136  Did we make any changes for @elinz suggestions? I'm not seeing any in this morning's build:

![image](https://cloud.githubusercontent.com/assets/3093182/21355995/f60647ce-c684-11e6-87cb-39315a925b91.png)

**Comment by pHill5136** [comment]
@mfunk @elinz Hmmm. I had a description in there. Seeing the same thing as you guys... will check code...

**Comment by pHill5136** [comment]
@mfunk @elinz Updated the description. Pull request: https://github.com/Esri/distance-direction-addin-dotnet/pull/204

**Comment by mfunk** [comment]
Got the latest build from Jenkins and this is what I see:
![image](https://cloud.githubusercontent.com/assets/3093182/21362736/83489592-c69e-11e6-9131-dd938187b1ea.png)


Text reads as 

> Interactively create geodetic circles, ellipses, range rings, and distance calculations based on time and rate. Created graphics can be saved to feature classes, shapefiles, and KMZ files.

Marking this one as completed.

**Comment by elinz** [comment]
@pHill5136 @mfunk Thanks. Looks good.
