### ISSUE TITLE
Extra Buttons should be removed from the Distance and Direction Add-In in Pro

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#189]
These two buttons are visible on the Distance and Direction Add-In ribbon but do not appear to do anything. Talked to @topowright who confirmed that they should not be there. seems the code was removed (or never existed) as they do not do anything, but the buttons never were removed. 

![image](https://cloud.githubusercontent.com/assets/5322669/21330680/78702654-c5f3-11e6-97a4-31763526a289.png)

**Comment by dfoll** [comment]
@topowright can you please chime in on this, and confirm one way or the other. There is definitely an issue here, as the buttons do no work, but the question is, are the buttons missing code behind them, or are they supposed to be totally removed.

**Comment by topowright** [comment]
We removed these buttons from the Coordinate Conversion add-in and should be done on Distance and Direction. 
![image](https://cloud.githubusercontent.com/assets/5488313/21330815/4025b72c-c5f4-11e6-8516-dbd87f3b24c3.png)

This is the way that it looks for that add-in

**Comment by pHill5136** [comment]
@nfeuerstein Removed buttons in Distance Direction pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/195

**Comment by mfunk** [comment]
Extra buttons are no longer present after installing the Distance and Direction Add-In:
![image](https://cloud.githubusercontent.com/assets/3093182/21355837/5f10ee46-c684-11e6-8687-3f7beb01e465.png)
