### ISSUE TITLE
Distance and Direction add in ArcMap Doesnt show diameter values

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#190]
When using the DD Circle tab and the Diameter option, the graphic labels give radius instead diameter.

![image](https://cloud.githubusercontent.com/assets/5116835/21330674/73b8af28-c5f3-11e6-85c9-952f6c515e61.png)

**Comment by Dbarnes1** [comment]
@NatalieCampos I'm seeing the same error.

**Comment by Thargoids** [comment]
To hopefully avoid duplication of work - I am unable to assign this issue to myself at present, but am working on it and have a fix imminent.

**Comment by mfunk** [comment]
Will verify once PR is merged.

**Comment by pHill5136** [comment]
@mfunk @Thargoids merged this.

**Comment by mfunk** [comment]
@Thargoids 
Not sure if this was the expected fix or not. When I select *Radius* the output label is **Radius**. When I select *Diameter* it is still labeled as **Radius**, but the distance value is correctly halved, and drawn correctly.
My test:
1) Select **Radius** from dropdown
2) Type "0 0" in Center Point
3) Type 100 in Radius/Diameter
4) Select Kilometers in the dropdown and click Enter
Circle is drawn with "Radius: 100.00 Kilometers"
5) Select **Diameter** from dropdown
6) Type "1 1" in Center Point
7) Type 100 in Radius/Diameter
8) click Enter
Circle is drawn with "Radius: 50.00 Kilometers"
What is expected is that the second circle would be labeled "Diameter: 100.00 Kilometers".

![image](https://cloud.githubusercontent.com/assets/3093182/21372396/c1db939a-c6cb-11e6-9730-e3c6f16fd2bc.png)

**Comment by elinz** [comment]
@mfunk @Thargoids Just installed the latest build (single addin). Followed steps above and things are working the way I would expect...
![image](https://cloud.githubusercontent.com/assets/4635490/21372603/285ed9fa-c6cd-11e6-8446-01b66b4eadc7.png)

**Comment by Thargoids** [comment]
This makes me happy :)

**Comment by mfunk** [comment]
Got it...

![image](https://cloud.githubusercontent.com/assets/3093182/21396868/851fcf62-c756-11e6-975f-5498dd3b27f9.png)
