### ISSUE TITLE
Unable to use the DD Rings in ArcMap

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#191]
Using the interface to create the range rings of the DD addin, I am unable to generate the rings.  Below is the inputs.  
![image](https://cloud.githubusercontent.com/assets/5116835/21330852/68c198e0-c5f4-11e6-8d74-479de59fd24e.png)
Below is a screen capture of my attempt to drop center points.  
![image](https://cloud.githubusercontent.com/assets/5116835/21330874/7f59481e-c5f4-11e6-8daf-e383ac59ddbc.png)
Pressing enter does not generate rings.

**Comment by mfunk** [comment]
@NatalieCampos what coordinate system are those point coordinates in?

**Comment by pHill5136** [comment]
I think this goes to the clicking enter to execute tool once all fields are populated. See issue: https://github.com/Esri/distance-direction-addin-dotnet/issues/167. Handled in documentation. Closing
