### ISSUE TITLE
Coordinate format should automatically update based on what you paste. Distance and Direction ArcMap, lines tab.

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#196]
This issue is more of an enhancement/design decision. If you have a spreadsheet of starting points for lines that you want to draw, and those are in decimal degrees, but the current format in the map (as set in the Edit Properties) is in lat long, the line will draw. BUT the end point won't automatically switch to decimal degrees, and as a result you would see two different coordinate formats in the Lines tab. I think that the add-in should automatically switch the format of the add-in based on what you paste. 

Visual reference of the issue:

![image](https://cloud.githubusercontent.com/assets/13024357/21332998/431815b2-c601-11e6-8a88-255aa2c2090a.png)

#### Example coordinates: 
Set the format to default map units and paste in this for a starting point: 22TCR2822350255. If possible the end point should change the format to mrgs

**Comment by topowright** [comment]
@saip if we can provide the user with functionality that allowed the input start point to change the input end point format what would the level of effort be for that capability? Based on that information will decide if we want to tackle this enhancement. FYI @lfunkhouser @dfoll

**Comment by topowright** [comment]
This is a no fix based on the level of effort and the return added value being too low.
