### ISSUE TITLE
User is given no indication via cursor icon that Map Point tool is active (ArcMap)

### ISSUE THREAD

**Issue by Thargoids** [Esri/distance-direction-addin-dotnet#197]
**Procedure:**
1. In ArcMap click Map Point tool
2. Hover mouse cursor over map

**Result:** the mouse cursor does not change from the standard mouse cursor

**Result expected:** mouse cursor should change to a cursor specific to the Map Point tool to indicate that this particular tool is active (in keeping with standard behaviour in ArcMap when a tool is selected)

**Comment by pHill5136** [comment]
This problem popped up with the fix to https://github.com/Esri/distance-direction-addin-dotnet/issues/189. When I removed the properties and sketch tool the map point tool no longer worked. Reverted back to original. May need to revisit issue 189.

**Comment by Thargoids** [comment]
I don't understand how this issue could have arisen as a result of #195 (i.e. the pull request intended to fix #189). #189 appears to relate strictly to Pro, whereas I opened this case strictly for an issue in ArcMap. Please clarify?

**Comment by pHill5136** [comment]
@Thargoids Yep. Still issue in arcmap... Looked at it incorrectly and conflated with another unrelated issue.

**Comment by pHill5136** [comment]
@Thargoids @nfeuerstein Fixed this. Pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/230

**Comment by elinz** [comment]
@pHill5136 @mfunk Check out the Pro Addin. It uses a cross hair icon.

**Comment by mfunk** [comment]
No build going on yet. Starting one now.

**Comment by mfunk** [comment]
Duh. Realized that this isn't merged yet.

**Comment by mfunk** [comment]
PR merged, waiting to see if it gets into the newest builds.

**Comment by mfunk** [comment]
Testing in 10.4.1 on Build 1067 and Map Point cursor changes to  **+** over the map for *Lines*, *Circle*, *Ellipse*, and *Rings*:

![image](https://cloud.githubusercontent.com/assets/3093182/21726080/018d5bf0-d3f0-11e6-99c8-e7eb94f8e9f1.png)
