### ISSUE TITLE
Entering very large Radius/Diameter when creating a circle causes graphical glitch with multiple lines drawn across map (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#198]
**Procedure:**

1. Add a world background data source in ArcMap
2. Display Circle tab on Distance and Direction addin UI panel
3. Click Map Point tool
4. Click on map to create a point
5. Click in Radius/Diameter text box
6. Enter a 1 and then keep adding zeros

**Result:** From 100000000000 upwards multiple intersecting lines are drawn across map (which presumably is not desired behaviour)

**Result expected:** the glitch is not seen. User is informed that value is beyond bounds.

**Comment by Thargoids** [comment]
![glitch](https://cloud.githubusercontent.com/assets/24588999/21352223/731bb3ec-c6b8-11e6-8167-bdd404022af1.png)

**Comment by Thargoids** [comment]
This issue also occurs with:

Circle tab:
Time field
Rate field

Ellipse tab:
Axis: Major

**Comment by mfunk** [comment]
Ok so this brings up the idea that there are critical limits for different units for these parameters. We'll need to research what each one should be for each relevant parameter on each tool. Essentially what is happening is that the graphic is wrapping around the globe and over itself many times... and looks like crap. We'll need to trap those numbers and display some kind of message about self-overlapping features.

**Comment by rjones0** [comment]
I examined using get_IsSimpleEx to determine when the polygon becomes self-intersecting (as an indicator that the polygon should not be displayed) but the operation is slow to execute when the intersections are many.

Ref:
http://desktop.arcgis.com/en/arcobjects/latest/net/ITopologicalOperator3_IsSimpleEx.htm

**Comment by rjones0** [comment]
It would seem to me that the limit for Radius should be the value at which the polygon will encompass the entire earth, i.e. just slightly over 20000km. However when investigating I discovered dateline issues as described in #280. I think that case should be resolved before this one, as improved handling of the dateline may well make the issue described in this case disappear.

**Comment by rjones0** [comment]
PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/318

**Comment by rjones0** [comment]
Fix for:

Ellipse tab:
Axis: Major

still outstanding

**Comment by rjones0** [comment]
PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/322

**Comment by lfunkhouser** [comment]
Reopened issue for MT PEs to verify

**Comment by NatalieCampos** [comment]
The errors that created this issue have been resolved.  When adding a large value to either the radius or diameter of circles or the Major axis of Ellipse an invalid input error is thrown.

![image](https://cloud.githubusercontent.com/assets/5116835/25919972/2e587948-3585-11e7-839a-34812135a3b0.png)
