### ISSUE TITLE
Adding an ellipse, without clicking on the map to create a point first, causes an ellipse to be created at the place where the mouse left the map  (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#201]
**Procedure:**

1. In ArcMap add a world background data source
2. Display Ellipse tab on Distance and Direction addin UI panel
3. Click Map Point tool
4. Move mouse over map but do not click on map
5. Enter values in Major, Minor, Angle text boxes
6. Press Enter

**Result:** Ellipse is created at the point where the mouse left the map. Presumably this is to support user entering point non-interactively, however, if they merely forgot to click on the map it seems like strange behaviour when the point at which the mouse left the map is used as the center point of the ellipse being created.

**Result expected:** for discussion. The Center Point text box fulfils both the task of displaying the current location of the mouse and of recording the location to be used for the center point. Perhaps a separate 'Input Center Point' text box could be provided that does not update on mouse move, but only updates either a. when a user clicks a point on the map or b. when the user enters values manually.

Issue is linked to #200, #202.

**Comment by rjones0** [comment]
@nfeuerstein I'm guessing priority might not be high any longer since the case is Version - After Next?

**Comment by rjones0** [comment]
Fixed in PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/319

**Comment by rjones0** [comment]
As designed

**Comment by lfunkhouser** [comment]
Reopening for MT PEs to verify

**Comment by NatalieCampos** [comment]
Following the steps outlined below no longer cause the ellipse/circle/ring to be drawn at the last mouse location.

Procedure:

1. In ArcMap add a world background data source
2. Display Ellipse tab on Distance and Direction addin UI panel
3. Click Map Point tool
4. Move mouse over map but do not click on map
5. Enter values in Major, Minor, Angle text boxes
6. Press Enter
