### ISSUE TITLE
Adding rings, without clicking on the map to create a point first, causes rings to be created at the place where the mouse left the map  (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#202]
**Procedure:**

1. In ArcMap add a world background data source
2. Display Rings tab on Distance and Direction addin UI panel
3. Click Map Point tool
4. Move mouse over map but do not click on map
5. Enter values in Number of Rings, Distance Between Rings, Number of Radials text boxes
6. Press Enter

**Result:** Rings are created at the point where the mouse left the map. Presumably this is to support user entering point non-interactively, however, if they merely forgot to click on the map it seems like strange behaviour when the point at which the mouse left the map is used as the center point of the rings being created.

**Result expected:** for discussion. The Center Point text box fulfils both the task of displaying the current location of the mouse and of recording the location to be used for the center point. Perhaps a separate 'Input Center Point' text box could be provided that does not update on mouse move, but only updates either a. when a user clicks a point on the map or b. when the user enters values manually.

Issue is linked to #200, #201.

**Comment by dfoll** [comment]
If you move from the map to the D and D pane with the map point tool enabled the last coordinate will be what was collected from the map if the user does not update the coordinate.

**Comment by rjones0** [comment]
@dfoll I've reopened this issue because I think it's my responsibility as the originator of the case to close it, I hope you don't mind :)

I understand why the issue happens, but I would be very surprised if it were confirmed that this behaviour is intentional or desirable. I think it would be a very strange way to use the tool to be deciding to set your Center Point based on the place where the mouse left the map. If we accept that the behaviour is not intentional, isn't it worth doing something about it?

I think we could clear the Center Point field completely whenever the map does not have focus and the user has not created a point. This would avoid the problem of the point where the mouse left the map being used inadvertently as the center point, and would make it explicit that the user has to either a. click on the map to set the Center Point location or b. click in the field to set the value manually.

I'm perfectly willing to be convinced that it's not worth fixing, but at the moment I don't see any reasons why we shouldn't attempt to address this issue.

**Comment by rjones0** [comment]
Having difficulty finding a mechanism for catching the 'mouse out' event of the map in ArcMap. I think I need to catch that to be able to clear the text box when the mouse leaves the map.

**Comment by kgonzago** [comment]
@rjones0 Could you use IDisplayTransformation::DeviceFrame based off of your activeView (map)? this will give you a client rect that can be used in the mouse_move event to determine if your mouse is off the map.

**Comment by rjones0** [comment]
I have the majority of the code ready now. Some dll interop was required, hopefully this won't be a problem! I couldn't see how to do it without this.

**Comment by rjones0** [comment]
Almost fixed, pending final testing: https://github.com/rjones0/distance-direction-addin-dotnet/commit/1bbc2af9b18f993a2eb9fceefebc00b1a03a515c

**Comment by rjones0** [comment]
Fixed in PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/319

**Comment by rjones0** [comment]
Behavior is as designed.
