### ISSUE TITLE
Map Point tool is disabled in build 1000

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#205]
The functionality of all three tabs still works if you manually enter values for the input coordinates, however trying to do things interactively is not possible because the map point tool is disabled. The button is there and the visual appearance is that it is active, but it does not do anything when you click on it to try to create something interactively.

**Comment by mfunk** [comment]
Tested in 10.3.1 & 10.5.1 daily (10.4.1 getting patched and rebooted at this time) and works OK on all 4 tabs.
