### ISSUE TITLE
Preview circle is not updated properly after certain edits to fields (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#207]
**Procedure**

1. With Circle tab create point on map using Map Point Tool
2. Click in Radius / Diameter field and enter a value
3. Select all in Radius / Diameter field
4. Press Delete or backspace

**Result:**

The Radius / Diameter text box is empty, but the preview circle remains visible

**Result expected:**

The preview should disappear because the text box is empty

**Additional:**

Same problem observed with Time and Rate fields in Distance Calculator section of Circle tab.

Also a variation on above:

1. With Circle tab create point on map using Map Point Tool
2. Click in Radius / Diameter field and enter a value with a single non zero integer followed by enough zeros to make the preview large enough to be visible
3. Press Home key
4. Press Delete key (not backspace)

**Result**

The Radius / Diameter text box equals zero, but the preview circle remains visible

**Result expected:**

The preview should disappear because the text box contains only zeros

**Comment by rjones0** [comment]
Fixed in local branch, will hold off making a pull request until appropriate.

**Comment by rjones0** [comment]
PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/316

**Comment by rjones0** [comment]
@kgonzago I'd appreciate your input on something - the Time and Rate text boxes on the Circle tab suffer the same issue as the Distance text box (before my last PR), i.e. clearing them does not clear the graphic. However, I cannot use the same fix for Time and Rate as for Distance due to differing data types of the bound variables - Distance is bound to a string, whereas Time and Rate are bound to double data type variables. The effect of this is that clearing the Distance text box completely still results in the 'set' method of the Distance variable being called, and therefore I can clear the graphic if I need to, whereas clearing Time or Rate completely results in the xaml Validation.ErrorTemplate being triggered, and the set method for Time and Rate is never called, thus no opportunity to clear the graphic.

There look to be several potential fixes, none of which are a 5 minute job. However, the simplest that occurs to me is to change the variables TravelTime and TravelRate to string data type and update the code accordingly, so that the structure for handling Distance, TravelTime and TravelRate is identical. Before I do this - are you aware of any reason why TravelTime and TravelRate are not handled in the same way as Distance?

**Comment by kgonzago** [comment]
@rjones0  I believe another developer authored the rate and time logic and did not follow what was already outlined with distance. I'm perfectly fine with having rate and time handled the same way as distance.

**Comment by rjones0** [comment]
Expect this will require manual testing as explained in #316.
