### ISSUE TITLE
Preview circle updates after changing Time or Rate drop downs even when Time / Rate field is empty (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#208]
**Procedure**

1. Use Map Point Tool from Circle tab to create a point on the map
2. Expand Distance Calculator if not expanded
3. Add values to Time and Rate sufficient to be able to see preview circle
4. Select value in Time field and delete
5. Change the Time drop down

**Result**

The preview circle updates

**Result expected**

The preview circle should not update on change of drop down because there is no value in the Time field

**Additional**

This issue occurs for each of the three cases of either or both of the Time and Rate fields being empty, and changing either of the drop downs in any of those three cases shows the same (incorrect) behaviour

**Comment by rjones0** [comment]
I think the issue here is that the text box that is bound to TravelTime uses ValidatesOnExceptions=True. This means that when the text box is completely cleared as in step 4. in the procedure, the set method for TravelTime is not called because ValidatesOnExceptions kicks in. This means that the code (in CircleViewModel.cs) to clear the preview is not called, and therefore when the time units drop down is changed, the code uses a stale value for Time.

I would guess either:

a. the ValidatesOnExceptions needs to be dropped in favour of a custom validation rule that updates the Time variable in CircleViewModel when the textbox is cleared, and then throws an exception if necessary

or

b. when the drop down is changed the code should retrieve the current value from the Time textbox

of the two I think a. is preferable because I would think we want to see the preview disappear immediately the Time textbox is cleared, which would not happen if we chose b.

**Comment by pHill5136** [comment]
please verify pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/384

**Comment by NatalieCampos** [comment]
verified on build 1475. closing
