### ISSUE TITLE
Preview circle disappears beyond a certain size despite there apparently still being room for expansion (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#210]
**Procedure**

1. Using Map Point Tool on Circle tab, create a point on map
2. Interactively expand this to make it as large as possible

**Result**

The preview circle never shrinks to a point, i.e. it is not possible to create a preview circle that encompasses the entire world

**Result expected**

It seems like it should be possible to continue expanding the circle until it encompasses the whole world

**Comment by topowright** [comment]
Looking at this closer I do see a bit of a lag in the circle updating; however, the performance is not hindering use. Also, I do not understand a use case where the user would need to draw a circle capturing the world extent. The output would not be useful based on the radius being larger than the earth it self when drawing is complete. Closing this issue as won't fix.
