### ISSUE TITLE
After creating a point with the Distance Calculator open, hiding the Distance Calculator makes it impossible to finish the circle (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#211]
**Procedure**

1. On Circle tab and with Distance Calculator open, use Map Point Tool to create a point on the map
2. Hide the Distance Calculator

**Result**

The Center Point field is cleared and whatever actions are taken it is not possible to complete the circle that was started by adding the point, yet the point remains visible

**Result expected**

After the Distance Calculator is minimized, either the point should be removed along with the Center Point field being cleared, or the Center Point field should not be cleared and it should be possible to complete the circle

**Comment by lfunkhouser** [comment]
@dfoll I get if you close the Distance Calculator, you shouldn't be able to complete the circle, but was this a design decision made to keep the point even though the field is cleared?

**Comment by dfoll** [comment]
I do not see this behavior happening any more in 10.6.1 with MT 48
