### ISSUE TITLE
Better error message when Distance Calculator Time / Rate fields are empty (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#213]
**Procedure**

1. In Circle tab and with Distance Calculator open, create a point on map using Map Point Tool
2. Delete value from Time field (issue also occurs with Rate field)

**Result**

Red exclamation shown around field, and hovering over field shows message 'Input string was not in a correct format'

**Result expected**

A more accurate error message e.g. 'Enter value' is preferable

**Comment by pHill5136** [comment]
Error reads 'enter value' when the time or rate are empty. Still reads 'invalid input' when invalid values are added. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/382

**Comment by NatalieCampos** [comment]
Verified on build 1475. Closing issue.
