### ISSUE TITLE
No error shown when massive values are entered in Time and Rate fields (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#214]
**Procedure**

1. On Circle tab show Distance Calculator if not shown
2. Create point on map using Map Point Tool
3. Click in Time field (or Rate field)
4. Enter a 1 and hold down 0 to keep adding zeros

**Result**

No error message is shown

**Result expected**

Since an error message is shown when the field is empty, it seems reasonable to expect to be warned also when the input number is ridiculously large

**Comment by rjones0** [comment]
Also present on Rings tab:

1. Add point
2. Change units combobox to Miles
3. Click in Distance between Rings field
4. Add value 100000000000000
5. Press Enter

Result:

Massive graphic is created. Zooming in caused ArcMap to crash.

**Comment by rjones0** [comment]
Resolved by PRs https://github.com/Esri/distance-direction-addin-dotnet/pull/318 and https://github.com/Esri/distance-direction-addin-dotnet/pull/322

**Comment by rjones0** [comment]
Circle issues resolved by PRs #318 and #322.

Rings issue resolved by https://github.com/Esri/distance-direction-addin-dotnet/pull/323

**Comment by Dbarnes1** [comment]
verified, closing.
