### ISSUE TITLE
Line tool: starting/ending point parameters do not handle coordinates entered in Longitude Latitude order (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#216]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21409338/949a2888-c78e-11e6-8e40-9ea6a21028cc.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21409345/9ea8de82-c78e-11e6-9d8c-ef141cf5863a.png)

**Comment by rjones0** [comment]
I have a fix for this locally, will make pull request when possible.

**Comment by kgonzago** [comment]
Similar to #217, this has been addressed in [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/495).

**Comment by topowright** [comment]
Verified

**Comment by topowright** [comment]
This cannot be finished until the Distance and Direction documentation topics are versioned and released

**Comment by ACueva** [comment]
Added to "Issues Addressed" section in Distance and Direction Release notes. Will assign to @dfoll for review once completed.

**Comment by ACueva** [comment]
Removing "Known Issue" label as this has now been addressed and is listed in the "Issues Addressed" section of our release notes.

**Comment by lfunkhouser** [comment]
Removing E-verified label. This is not on dev and therefore cannot be verified.

**Comment by ACueva** [comment]
This is not ready.  I cannot get the lines to draw using the following workflow:

Environment:
ArcMap 10.6

Add a basemap, and enter the following:
Starting point: 116.948W 34.73N
Ending point: 24.895304E 60.236869N

If I paste in these coordinates.  It does not give an error, it just doesn't work.
If I manually type in the coordinates it gives the following:
![snag_3f3352](https://user-images.githubusercontent.com/3093940/36699569-ecaf21a0-1b01-11e8-9816-687adc9d3817.png)

**Comment by ACueva** [comment]
FYI @kgonzago @csmoore

**Comment by kgonzago** [comment]
@ACueva I'll take a look at this.

**Comment by kgonzago** [comment]
@ACueva Issue fixed in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/526)
