### ISSUE TITLE
Line tool: starting/ending point parameters do not handle coordinates entered in Longitude Latitude order (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#217]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21409407/e911e72a-c78e-11e6-8028-f26dfe6a5958.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21409385/d4840b80-c78e-11e6-9f9d-0c92993c723f.png)

**Comment by rjones0** [comment]
I have a fix for this locally, can make pull request when possible if necessary (see #223).

**Comment by csmoore** [comment]
Note: This still seems to be an issue after #494 - I tested with:

Works:
34.73N 116.94W
60.23N 110.89W

Doesn't work (Red validation error box):
116.94W 34.73N
110.89W 60.23N

**Comment by kgonzago** [comment]
Picking this up since this ties in with CC library stuff I worked on.

**Comment by kgonzago** [comment]
Applied fix and submitted [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/495)

**Comment by topowright** [comment]
This is no longer an issue in Distance and Direction, but it is still an issue in Visibility.

**Comment by topowright** [comment]
Verified

**Comment by topowright** [comment]
This cannot be finished until the Distance and Direction documentation topics are versioned and released

**Comment by ACueva** [comment]
Added to "Issues Addressed" section in Distance and Direction Release notes. Assigning to @dfoll for review.

**Comment by ACueva** [comment]
Removing "Known Issue" label as this has now been addressed and is listed in the "Issues Addressed" section of our release notes.

**Comment by lfunkhouser** [comment]
@topowright This issue still has a task to QC the Doc. Has that been completed. Cannot close or add a closing E-label to item that still has tasks remaining.

**Comment by topowright** [comment]
Removed the doc label as this has been documented.

**Comment by lfunkhouser** [comment]
@topowright I just checked on the dev site for documentation. This has been documented for ellipse and circle, but not for lines as indicated by this issue. If we are calling out some, we should call out all areas of functionality and issue #217 should be added to the issues addressed.
