### ISSUE TITLE
Circle tool: Center Point parameter does not handle coordinates entered in Longitude Latitude order (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#219]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21409756/d7bc6778-c790-11e6-8304-6965084e9eca.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21409766/e6065eb0-c790-11e6-8ea6-e4305018b629.png)

**Comment by rjones0** [comment]
I have a fix for this locally, can make pull request when possible if necessary (see #223).

**Comment by kgonzago** [comment]
Addressed in #495 PR

**Comment by topowright** [comment]
This cannot be finished until the Distance and Direction documentation topics are versioned and released

**Comment by ACueva** [comment]
Added to "Issues Addressed" section in Distance and Direction Release notes. Assigning to @dfoll for review.

**Comment by ACueva** [comment]
Removing "Known Issue" label as this has now been addressed and is listed in the "Issues Addressed" section of our release notes.

**Comment by ACueva** [comment]
Removing - QC Verify (Checklist) tag as this issue has already been marked with a E- Verified tag. FYI @topowright

**Comment by dfoll** [comment]
verified it is no longer listed in the known issues. adding release tag and removing QC verify and moving to for review
