### ISSUE TITLE
Ellipse tool: Center Point parameter does not handle coordinates entered in Long Lat order (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#220]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21410519/3970fdc6-c796-11e6-96db-53d4535bdbc3.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21410521/3d00b22e-c796-11e6-9946-0d997ee538ba.png)

**Comment by rjones0** [comment]
I have a fix for this locally, will make pull request when possible.

**Comment by kgonzago** [comment]
Issue fixed in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/498)

**Comment by ACueva** [comment]
CMS Doc changes have been entered into the Resources section.
- [ ] Filtered list of issues fixed is dependent on https://github.com/Esri/distance-direction-addin-dotnet/issues/519
- [ ] Tech review on new doc needed.

What's left is
- [ ] updating the checklist tests (adding test for lat/long)
- [ ] Verify MT addin functionality works
- [ ] Verify single addin functionality works

**Comment by ACueva** [comment]
Removed this item from the Known issues section in CMS.  Still needs appropriate labels for search functionality.

**Comment by ACueva** [comment]
Closing this issue to make sure it is present in "Issues addressed" section.

**Comment by ACueva** [comment]
Confirmed this issue appears in the "Issues addressed" section of the release notes for the April 2018 release.
![2018-02-27_12-39-16](https://user-images.githubusercontent.com/3093940/36753517-3ea89856-1bbb-11e8-9fb9-04e6080b52ad.png)

**Comment by lfunkhouser** [comment]
@ACueva You removed the **G - QA Create Checklist** label - There is no comment indicating you updated the checklist test to enter coordinates for the center point in long/lat order. Was this work completed?

**Comment by ACueva** [comment]
Yes, I listed the commit a few comments above. https://github.com/ArcGIS/solutions-defense-test-catalog/commit/9c498f768156a76817ee9cc308aa874db4a8a114
