### ISSUE TITLE
Ellipse tool: Center Point parameter does not handle coordinates entered in Longitude Latitude order (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#221]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21410565/7117ca8e-c796-11e6-8ed0-24d8ea68b085.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21410575/7e2326ce-c796-11e6-9dcb-1cf617a413f1.png)

**Comment by rjones0** [comment]
I have a fix for this locally, can make pull request when possible if necessary (see #223).

**Comment by kgonzago** [comment]
Addressed in #495

**Comment by topowright** [comment]
This cannot be finished until the Distance and Direction documentation topics are versioned and released

**Comment by ACueva** [comment]
Added to "Issues Addressed" section in Distance and Direction Release notes. Assigning to @dfoll for review.

**Comment by ACueva** [comment]
Removing "Known Issue" label as this has now been addressed and is listed in the "Issues Addressed" section of our release notes.

**Comment by ACueva** [comment]
Removing - QC Verify (Checklist) tag as this issue has already been marked with a E- Verified tag. FYI @topowright

**Comment by dfoll** [comment]
- The checklist test is updated to include using lon/lat when manually inputting an ellipse center point.
- I verified those checklist steps cause this issue to pass
- The release notes have this listed as an issue addressed already

Can we move this to the done column?
