### ISSUE TITLE
Rings tool: Center Point parameter does not handle coordinates entered in Longitude Latitude order (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#223]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21410693/9d6b9056-c797-11e6-9950-02b70b5d9512.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21410696/a253afa4-c797-11e6-920b-34a0c508253f.png)

**Comment by pHill5136** [comment]
@elinz @nfeuerstein @kgonzago To do this correctly we will have to define a new field for user to define the format for incoming points. This requires ui changes. Lots of coding. Is this something we want to document and add as enhancement to version after next (same goes for all the other dd tools)?

**Comment by elinz** [comment]
@pHill5136 @nfeuerstein @kgonzago Maybe I'm missing something, but from my testing the tool already is handling how to interpret the input format.

**Comment by nfeuerstein** [comment]
The Coordinate Conversion tool was modified to allow lat/long OR long/lat.  Is this the same modification, but in Distance and Direction?  Or something more complex?

**Comment by pHill5136** [comment]
@nfeuerstein @elinz  @kgonzago I think the best way to do this is have a combo box that allows the user to define the input format for cases where it is not obvious the format needed (i.e points like (10, 0, 20.0)). To do this will require quite a bit of coding including ui changes that we want to avoid as much as possible at this time.

**Comment by kgonzago** [comment]
@pHill5136 Agreed. I suggest tackling any UI changes in our next release.

**Comment by rjones0** [comment]
I have a fix for this locally which just reverses coordinates order when trying to parse lat long coords. I will hang on to this in case we need it. Same fix should work for all issues involving lat/long coord order: #216, #217, #218, #219, #220, #221, #222.

**Comment by pHill5136** [comment]
@rjones0 @kgonzago @nfeuerstein I think we should hold onto this for now. We will have to discuss exactly how we want to approach this for all the dd tools. For instance do we want long lat coords to be user defined i.e user tells us s/he is adding coordinates as long lat. Will have to turn off functionality when not using decimal coordinates also might consider turning off map point tool when entering long lat.

**Comment by kgonzago** [comment]
@rjones0 @pHill5136 sorry for the late reply and am not ignoring the suggestion. We have a meeting to discuss the lat/long and long/lat issue. Decisions made from that meeting will dictate how this issue will be resolved.

**Comment by kgonzago** [comment]
Addressed in #495

**Comment by topowright** [comment]
This cannot be finished until the Distance and Direction documentation topics are versioned and released

**Comment by ACueva** [comment]
Removing - QC Verify (Checklist) tag as this issue has already been marked with a E- Verified tag. FYI @topowright

**Comment by ACueva** [comment]
Removing "Known Issue" label as this has now been addressed and is listed in the "Issues Addressed" section of our release notes.

**Comment by lfunkhouser** [comment]
removing the closing label, e-verified. This is not published and able to be tested on dev.
