### ISSUE TITLE
Dark Theme in Pro makes settings invisible

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#233]
Like the other parts of the add-in, using the dark theme in pro messes with the visibility of settings. The example I have is the drop down in the edit settings dialog has no visible text until you scroll over it. 

![image](https://cloud.githubusercontent.com/assets/13024357/21692490/fcd640a4-d331-11e6-95d9-54bb76da4557.png)

**Comment by mfunk** [comment]
Thanks @Dbarnes1 , can you add a screenshot as an example of what it looks like? Thanks.

**Comment by Dbarnes1** [comment]
And again with the save output button. 

![image](https://cloud.githubusercontent.com/assets/13024357/21692778/46a1c9d2-d333-11e6-8de6-658555e8a490.png)

**Comment by pHill5136** [comment]
@Dbarnes1 fixed pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/251

**Comment by joebayles** [comment]
@pHill5136 looks pretty good! The only thing I see is Distance Calculator is still hard to read.
![image](https://cloud.githubusercontent.com/assets/5016557/21826199/6f2db9cc-d73b-11e6-83a0-887daff773bf.png)

**Comment by Dbarnes1** [comment]
adding on to @joebayles distance calculator comment, the rate and time labels are also hard to read when the distance calculator is expanded: 

![image](https://cloud.githubusercontent.com/assets/13024357/21826579/e7ff05b2-d73c-11e6-9d4e-76366c82ab0f.png)

**Comment by joebayles** [comment]
As of the 11 January 0900 build:
- Distance Calculator is still dark gray.
- Time and Rate are still black.
 - Radial buttons are still empty.

FYI @Dbarnes1 @pHill5136

**Comment by chris-fox** [comment]
In regards to changing the text of the combo boxes to black, you can make a pretty small change to the combo box style to have them inherit the Pro combo box style so that they have a black background and white foreground.

You just need to change need to make the following change to the [MAResourceDictionary.xaml](https://github.com/Esri/distance-direction-addin-dotnet/blob/dev/source/DistanceAndDirection/DistanceAndDirectionLibrary/MAResourceDictionary.xaml) file.

    <Style TargetType="ComboBox" BasedOn="{StaticResource {x:Type ComboBox}}">
            <Setter Property="ItemTemplate">

![image](https://cloud.githubusercontent.com/assets/6796763/21869962/17369c6e-d828-11e6-8182-8d5416351749.png)

![image](https://cloud.githubusercontent.com/assets/6796763/21869979/2904f54e-d828-11e6-805e-6306c787ac2c.png)

This gives it a similar look to other Pro combo boxes. I also made a similar change for the TextBlock under Radius/Diameter in the screenshots below.

**Comment by joebayles** [comment]
As of the 0900 build today:
- Lines
  - [ ] Save As - Save Outputs Radial buttons are blank
- Circle
  - [ ] Distance Calculator drop-downs are blank (From and Radius/Diameter drop-downs work fine)
  - [ ] Time and Rate text is black
  - [ ] Save As - Save Outputs Radial buttons are blank
- Ellipse
  - [ ] Save As - Save Outputs Radial buttons are blank
- Rings
  - [ ] Save As - Save Outputs Radial buttons are blank

FYI @pHill5136

**Comment by joebayles** [comment]
FYI @pHill5136 @nfeuerstein everything is fixed except for Distance Calculator drop-downs and the dark text, of which only the former is what I would call a showstopper.
![image](https://cloud.githubusercontent.com/assets/5016557/21940871/081a18e2-d97b-11e6-9721-7536f415acf1.png)

**Comment by nfeuerstein** [comment]
Changing priority of all "dark theme" issues to medium-priority.  If we can nail it - do it and do it right - we do it.  Otherwise, it can wait until next-release.  Not a show stopper.

**Comment by nfeuerstein** [comment]
Moving all "dark theme" issue to version- after next.

**Comment by pHill5136** [comment]
please verify. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/414

**Comment by ACueva** [comment]
Verified the following issues have been addressed.

- Lines
  - [ ] Save As - Save Outputs Radial buttons are blank
- Circle
  - [ ] Distance Calculator drop-downs are blank (From and Radius/Diameter drop-downs work fine)
  - [ ] Time and Rate text is black
  - [ ] Save As - Save Outputs Radial buttons are blank
- Ellipse
  - [ ] Save As - Save Outputs Radial buttons are blank
- Rings
  - [ ] Save As - Save Outputs Radial buttons are blank
