### ISSUE TITLE
Pro tooltips for Distance and Direction are gone

### ISSUE THREAD

**Issue by mfunk** [Esri/distance-direction-addin-dotnet#234]
Found this one in today's Build 1057 from Jenkins. The Distance and Direction Add-In lost it's tool tips.
![image](https://cloud.githubusercontent.com/assets/3093182/21691978/a2bb5e08-d32f-11e6-8e59-75d268b225d1.png)

This was originally logged as #185.

1) install the add-in
2) Open Pro
3) Go to Add-In ribbon and hover over *Distance and Direction*

Per the previous issue this should read:

> Interactively create geodetic circles, ellipses, range rings, and distance calculations based on time and rate. Created graphics can be saved to feature classes, shapefiles, and KMZ files.

**Comment by pHill5136** [comment]
@mfunk @nfeuerstein fixed pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/242.

**Comment by lfunkhouser** [comment]
Assigning to @mfunk to verify

**Comment by joebayles** [comment]
As of 11 January 0900 build, this is still an issue.
FYI @mfunk @pHill5136

**Comment by mfunk** [comment]
Getting a !@#$!@#$ certificate error opening Pro that is causing it to become unresponsive. Looks like I won't be able to check it out. 😠

**Comment by mfunk** [comment]
Nvrmnd. Bad Project. But yes, @joebayles is correct I'm not seeing this fixed in Pro 1.4:

![image](https://cloud.githubusercontent.com/assets/3093182/21863068/c5977310-d7f0-11e6-9ec4-cf2fb3063a29.png)

I installed from the single add-in build 1091.
Sorry @pHill5136.
