### ISSUE TITLE
Warning ensuring starting point is created for lines with distance and bearing- Pro

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#235]
If a user is creating multiple lines from distance and bearing, and forgets to enter a starting point each time, they may get frustrated typing in distance and length values, selecting enter, and not understanding why nothing happens. There should be a warning sign popping up telling the user that they need to create a starting point.

To reproduce: 
1. create several lines from distance and bearing, first with selecting a starting point, and then distance and angle values. Several lines will be created.
2. skip adding a starting point, and enter values under distance/length and angle, and click enter. Nothing will happen, but there is no reminder that you forgot to add a starting point.

**Comment by topowright** [comment]
@dfoll I do not think this is an issue that we should address. We would expect the users to always put in a starting point. I feel like this can be closed.

**Comment by lfunkhouser** [comment]
A start point is required to draw a line. Closing.
