### ISSUE TITLE
Creating circle from Radius or diamater and having circle cross date line creates red outlines along edge of map that shouldn't exist.

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#236]
See screenshot: 
![image](https://cloud.githubusercontent.com/assets/13024357/21693958/ce32000c-d337-11e6-8c69-add28dccf546.png)

When creating a circle from radius or diamater, these straight red lines appear. I shouldn't see these red lines around the border of the map

**Comment by topowright** [comment]
![image](https://cloud.githubusercontent.com/assets/5488313/21959147/7f45cb8e-da73-11e6-9ad8-42de3c6d13df.png)
Arcgis Pro in a 2D Map does not support continuous features across the International date line this has to be supported by using a multi part feature. This can be seen by the one entry in the feature table.

**Comment by lfunkhouser** [comment]
The vertical lines are not intended, but draw as a result of a dependency on ArcGIS Pro. Removing the "as designed" label.

**Comment by lfunkhouser** [comment]
User gets a "Point is out of bounds" warning. Closing.
