### ISSUE TITLE
Create circle from diamater- Map Point Tool doesn't work properly

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#237]
I'm getting this issue where if I use the map point tool to create a circle from diameter, I can't get the map point tool to properly drag out the circle to the size I want. 

What should happen: the map point cursor and the black preview circle follow each other interactively, the map point cursor should be on some point in the circumference of the circle. 

What is happening: the black preview circle doesn't follow the map point tool cursor, erratically resizing itself at a much smaller extent than the map point cursor.

**Comment by Thargoids** [comment]
It appears that when Diameter is selected in the drop down the value in the Radius / Diameter text box is half the value it should be, and this same halved value is apparently used to draw the circle.

**Comment by pHill5136** [comment]
@Dbarnes1 fixed pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/250

**Comment by Dbarnes1** [comment]
confirmed fixed. closing.
