### ISSUE TITLE
Map point tool cursor shows up as soon as you open distance and direction for any shape, even though cursor should still be default "explore"

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#238]
When opening the distance and direction tool for the first time, or switching between any of the different tabs for creating different features, you will see that the cursor for your mouse is using the map point tool icon when panning over the map. This is wrong because the mouse is still in explore mode until you actually click on the map point tool button and navigate over the map to create features.

**Comment by dfoll** [comment]
This is not happening in the current build.

**Comment by Dbarnes1** [comment]
verified fixed. closing
