### ISSUE TITLE
Labels not drawn for manually typed input coordinates in ArcMap

### ISSUE THREAD

**Issue by mfunk** [Esri/distance-direction-addin-dotnet#243]
Drawing Lines by typing coordinates in for **Starting Point** and **Ending Point** produces a line without labels, whereas using the *Map Point* tool's line produces labels.

Steps:
1) Select *Lines* tab
2) Type '0.0 .0.0' for the **Starting Point** (without the single quotes)
3) Type '5.0 5.0' for the **Ending Point** (without the single quotes)
4) Select "Enter"
A line is drawn in Gulf of Guinea pointing to the northwest, which is correct, but there is no labels

5) Select **Map Point** tool and draw a line roughly parallel.
A second line is drawn WITH LABELS.

![image](https://cloud.githubusercontent.com/assets/3093182/21727723/83060e96-d3f7-11e6-9ab8-a520868e508e.png)

**Comment by pHill5136** [comment]
@mfunk fixed pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/252

**Comment by mfunk** [comment]
Looks good!

![image](https://cloud.githubusercontent.com/assets/3093182/21862242/396ee8c6-d7ed-11e6-8da4-4a87637b97cc.png)
