### ISSUE TITLE
Creating a geodesic line from distance and bearing - ArcMap

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#245]
There are several times when I have to restart ArcMap because the Map Point tool doesn't work properly. I can click the button and my cursor turns into the crosshairs, but clicking around does nothing.

Daily Build Military Tools and ArcGIS Desktop 10.5

**Comment by dfoll** [comment]
@joebayles This is not happening in the current build.

**Comment by joebayles** [comment]
Verified, closing.
