### ISSUE TITLE
Creating a Ring in Distance and Direction - ArcMap

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#247]
The instructions say:
7. Click the Map Point tool.
8. Click on the map to designate the center range ring.
9. Press the Enter key.

This workflow will not work. There needs to be an additional step between 8 and 9 to click back into the Distance and Direction pane to reactivate it (or change that issue in the add-in).

**Comment by pHill5136** [comment]
@joebayles @nfeuerstein Is this just a documentation issue?

**Comment by joebayles** [comment]
Ideally, no. While it seems inane, it's just a little kludgy to have to reactivate the pane.

So, for v.next? Yes, it's a doc issue. for v.after-next, I would say we should try to enhance the software.

**Comment by Dbarnes1** [comment]
I'm assigning it to myself- this is pretty much a doc issue, you don't have to reactivate the pane if you click on the map point tool, then enter the parameters. That workflow makes more sense anyway. I'm going to rewrite the steps and reassign it to @joebayles to verify.

**Comment by Dbarnes1** [comment]
Ok I switched the steps around so they work properly with the way the add-in is designed. @joebayles this will be ready to verify in the next build.
