### ISSUE TITLE
Creating a Ring zeroes out some values - ArcMap

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#248]
When creating a ring from a distance and number of rings, hitting enter to create the ring zeroes out Distance Between Rings and Number of Radials, but not Number of Rings.

**Comment by Thargoids** [comment]
@mfunk @pHill5136 I'm wondering if this is by design - please confirm.

**Comment by dfoll** [comment]
This is as designed, but I think @kgonzago or @jmccausland can give more background on this issue.

**Comment by rjones0** [comment]
@dfoll @joebayles are you able to advise on protocol with regards to closing issues - since we think this is as designed can I close the case or do we leave it to the originator (as in some other issue tracking I've come across)?

**Comment by joebayles** [comment]
@rjones0 I would just comment when you close it out, and say "this is intended functionality" or "this works as designed." I think it is helpful to mention _why_ it's intended functionality if possible, but if this is not what @nfeuerstein I'm sure she can weigh in and reopen an issue.

As designed.
