### ISSUE TITLE
Range tool: Clicking Map Point tool twice disables Map Point tool (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#253]
**Procedure**

In Rings tab click on Map Point tool
Hover mouse over map - cross hair cursor shown, indicating tool is active
Click on Map Point tool
Hover mouse over map - normal mouse cursor pointer shown

**Result**

Map Point tool is disabled

**Result expected**

The Map Point tool should remain enabled, whereas at the moment clicking on the tool multiple times causes toggling type behaviour.

It seems that the cause is that the code that is called on double click when in interactive mode is being called by the second click (i.e. the 'toggle off' click) on the Map Point tool.

**Comment by dfoll** [comment]
is this expected behavior? the way this is written, it sounds like the map point tool was enabled, then disabled

**Comment by elinz** [comment]
@dfoll @rjones0 I tested the latest build 14 Jan 2017 09:12 and the Map Point tool on the Rings tools is working as I would expect. Meaning that the Map Point tool is only enabled or disabled when the user clicks on the tool. The Map Point tool should not remain enabled at all times.
