### ISSUE TITLE
Rings: clicking Map Point tool changes icon to shaded blue version as shown only during mouse over for Lines, Circle, Ellipse tabs (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#254]
**Procedure**

With Range tab displayed click on Map Point tool
Move mouse away from tool

**Result**

Map Point button changes to blue shaded version, as used to indicate mouse over on the other tabs

**Result expected**

Blue shaded version of button is only shown during mouse over

**Comment by dfoll** [comment]
as designed
