### ISSUE TITLE
Distance and Direction: Line tool - created graphic is not labeled and has no arrowhead (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#256]
build 11 Jan 2017 13:51 ArcGIS Pro addin

![image](https://cloud.githubusercontent.com/assets/4635490/21868882/b6979408-d809-11e6-839f-ca2c9dd17c30.png)

**Comment by elinz** [comment]
Here's how it looks in ArcMap:
![image](https://cloud.githubusercontent.com/assets/4635490/21869219/6479791e-d80b-11e6-98dc-431a1d494b47.png)

**Comment by dfoll** [comment]
We are able to create labels on the top of targets in ArcGIS Pro using the Visibility add-in. We should look at this as a possible way forward.

**Comment by lfunkhouser** [comment]
Closing. Graphics are not labeled in ArcGIS Pro. #542 has been created to handle the labels on lines.
