### ISSUE TITLE
Distance and Direction: Ellipse tool: Created graphic is not labeled (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#257]
build 11 Jan 2017 13:51 ArcGIS Pro addin
![image](https://cloud.githubusercontent.com/assets/4635490/21868924/ef5845ee-d809-11e6-9a12-1f2f1c741b25.png)

**Comment by elinz** [comment]
Here's how it's labeled in ArcMap...
![image](https://cloud.githubusercontent.com/assets/4635490/21869117/d4bad7c8-d80a-11e6-966c-a0f059d68924.png)

**Comment by dfoll** [comment]
We are able to create labels on the top of targets in ArcGIS Pro using the Visibility add-in. We should look at this as a possible way forward.

**Comment by nfeuerstein** [comment]
Labels are still a limitation in Pro.

**Comment by lfunkhouser** [comment]
Closing. Graphics are not labeled in ArcGIS Pro. #543 has been created to handle the labels on ellipses.
