### ISSUE TITLE
Distance and Direction: Rings tool - created graphic is not labeled (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#258]
build 11 Jan 2017 13:51 ArcGIS Pro addin
![image](https://cloud.githubusercontent.com/assets/4635490/21868967/1f192dd4-d80a-11e6-91b4-7f60bda097e1.png)

**Comment by elinz** [comment]
Can't include a screenshot of what it looks like in ArcMap as it's not labeling either #259

**Comment by elinz** [comment]
@nfeuerstein I can't show you what it looks like from the ArcMap addin as that's not working either, but here is what the labels looks like from the widget:
![image](https://cloud.githubusercontent.com/assets/4635490/21869954/ebf90780-d80e-11e6-867f-b70bceaaddb5.png)

**Comment by dfoll** [comment]
We are able to create labels on the top of targets in ArcGIS Pro using the Visibility add-in. We should look at this as a possible way forward.

**Comment by nfeuerstein** [comment]
Labels are still a limitation in Pro.

**Comment by lfunkhouser** [comment]
Closing. Graphics are not labeled in ArcGIS Pro. #544 has been created to handle the labels on created rings.
