### ISSUE TITLE
Distance and Direction: Rings tool - created graphic is not labeled (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#259]
build 11 Jan 2017 13:51 addin (tested in ArcMap 10.3.1)
![image](https://cloud.githubusercontent.com/assets/4635490/21869048/8a0e458e-d80a-11e6-9207-474070036f99.png)

**Comment by nfeuerstein** [comment]
@elinz what is the expected label?

**Comment by elinz** [comment]
@nfeuerstein oops. Sorry. Should have included it. I can't show you from the Pro addin as that's not working either, but here is what the labels looks like from the widget:
![image](https://cloud.githubusercontent.com/assets/4635490/21869954/ebf90780-d80e-11e6-867f-b70bceaaddb5.png)

**Comment by rjones0** [comment]
PR #264

**Comment by joebayles** [comment]
I don't see a label, tested on 10.5 and the latest build.
![image](https://cloud.githubusercontent.com/assets/5016557/21913707/e799bbf6-d8e2-11e6-819b-a0e7d8ada847.png)

**Comment by rjones0** [comment]
Tested at 10.5 and looks ok to me - perhaps the build you have doesn't include the fix for some reason?

![image](https://cloud.githubusercontent.com/assets/24588999/21935281/d9838368-d9a4-11e6-82c7-9eb5314a6620.png)

**Comment by rjones0** [comment]
Ok I think I see now - no labels are created when in Interactive mode. I will investigate.

**Comment by joebayles** [comment]
Just tested in 10.5 Interactive and... not.

Interactive:
![image](https://cloud.githubusercontent.com/assets/5016557/21942799/4e476268-d983-11e6-82b4-cd91979cd8db.png)

Non:
![image](https://cloud.githubusercontent.com/assets/5016557/21942804/535d2378-d983-11e6-83e7-aa3590201fe5.png)

**Comment by elinz** [comment]
@rjones0 @pHill5136 @joebayles @nfeuerstein Issue with labeling when user selects "Miles" as units.

The Rings tool is now labels miles as "Mile_USs":
![image](https://cloud.githubusercontent.com/assets/4635490/21944392/d7c7164e-d98a-11e6-94f9-3d8d0adce8c0.png)
(There is a formatting issue this should have been "Miles_US")

While specifying "US" to represent statue miles is correct. For all other tools in the ArcMap addin we label using "Miles" and in the widget will label using "Miles". We use Miles in all the Unit drop-down controls. The out of the box measure tool in ArcMap uses Miles. We should change the labeling of rings in the addin to use "Miles" as we do everywhere else.

**Comment by elinz** [comment]
@nfeuerstein @rjones0 @pHill5136 Verified on build 13 Jan 2017 16:08. Rings are now being labeled and labeled with Miles instead of Miles_USs.

![image](https://cloud.githubusercontent.com/assets/4635490/21950767/0f0858ac-d9b3-11e6-805b-ebf0b4053e71.png)

Closing issue.
