### ISSUE TITLE
Circle tool: Radius/Diameter values are being converted when unit is changed (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#260]
build 11 Jan 2017 13:51 addin

- I enter a center point, a radius of 1000. Units were set to meters when tab was accessed...
![image](https://cloud.githubusercontent.com/assets/4635490/21869661/8d75b8bc-d80d-11e6-8914-97786704720e.png)

- I now change the Units from Meters to Kilometers...
![image](https://cloud.githubusercontent.com/assets/4635490/21869715/c2798bc4-d80d-11e6-9b7c-c7c03ccf7375.png)

- I click back into Radius / Diameter parameter and hit return so graphic is created...
![image](https://cloud.githubusercontent.com/assets/4635490/21869788/186e609a-d80e-11e6-92fd-bc05001e5108.png)
Instead of the circle having a radius of 1000 kilometers it converted the initial value of 1000 meters and converted to the equivalent kilometers. The tool should not be converting units value when the units is changed.

**Comment by rjones0** [comment]
PR #262

**Comment by joebayles** [comment]
Verified @elinz

**Comment by elinz** [comment]
@joebayles @pHill5136 @rjones0 Issue verified. Closing issue.
