### ISSUE TITLE
Circle tool: ArcMap hangs with 99% CPU core usage on trying to create circle with certain inputs (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#261]
**Procedure**

(note that the order of steps below is important)

1. Click in Center Point text box and add following: 0 0
2. Change distance unit combobox to Kilometers
3. Enter following in Radius/Diameter: 100
4. Change distance unit combobox to Feet
5. Click in Radius/Diameter text box
6. Press Enter

**Result**

ArcMap hangs with a single CPU core maxed out at 100% usage

**Result expected**

Circle should be created as usual, hang not expected

**Comment by rjones0** [comment]
Similar issue with Rings - perhaps the Center Point being at 0 0 is the underlying problem:

**Procedure**

1. Add dataset with coord sys WGS 84
2. Enter following inputs in Rings tool:

Center Point: 0 0
Number of Rings: 10
Distance Between Rings: 1
Units combobox: Meters
Number of Radials: 0

**Result**

ArcMap hangs with single CPU core maxed out at 100%

**Comment by Dbarnes1** [comment]
I was able to replicate this hang

**Comment by joebayles** [comment]
Same, I did notice that it drew something, so probably hanging on the zoom.

**Comment by Dbarnes1** [comment]
![image](https://cloud.githubusercontent.com/assets/13024357/21940542/ba4cea1e-d979-11e6-93b8-487c1d41e5cd.png)


verified. closing.
