### ISSUE TITLE
Rings tool: ArcMap hangs when creating rings with Center Point at/near 0 0 (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#263]
**Procedure**

1. Add dataset with coord sys WGS 84
2. Enter following inputs in Rings tool:

Center Point: 0 0
Number of Rings: 10
Distance Between Rings: 1
Units combobox: Meters
Number of Radials: 0

**Result**

ArcMap hangs with single CPU core maxed out at 100%

Perhaps related to #261

**Comment by nfeuerstein** [comment]
0,0 should be a valid coordinate

**Comment by joebayles** [comment]
I just ran this on 10.5 and still had the issue.

**Comment by Dbarnes1** [comment]
no longer crashing, rings are created: 
![image](https://cloud.githubusercontent.com/assets/13024357/21940492/75ce8582-d979-11e6-92c5-a9c20c121865.png)


closing.
