### ISSUE TITLE
Different Distance Annotations for Range Rings

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#270]
So, created a range ring using metric and imperial measurements, and found this:
![image](https://cloud.githubusercontent.com/assets/5016557/21943265/4db3de42-d985-11e6-8d34-6030149ed6f2.png)

That's 1000 Mile_USs instead of 1000 Miles.

**Comment by nfeuerstein** [comment]
Issue was also found by @elinz here: https://github.com/Esri/distance-direction-addin-dotnet/issues/259 (as a comment).  Closing as a dup.
