### ISSUE TITLE
DD create double arrows when using the distance and bearing option

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#273]
In ArcMap, when using the distance and bearing option a double arrow is generated.  See below.  To reproduce:

1.  Select a location for starting point.
2.  Input a value for distance.
3.  Give a value for bearing.
4.   A double arrow will be generated. 

![image](https://cloud.githubusercontent.com/assets/5116835/21958430/f654b61a-da62-11e6-899c-4deb43c11f2a.png)

**Comment by lfunkhouser** [comment]
Assigning to @pHill5136 to look into this

**Comment by pHill5136** [comment]
@NatalieCampos Fixed and merged

**Comment by NatalieCampos** [comment]
verified and closing
