### ISSUE TITLE
DD Clear graphics button does not clear graphics on screen (ArcMap)

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#274]
the clear graphics button does not automatically clear graphics on the line tab.  An additional click on the map display is required to clear the graphics. This issue was seen when using a layer on disk in the table of contents.  However, this issue is not present if there is a basemap in the display.

To reproduce:

1. Create an arrow of any kind in DD.
2.  Click the clear graphics button.
3.  Notice that the graphic is not  cleared but that the button itself is greyed out.
4.  Click on the map display 
5.  Notice that the graphic is now cleared.

**Comment by rjones0** [comment]
Strangely enough I used to see this issue, but now I cannot recreate it.

**Comment by pHill5136** [comment]
Looks like this is fixed now. Not seeing this behavior.

**Comment by dfoll** [comment]
i've working heavily with distance and direction this morning, using build 1474, have not seen this. closing.
