### ISSUE TITLE
Circle tab - unexpected behaviour of Delete key in Radius/Diameter text box if ending in all zeros

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#278]
**Procedure**

1. Add a point
2. Add a distance in Radius / Diameter (ADDED) - ending in zeros, ex: 100000 (meters)
3. Click in Radius / Diameter to position cursor before initial digit, ex before 1
4. Press Delete key

**Result**

The whole number in the text box is removed to a single 0

**Result expected**

Only the initial digit should be removed

**Environment**

ArcMap and Pro

**Comment by rjones0** [comment]
I have spent some time investigating this looking for a quick fix but have not been able to find one and am wary of changing the coupling between DistanceString / Distance variables in CircleViewModel.cs and TabBaseViewModel.cs. The issue seems to be that changes to Radius / Diameter are translated into a double number and then back into a string, thereby changing e.g. 000 to 0 in the process.

**Comment by csmoore** [comment]
I thought this was a non-reproducible problem, but I do see the problem for 1 unique test case:

Enter 100000, delete the "1" at beginning and text box is changed to "0" 

I've updated the original comment/title to clarify that this is the failing case

**Comment by csmoore** [comment]
This is addressed for ArcMap in branch: https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23278-radius-text-delete-key

However while testing I also noticed the same issue exists in Pro so changing title/tags for this issue and investigating (ArcMap and Pro implementations are quite different for this for some odd reason)

**Comment by csmoore** [comment]
Addressed in #529 - ready for QC/QA after merge

**Comment by BobBooth** [comment]
I have tested this in ArcMap 10.5 with the latest build of MT. 
Deleting the initial digit with a string of 000 after it leaves the 000 values.  I can delete the "1" in 10000 and replace it with 2, get a circle with radius of 20000.

**Comment by BobBooth** [comment]
I noticed and have submitted issue https://github.com/Esri/distance-direction-addin-dotnet/issues/548 while testing this one.
@csmoore

**Comment by BobBooth** [comment]
I also tested on Pro 2.1.0 with the latest build of MT.
This problem is also fixed there.
Interestingly, issue #548 only applies to ArcMap. 
The behavior of the other tabs (Line, Ellipse, Rings) is consistent with the correct Circle tab behavior in Pro.

**Comment by BobBooth** [comment]
The only thing that I think needs to be done for CMS doc would be to list this issue as fixed in the what-is-new page for the next release.
Not sure how best to handle that.
@dfoll

**Comment by dfoll** [comment]
- This has been added as an Issue addressed to the June 2018 topic for Distance and Direction. 
... > ... >ArcGIS for Defense>Distance and Direction>Resources>topics
- This has been added to the June 2018 What's New table on the home page DD
- This has been added to the June 2018 section on the What's new page

@BobBooth if this was just waiting for documentation/tags to be removed, it can be moved to "done"
