### ISSUE TITLE
Circle tool tells the user inputs are not valid when using keyboard input, if the resulting circle will cross the International Date Line. (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#280]
**Procedure:**

Using Circle tab:
1. Ensure From dropdown is set to Radius
2. Ensure units dropdown is set to Kilometers
3. Enter a Center Point of 0 90
4. Enter following in Radius / Diameter: 11000
5. Export the graphic to a feature class or shapefile 

**Result:**

The graphic is created, but if that graphic is exported to a feature class or a shapefile it is an empty feature. 

**Result expected:**
A circle draws across the International Date line

**Comment by rjones0** [comment]
If we fix this issue we may well fix #198 at the same time, i.e. improved handling of the value in the Radius / Diameter text box should prevent us having to explicitly catch #198.

**Comment by rjones0** [comment]
@mfunk @jmccausland I would expect this issue to be handled by having a Radius limit of around 20000km, and by creating a separate polygon on the other side of the dateline in the case that the circle crosses the dateline. Please confirm.

**Comment by rjones0** [comment]
I have created a partial fix, but no pull request until we start work on the next version. The relevant code is here: https://github.com/rjones0/distance-direction-addin-dotnet/commit/64d3f51cd2ab5e3a555f27ac5021e141689e2018#diff-88394ed48d50d1b77ba5fffe994da80b

It may be worth someone reviewing to check my approach looks ok before I go any further.

**Comment by topowright** [comment]
Due to the limitation of core software this will not be fixed. We will not support drawing a feature across the IDL as a featureclass.  The graphics will be able to persist we will just not support feature creation.
