### ISSUE TITLE
Tab Plurality

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#281]
![image](https://cloud.githubusercontent.com/assets/5016557/22002571/ee27f100-dc01-11e6-8eb1-a16d4b9ee9f3.png)

Currently, the tabs display as:

- Lines - Plural
- Circle - Singular
- Ellipse - Singular
- Rings - Plural

Granted, Rings should be plural regardless, because in a single operation we are creating more than one, but not so for the others. So, I suggest we do one of the following:

- Line
- Circle
- Ellipse
- Rings

... or...

- Lines
- Circles
- Ellipses
- Rings

**Comment by lfunkhouser** [comment]
Verified as fixed in build 1157. Closing issue.
