### ISSUE TITLE
Geodetic -vs- Geodesic lines

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#282]
Do our tools create "geodetic" or "geodesic" features? I personally am confused by this. I was under the impression that features that are created that honor the Earth's curvature are "geodetic" while something that relates directly to geodesy is "geodesic". To me, this means that we create "geodetic" lines, not "geodesic". However, our distance and direction add-in says it is creating "geodesic" lines. Are these terms completely interchangable, i was under the impression they are not.  Maybe this is a non-issue.

@mfunk can you please weigh in on this?

Our core software says that we create "geodetic" lines?
https://pro.arcgis.com/en/pro-app/tool-reference/data-management/bearing-distance-to-line.htm

i set milestone to next @nfeuerstein can you please prioritize, and if we don't get an answer, approach someone directly about finding an answer

**Comment by dfoll** [comment]
as far as correctness, it is semantics, but we should pick a way and stick with it. we look silly using them interchangeably without any reason. my vote is for "geodetic" as that is the way that core software refers to the type of lines our software is creating.

https://pro.arcgis.com/en/pro-app/tool-reference/data-management/bearing-distance-to-line.htm

google told me they are nearly interchangeable. speaking to an subject matter expert i was told that either are ok, so once again, i elect that we stick with how core does it.

**Comment by kgonzago** [comment]
to-may-to vs to-mah-to situation?

**Comment by dfoll** [comment]
@pHill5136 this is the issue i was yacking about... i think the only note i don't already state in this issue is that we want to make these changes in all three ... pro, arcmap, and the widgets

**Comment by dfoll** [comment]
also ... "geodetic" is what we decided we are going to use

**Comment by dfoll** [comment]
@kgonzago since you're here... can we get this to happen in the widgets? me and @pHill5136 talked about this... we think it should only exist in distance and direction.

**Comment by dfoll** [comment]
replicated by #285

**Comment by topowright** [comment]
This has been verified.

**Comment by quinonez** [comment]
If your team measure it experimentally then you did a geodetic measurement or geodetic survey. 
If your team calculate it analytically or computationally then you did a geodesic calculation. Now if your team show results from tabulated measurements then you don't have to be confused because is geodetic.
The key question is if 
Do you present values from tabulated experimental data or results from a physical model?
Cheers!
