### ISSUE TITLE
Unit Plurality for the Ellipse Tab

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#284]
In the Ellipse tab for both Pro and ArcMap, the units drop-down for Axis and Orientation are labeled differently:
![image](https://cloud.githubusercontent.com/assets/5016557/22032560/aff1aca8-dc99-11e6-8b2c-a3f0d4c9e59a.png)
![image](https://cloud.githubusercontent.com/assets/5016557/22032564/b1842474-dc99-11e6-9a3a-8ffb5bd22525.png)

Suggest changing the Orientation Unit to Units.

**Comment by lfunkhouser** [comment]
Verified as fixed in build 1157. Closing.
