### ISSUE TITLE
Geodesic vs. Geodetic... the showdown

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#285]
What's the difference? Semantics?

![image](https://cloud.githubusercontent.com/assets/5016557/22032693/59775f16-dc9a-11e6-8067-66cd4b5cde98.png)

>A geodetic feature is one whose measurements account for the inherent distortion of projected space. Geodetic features are useful when you want to create a feature that spans a large distance, such as a flight path across an ocean.

> Geodesic line—The shortest line between any two points on the Earth's surface on a spheroid (ellipsoid). One sample use for a geodesic line is when you want to determine the shortest distance between two cities for an airplane's flight path. Another example is the creation of the path between the point of impact and the point of origin of a missile. This is also known as a great circle line if based on a sphere, rather than an ellipsoid. The geodesic line type allows you to create lines only. In addition, you can create a multi-segment line which is a series of geodesic lines that make up a single line feature. You can use a multi-segment line when you want to create an airplane's flight path with waypoints, such as an air route with multiple stops that make up a full route.

_http://resources.arcgis.com/en/help/main/10.2/index.html#//01m70000003q000000_

FYI @dfoll @mfunk @topowright

**Comment by dfoll** [comment]
as far as correctness, it is semantics, but we should pick a way and stick with it. we look silly using them interchangeably without any reason. my vote is for "geodetic" as that is the way that core software refers to the type of lines our software is creating.

https://pro.arcgis.com/en/pro-app/tool-reference/data-management/bearing-distance-to-line.htm

google told me they are nearly interchangeable.  speaking to an subject matter expert i was told that either are ok, so once again, i elect that we stick with how core does it.

**Comment by joebayles** [comment]
So, @dhagens, can you change the option in the drop-down to Geodetic?

**Comment by dfoll** [comment]
duplicated by #282, @pHill5136 is going to work on this
