### ISSUE TITLE
Drawing line graphics across the International Date Line causes label issues (ArcMap)

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#289]
When creating graphics across the International Date Line the labels show up in the center location of the graphic, which is not correct for this use case: This is because the graphic spreads across the entire world.

![image](https://cloud.githubusercontent.com/assets/5488313/22078709/d425820a-dd6d-11e6-877b-1987e5c0004d.png)

**Comment by topowright** [comment]
@csmoore and @kgonzago can we do better and what would the level of effort be for this?

Currently this is much better than what was done at the time of this issue. 
![image](https://user-images.githubusercontent.com/5488313/36299367-7a230d3e-12b1-11e8-9891-92025683bf9a.png)

**Comment by kgonzago** [comment]
Actions needed:
1. Dateline check is needed during line creation process. This will drive label placement
2. Add a toggle button to the UI which will allow users to show/hide labels. (new issue will be added for this)

**Comment by ACueva** [comment]
@kgonzago Sorry, mistakenly assigned this one to myself.  Based off your suggestions, this still needs Development work.  Placing back in the Sprint.

**Comment by kgonzago** [comment]
@ACueva no worries.

**Comment by kgonzago** [comment]
We can use this [sample](https://github.com/Esri/developer-support/blob/master/arcobjects-net/international-dateline-draw-line-across/CreateLine.cs) as a guide to check the international dateline when constructing lines.

**Comment by kgonzago** [comment]
![image](https://user-images.githubusercontent.com/6391826/36872421-3440733e-1d73-11e8-9b31-96ae93c1b60d.png)

Labels will be created at the start point of each geodetic line without an angle. Thoughts? @ACueva @dfoll @topowright

**Comment by kgonzago** [comment]
Needs PEs input before implementing change.

**Comment by BobBooth** [comment]
@kgonzago - I think placing a label at the line start makes sense. Not sure what you mean by " without an angle. "

**Comment by adgiles** [comment]
They are not drawn at an angle on the parallel with the line - I guess

**Comment by kgonzago** [comment]
@BobBooth Please see the [image](https://github.com/Esri/distance-direction-addin-dotnet/issues/289#issuecomment-366174160) that was shared by @topowright. The labels were rendered at an angle to mimic the curvature of the line created.

**Comment by kgonzago** [comment]
text labels are now rendered at the start point of a line with no rotation to it. It is also left aligned for better readability.

**Comment by dfoll** [comment]
@lfunkhouser @topowright  not sure what to do with this issue. it was written in a vague manner as to what exactly the problem was.  lines were fixed, circles and ellipses are still not labeling correctly #533 was opened for ellipse and circle labeling.

**Comment by BobBooth** [comment]
Added steps to checklist test.
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/117/files#diff-6eadc8ba6a74ef60a73247e88b9185e0
