### ISSUE TITLE
Distance and Bearing creating bad results (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#292]
Tested with Build 19 Jan 2017 05:11

- Open ArcMap
- Add the topographic basemap
- Open Distance and Direction tool
- Line tab is enabled
- For "From:" parameter, select "Distance and Bearing".
- For "Starting Point" parameter, enter 45N 120W
- ISSUE #298 : as you are typing in coordinate, the tool is creating the "temp" line; . I believe at this point in user interaction, that only the green dot is supposed to be drawn on the map to indicate the Starting Point location?
- For "Distance/Length", enter 1000.
- For "Units", select Kilometers.
- For "Angle" enter 90. Keep units as degrees.
- Enter return in the Angle parameter.
- ISSUE #295 : Angle and Starting and Ending Points are not cleared. (In Pro addin. all inputs are cleared after the line is drawn).
- [x] ISSUE: The line is now labeled with a length longer then user specified. The angle greater then the user specified. Should be 1000 Kilometers and 90 degrees.
![image](https://cloud.githubusercontent.com/assets/4635490/22111988/4367cc10-de16-11e6-831d-03eb015d69a8.png)

With Line tab still active...
- Re-enter 1000 for Distance and 90 for Angle. Enter return in Angle parameter.
- [x] ISSUE: the same line is not drawn. The line now has a longer line and greater angle then previous line.
![image](https://cloud.githubusercontent.com/assets/4635490/22112163/d7cb5138-de16-11e6-98fd-c561b3041410.png)

The error in line length and angle keeps increasing each subsequent time you run the tool, i.e. each time I enter the same parameters (1000 Kilometers and 90 Degrees) the line is created with increasingly incorrect length and angle...
- Re-enter 1000 for Distance and 90 for Angle. Enter return in Angle parameter.
![image](https://cloud.githubusercontent.com/assets/4635490/22112328/5caee428-de17-11e6-93d3-f239e9bdd464.png)

ArcGIS Pro addin is working correctly.

**Comment by pHill5136** [comment]
@elinz fixed please test next build pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/293

**Comment by elinz** [comment]
Verified on build 19 Jan 2017 13:18 Build Number 1155. Closing issue.
