### ISSUE TITLE
Line tool does not "clear" parameter input controls after line is created (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#295]
Tested build 19 Jan 2017 

In "Point" mode:
After creating a line, the input parameter such as starting/ending point distance are not cleared, forcing the user to manually clear these inputs. 

For example,
Entered 45N 120E as Starting Point; entered 10S 100E as Ending Point. Click return so that line graphic is created...
![image](https://cloud.githubusercontent.com/assets/4635490/22128492/b71660d8-de55-11e6-84ac-42fb75e72e0d.png)

The Starting Point and Ending Point inputs are not cleared.

**Comment by elinz** [comment]
@nfeuerstein Not critical. I would say move to version after next.

**Comment by elinz** [comment]
Same issue applies when you use the Distance and Bearing option. the appropriate textboxes are not cleared after the graphic is created.

**Comment by lfunkhouser** [comment]
@dfoll @Dbarnes1 Please add to list of known issues for this release

**Comment by Dbarnes1** [comment]
@lfunkhouser issue has been added.

**Comment by elinz** [comment]
@Dbarnes1 Can you please remove this from the know issue doc? when I was verifying #296 it turns out that this issue was fixed. But none of us were notified that it was being fixed or was fixed. I'll remove the known issue label.

Verified fixed on build 19 Jan 2017 16:49, build number 1158. Closing issue.

@lfunkhouser @dfoll FYI.

**Comment by elinz** [comment]
On second thought I reopen. Once @Dbarnes1 removes this from know issue doc, then we can close this issue.

**Comment by Dbarnes1** [comment]
@elinz I removed this from known issues. closing out.
