### ISSUE TITLE
Line tool does not zoom/pan to created line (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#296]
Tested with build 19 Jan 2017 13:18 #1155
After the line is created, the map is not zoomed/panned to the newly created line. All other tools (Circle, Ellipse, and Rings) in ArcMap addin and all tools including the Line tool in ArcGIS pro adding zooms/pans to newly created graphic

**Comment by pHill5136** [comment]
fixed pull request https://github.com/Esri/distance-direction-addin-dotnet/pull/297

**Comment by elinz** [comment]
@nfeuerstein Just waiting for the fix to be merged.

**Comment by elinz** [comment]
@kgonzago Can you review and merge #297 ? Thanks.

**Comment by nfeuerstein** [comment]
@elinz done

**Comment by elinz** [comment]
@nfeuerstein haha. I was wondering if I should click on the Merge button.

**Comment by elinz** [comment]
@nfeuerstein I will start a new jenkins build.

**Comment by elinz** [comment]
@nfeuerstein Verified fixed on build 19 Jan 2017 16:49, build number 1158. Closing issue.
