### ISSUE TITLE
Green "location" dots are left on the map when creating Lines (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#298]
Tested with build 19 Jan 2017 13:18 Build Number 1155

For this test case I set the "From" parameter to "Distance and Bearing" (issue applies to "Points" option as well).

- As I'm typing in a coordinate the Line tool is interpreting and if it can evaluate to a valid coordinate it places a green dot on the map at that location. For example, I want to enter the coordinate 45N 120W as the Starting Point. As I'm typing the coordinate and type in "45N 1", the tool evaluates this as a value coordinate and draws a greet dot...
![image](https://cloud.githubusercontent.com/assets/4635490/22129538/81e1f89a-de5b-11e6-95d2-7d25d1029b6c.png)

As I continue to type in 120W, the tool continues to draw dots because "45N 12" is a valid coordinate; "45N 120" is a valid coordinate; "45N 120W" is a valid coordinate (I am now done with entering the coordinate. However, now the map is starting to fill up with more green dots....
![image](https://cloud.githubusercontent.com/assets/4635490/22129653/30256b8a-de5c-11e6-80be-d0754c6bc9a3.png)

Now I enter in a a distance and angle, 3000 kilometers and 45 degrees and hit return within the angle input box so the graphic is created...However, the tool does not delete all the green dots from the map...
![image](https://cloud.githubusercontent.com/assets/4635490/22129800/168fdb6e-de5d-11e6-9944-0c3ccc64b31a.png)

The user has two choices if they want to delete the green dots (workaround until this is fixed):
1. After they create the final graphic they can click "Clear Graphics" on the Line tool, but that will also delete their final graphics as well as the green dots.
2. Open the out of the box Graphics toolbar, select all the green dots (they're just graphics) and click the delete key.
Both are not good options.

What I believe should be happening is:
- As the user types in a coordinate it places a green dot on the map if the coordinate is valid. As the user continues to type in the coordinate and it's evaluated as a valid coordinate, the previous drawn green dot should be deleted and a new green dot is added at the newly evaluated value coordinate, etc. Basically, the tool shouldn't "leave a trail" as it's evaluating.
- When the user clicks enter to create the final line graphic, the final line graphic is drawn and the green dot drawn at the starting point location is deleted.

NOTE: the ArcGIS Pro addin Line tool does not "leave a trail" of green dots and after the user creates the final line graphic, the green dot located at the Starting Point location is deleted.

**Comment by lfunkhouser** [comment]
@Dbarnes1 @dfoll Please add to list of known issues in ArcMap for this release

**Comment by Dbarnes1** [comment]
@lfunkhouser issue has been added to doc.

**Comment by kgonzago** [comment]
I decided to tackle this issue since it was a simple fix (one liner  PR #300). Green/Start points are now cleaned up.

@Dbarnes1 Sorry this will affect doc.

**Comment by elinz** [comment]
@kgonzago Thank you for fixing.

**Comment by csmoore** [comment]
Got autoclosed with PR - reopening for verify

**Comment by Dbarnes1** [comment]
I'll remove from known issues list once @elinz verifies.

**Comment by elinz** [comment]
@kgonzago @csmoore @Dbarnes1 Starting a build right now.

**Comment by elinz** [comment]
@Dbarnes1 @kgonzago @csmoore Verifed fixed in build 20 Jan 2017 07:39, build number 1163.

@Dbarnes1 Ready for you to update known issues doc and remove known issue label.

Closing issue.

**Comment by Dbarnes1** [comment]
removed from known issues.
