### ISSUE TITLE
Distance and Direction - Save As not exporting relevant fields (ArcGIS Pro)

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#299]
_From @ACueva on January 17, 2017 23:47_

## Expected Behavior
I should see exactly what the addin displays:

![1-17-2017 3-46-46 pm](https://cloud.githubusercontent.com/assets/3093940/22044940/34239ebe-dccc-11e6-95a8-9a2328fc01db.png)

Starting Point
Ending Point
Distance/ Lenght
Angle

## Current Behavior
Save As- Export to Feature Class
![1-17-2017 3-38-26 pm](https://cloud.githubusercontent.com/assets/3093940/22044754/155e7702-dccb-11e6-8815-026e70bb2232.png)

Save As - Shapefile
![1-17-2017 3-41-40 pm](https://cloud.githubusercontent.com/assets/3093940/22044829/779d713e-dccb-11e6-95cb-12e9f08fa1bb.png)

## Steps to Reproduce (for bugs)
1. Create a line using map tool.
2. Click Save As
3. Select either Feature Class or Shapefile
4. Explore  (identify) item

## Context
I believe we have all this information, why not export it so the customer can use it?

## Your Environment
ArcGIS Pro 1.4

_Copied from original issue: Esri/military-tools-for-arcgis#91_

**Comment by lfunkhouser** [comment]
@ACueva Is this happening in ArcMap also?

**Comment by ACueva** [comment]
@lfunkhouser Just tested in ArcMap.  Yes, same behavior.  I'll log an issue.

**Comment by ACueva** [comment]
Update: Tested Feature Class does work.  Shapefile does not export attributes.  KMZ is doing it's own thing.
![2017-05-10_10-29-47](https://cloud.githubusercontent.com/assets/3093940/25912296/9c47bd34-356b-11e7-91a4-3c2eed15ceb5.png)

**Comment by dfoll** [comment]
with build 1474 these fields are being added to feature class and shapefile. Still at 1474, some of the kmz are seemingly randomly getting corrupted, however the ones that did work did not have the fields added

**Comment by pHill5136** [comment]
added attributes to shapefile please verify. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/387

**Comment by dfoll** [comment]
attributes are carrying over and populating ok for feature class and shapefile for lines rings circles and ellipses. still could not get any of them to produce a valid kmz (). Case has been created with Tech Support. Esri Case #1933479. See issue for more details on the kmz issue until tech support opens a bug will update once tech support opens an issue.

**Comment by pHill5136** [comment]
please verify kmz. Now reprojecting shapefile from which kmz is derived to 4326. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/392

**Comment by NatalieCampos** [comment]
@pHill5136 The reproject seems to have worked.  There are still some issues.

1. KMZs saved from rings do not have attributes.  (Circles, Ellipses, and Lines do have attributes)
2.  My lines are named lines.kmz.  When I bring in the lines.kmz file to Pro, Pro names them LInes_proj.  Can you remove the _proj?
![image](https://cloud.githubusercontent.com/assets/5116835/26380321/c25f57d6-3fd2-11e7-977d-210486d6b381.png)

3. Saving to KMZ produces 2 extra shape files. Is it possible to delete these files after the kmz is created?
![image](https://cloud.githubusercontent.com/assets/5116835/26380394/3622d0c6-3fd3-11e7-829f-f99ee1bf0122.png)

**Comment by pHill5136** [comment]
please verify. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/394

**Comment by NatalieCampos** [comment]
@pHill5136 the extra shp files are still being left behind.  Can these be removed?

**Comment by NatalieCampos** [comment]
@pHill5136 there is still an issue with name of the file as it is brought into pro...
![image](https://cloud.githubusercontent.com/assets/5116835/26474166/495b3470-4164-11e7-8e4c-29e2c3747127.png)

**Comment by NatalieCampos** [comment]
additionally I am totally unable to save rings out to kmz

![image](https://cloud.githubusercontent.com/assets/5116835/26474581/b4251648-4166-11e7-9b32-d273753023ad.png)

**Comment by dfoll** [comment]
This issue needs to be broken into two different issues. This will be done by @NatalieCampos .

**Comment by topowright** [comment]
I have verified that this works using build 05-31-2017_1540
