### ISSUE TITLE
After switching between tabs, two clicks are required to enable Map Point tool (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#301]
**Procedure:**

1. On any tab click on Map Point tool
2. Switch to another tab
3. Switch back to initial tab (Map Point tool should be unshaded i.e. not shaded in blue at this point, as it should have been deactivated on switching to another tab)
4. Click on Map Point tool

**Result:**

Map Point tool icon changes to unshaded (not shaded blue to indicate activation), cursor does not change to cross, and tool is not enabled for use on map

**Result expected:**

Map Point tool changes from unshaded to shaded blue to indicate activation, cursor changes to cross, tool is enabled for use on map

**Additional:**

Click on Map Point tool again

**Result:**

Map Point tool icon changes to shaded blue to indicate activation, cursor changes to cross, tool is enabled for use on map

**Comment by elinz** [comment]
@rjones0 I would not expect enabling the Map Point tool on one tab means that the Map Point tool should be enabled on all the other tabs.

**Comment by rjones0** [comment]
Sorry perhaps I wasn't clear - the issue is that after changing tabs, two clicks are required to enable the Map Point tool, whereas surely one click should enable the tool.

**Comment by rjones0** [comment]
@elinz ok slightly different than I first thought - I have updated the description.

**Comment by elinz** [comment]
@rjones0 Oh ok. Thank for the update. I'll install latest build and check the behavior.

**Comment by elinz** [comment]
@rjones0 I was able to replicate the issue in the latest build.

**Comment by rjones0** [comment]
Despite my efforts I have not been able to resolve this issue. My approach is:

1. When Map Point tool is enabled, store the identity of the tab
2. When tab is changed, check whether the Map Point tool should be enabled for the tab (using identity of tab on which Map Point tool is enabled)

This should mean that every time the user clicks on the Map Point tool it is enabled for the currently displayed tab, and unless the user enables the Map Point tool for another tab, when they come back to the tab on which they enabled the Map Point tool it should be enabled.

I used the code that is triggered by clicking the Map Point tool and called this on changing tab, if the tab displayed is the tab for which the Map Point tool was last enabled. This doesn't work and I cannot figure out why. I will retain my code locally and commit to a remote branch for discussion when possible.

**Comment by topowright** [comment]
@dfoll , @ACueva , @NatalieCampos I am not sure what we want to do with this issue. 

Based on the last comment that was made by rob jones he could not figure out how to change the behavior. The expected outcome was to have the map point tool deactivate each time the user left the tab; however, he could not figure out how to implement this fix. 

The current behavior makes the user click on the tool twice when they want to use the map point tool after leaving the tab. @csmoore is there something that might have been missed by the last developer that we can change? If so what would the level of effort be?

**Comment by pHill5136** [comment]
I too have looked into this and cannot find a solution. I have codded it so that the map point tool is not deactivated when tabs are changed. This works for changing between tabs unless the tool is deactivated in one tab. then moving to the next tab the tool appears to be active but does not activate until 2 clicks.

**Comment by NatalieCampos** [comment]
Verified and closed.
