### ISSUE TITLE
ArcMap Crash - Too many rings.

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#302]
![image](https://cloud.githubusercontent.com/assets/5016557/22162100/124f48c8-df02-11e6-9f13-5b116cdd80ea.png)
Using ArcMap 10.5 and Military Tools for ArcGIS 1.0.0, I created a 20-ring range ring using a distance of 100,000 meters. It fails consistently.

**Comment by ACueva** [comment]
I reproduced this issue as well.

**Comment by joebayles** [comment]
It'll work at 15 100K-Meter range rings, but 17 is too many. Regardless of the fact that this may or may not be a useful workflow, we've established a limitation for the tool and should probably document it.

**Comment by joebayles** [comment]
@ACueva - Maybe this is a use case?
![image](https://cloud.githubusercontent.com/assets/5016557/22162648/617c2f04-df04-11e6-9b0b-3d31f2f7a85d.png)

**Comment by pHill5136** [comment]
@nfeuerstein Code all completes this appears to be a bug in arcmap.

**Comment by nfeuerstein** [comment]
@Dbarnes1 @dfoll @lfunkhouser we can't fix bugs in ArcMap, but we should document this limitation.

**Comment by pHill5136** [comment]
@nfeuerstein @lfunkhouser @kgonzago Kevin and I have been looking at this. This appears to be a bug in arcmap when adding lots of graphics to a map. I tested that it crashes if I copy and paste too many graphics at once.

**Comment by NatalieCampos** [comment]
unable to verify this issue.  I added 50+ range rings to my ArcMap 10.5 session without a crash.

![image](https://cloud.githubusercontent.com/assets/5116835/25630709/e8d90580-2f22-11e7-99b2-3673905708f5.png)


@lfunkhouser shall I close the issue? Or do we add it to "known issues" documentation as a catch all just in case?

**Comment by NatalieCampos** [comment]
I tested this on my laptop (same machine as earlier) @10.3 and had no crashes. I also tested this on a different (desktop) machine and was able to create 50+ rings with no crashes.  @topowright @ACueva.....I dont know where to go from here except to add the blurb about graphics being limited by the users graphics cards.   Any ideas?

**Comment by NatalieCampos** [comment]
Adding @lfunkhouser

**Comment by joebayles** [comment]
Well, I just re-ran it, same parameters (although not a fresh map). Didn't crash, but I got this:
![image](https://cloud.githubusercontent.com/assets/5016557/25643801/8a152284-2f56-11e7-882e-95e8869cd59b.png)

**Comment by ACueva** [comment]
Thanks @joebayles.  Make sure you go downstairs and let help desk know your blender is having issues.  :)

**Comment by csmoore** [comment]
I can reproduce this issue(crash), though similar to #364, I'm having some issues knowing the correct input sequence to get the range rings to draw on the map.

But these circles do appear to be too densified (too many points) - it seems like perhaps a [radians/degrees issue](https://github.com/Esri/distance-direction-addin-dotnet/blob/dev/source/DistanceAndDirection/ArcMapAddinDistanceAndDirection/ArcMapAddinDistanceAndDirection/ViewModels/RangeViewModel.cs#L268) though I don't see where [the units of that parameter are specifically called out](https://desktop.arcgis.com/en/arcobjects/latest/net/webframe.htm#IConstructGeodetic_ConstructGeodesicCircle.htm).  But assuming this parameter is degrees, I can get this to work modifying it to "densify to 5 degrees":

![image](https://cloud.githubusercontent.com/assets/3090809/25673229/9c451f82-3004-11e7-9dad-fc1fe8663802.png)

**Comment by topowright** [comment]
The performance that I see on build 05-03-2017_1426 is what I would expect when we create graphics. Great job @csmoore. I was able to create 180 circles quickly. Is there a reason why we choose 180 rings as the most a user can create?

**Comment by ACueva** [comment]
As @mfunk would say "Works on my machine".

**Comment by topowright** [comment]
This has been verified.
