### ISSUE TITLE
Circle/Ellipse tool: Graphical glitch in preview after changing Center Point (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#303]
**Procedure:**

1. Using Circle tab Enable Map Point tool
2. Move mouse over map but do not click
3. Click in Radius / Diameter fieldsteps 
4. Add a value large enough to make preview visible
5. Click in Center Point field and change value

**Result:**

The preview circle is not completed properly

**Result expected:**

Preview circle should complete properly

**Additional**

Procedure for Ellipse is similar but replace steps 3 and 4 above with adding values to Axis Major and Minor fields

**Comment by pHill5136** [comment]
please verify. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/381

**Comment by NatalieCampos** [comment]
Verified on build 1475.
