### ISSUE TITLE
Allow user to create unequally spaced rings through keyboard

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#311]
#### Background
We allow the user to interactively create unequally spaces rings interactively, we should allow the user to create unequally spaced rings through the keyboard/from known intervals.

#### Expected Results
For ArcGIS Pro  and ArcMap

User should have four options for creating rings using the add-in.
- "Interactive" (**already implemented**)
- "Fixed" (**already implemented**, a user supplies a point, number of rings, and a distance between rings)
- "From Origin" (user supplies a point either manually or with the map point tool and then populates the list. Each row in the list is treated as a new ring that is to be created X distance from the center point. In this case, The order of the rings does not matter, as each rings is drawn independent of the ring before it in the list. ) _Widget uses the verbiage "Origin" suggest using the verbiage "From Origin" instead and eventually changing the widget_
- "Cumulative" (user supplies a point either manually or with the map point tool and then populates the list. Each row in the list is drawn based on the row before it and distances build cumulatively. First ring would be drawn based on the center point.)

"Unequally spaced" rings would be covered by the last two scenarios, in which a list would drive the creation of the rings.

###### From Origin
List is populated, each ring/row is drawn on it's own, independent of the previous entry. In the mock up below, rings would be drawn at intervals of 
- 100m (from origin)
- 300m (from origin)
- 200m (from origin)

![image](https://user-images.githubusercontent.com/5322669/45698769-c73b9900-bb36-11e8-90a3-b9c07eca8082.png)

###### Cumulative
List is populated, each ring/row is drawn based on the ring/row before it and distances build cumulatively. First ring/row distance is based on the starting point. In the mock up below, rings would be drawn at intervals of 
- 100m (cumulative from the starting point)
- 400m (first entry was 100m, second entry was 300m, so cumulatively the second entry would create a ring at 400m)
- 600m (first entry was 100m, second entry was 300m, third entry was 200m, so cumulatively the third entry would create a ring at 600m)

![image](https://user-images.githubusercontent.com/5322669/45699194-90b24e00-bb37-11e8-937d-6644b7e0db58.png)

#### Documentation (to finish this issue)
- [ ] Workflow documentation (suggest to the group that we should re-work documentation to have a single topic for creating rings, single topic would have sections  that address each way of creating rings)
- _when this issue is closed it should be listed in "What's new" as it is not a bug, but an enhancement_
- [ ] "What's new" Defense page
- [ ] "What's new" section on the release topic (Distance and Direction release)
- [ ] "What's new" section on the release topic (Military Tools for ArcGIS release)

**Comment by dfoll** [comment]
updated issue body, based on this [comment](https://github.com/Esri/distance-direction-addin-dotnet/issues/312#issuecomment-422430641) to clarify what we want in this enhancement, so this can be worked on by someone not intimately familiar with the add-in or widget

**Comment by dfoll** [comment]
@topowright @kgonzago @lfunkhouser build 12  in ....\Commercial\Solutions\DefenseSolutions\DistanceAndDirection\Testing can be used to test this functionality

**Comment by dfoll** [comment]
This new functionality should be added to the Military Tools 3.3 cms release topic as well

**Comment by kgonzago** [comment]
Drop-down list with options: 

![image](https://user-images.githubusercontent.com/6391826/47020785-1e2d9180-d128-11e8-934e-520e6d7d32a2.png)

`Origin` Testing:
![image](https://user-images.githubusercontent.com/6391826/47021949-867d7280-d12a-11e8-8e37-47357148bf56.png)

**Comment by kgonzago** [comment]
![image](https://user-images.githubusercontent.com/6391826/47028600-aff0cb00-d137-11e8-8374-2faa9674c429.png)
Screenshot for unequal distances for rings.

**Comment by BobBooth** [comment]
@kgonzago and I just added the workflow step and republished to solutionsdev and the PDF.
Removing Doc CMS and QC Doc tags.

**Comment by BobBooth** [comment]
I believe the Doc Website tag can be removed after https://github.com/ArcGIS/arcgis-solutions-website/pull/7237 is merged.

**Comment by BobBooth** [comment]
This is impeded - needs review and merge by @dfoll or @topowright who are not available.

**Comment by dfoll** [comment]
Reviewed and merged
