### ISSUE TITLE
Distance Calculation should label based on units specified in Distance Calculation parameters (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#325]
Tested 1.0 release of Military Tools for ArcGIS

Perform distance calculation where center point is on New York City, time is 24 hours, rate is 60 miles per hour, which equals 1440 miles.

The tool labels the output graphic based on the Radius/Diameter units instead of the units set in the Rate parameter. For this example, I specified the rate as "Miles / Hour" so the labeled units should be Miles.

Also when you perform distance calculations the output should be labeled as "Radius" no matter if the "From" parameter is set to Radius or Diameter.
![image](https://cloud.githubusercontent.com/assets/4635490/23074906/66c03ab8-f4ef-11e6-9195-900e88b76333.png)

@kgonzago FYI.

**Comment by rjones0** [comment]
@elinz @kgonzago On the second issue - the behaviour described (i.e. always label circle with Radius regardless of whether Radius or Diameter is specified in the From combobox) was previously raised as a bug and fixed as such: https://github.com/Esri/distance-direction-addin-dotnet/issues/190

**Comment by rjones0** [comment]
When Distance Calculator is displayed the distance unit from the Rate combobox is used for the label. PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/327

**Comment by elinz** [comment]
@rjones0 @kgonzago This fix is only part correct. The only thing that is correct now is that the circle created by performing distance calculation is labeled with the unit of length specified in the Rate parameter. 

When users are performing a Distance Calculation, the code should not take into account the "From" parameter value, i.e. no matter what the "From" parameter is set to, the code should calculate the circle based on Radius. 

For example, if I run a Distance Calculation where the time is 10 hours and the rate is 60 miles/hour...
![image](https://cloud.githubusercontent.com/assets/4635490/23279621/d5268de2-f9ca-11e6-96de-77dcfa6cc934.png)

The code should create a circle with a radius of 600 miles as shown below:
![image](https://cloud.githubusercontent.com/assets/4635490/23279634/e9af2fe4-f9ca-11e6-98af-383b82e48653.png)

No matter if the "From" parameter is set to Radius or Diameter, the code should create the circle based on radius as shown in the screenshot above. 

This was actually working as I expected previously. The only issues were that it should be always be labeled "Radius" (i.e. ignore the From parameter) and that the label for distance should be based on distance part of the Rate parameter.

I'm not sure why we are labeling with so many decimal places; we used to label out to 2 decimal places.

Also the person who opened the issue should be the one to verify the fix. The exception to this is when the person who opened the issue is the one that fixed it, then someone else should verify the fix.

**Comment by rjones0** [comment]
@elinz I suspect the extra precision is a side effect of another fix of mine. I think the other issue - always use Radius for labelling if the Distance Calculator is displayed - is a pretty quick fix. I will look at both.

**Comment by rjones0** [comment]
PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/338
