### ISSUE TITLE
Pro 1.4.1 Lines not accepting decimal in Radius/Diameter box

### ISSUE THREAD

**Issue by mfunk** [Esri/distance-direction-addin-dotnet#328]
Found some problems entering Radius/Diameter values in the Circle tab on DD in Pro 1.4.1. 

1) Click **Map Point** tool by *Center Point*
2) Click a location on map (I used point off coast of Colombia in South America
3) Click in *Radius/Diameter* and type 1000.00
Note that the decimal does not show up and by the hundredths "0" actually shows an error in the box:

![image](https://cloud.githubusercontent.com/assets/3093182/23187045/3c3226d8-f83e-11e6-8581-0625ae59bb67.png)

**Comment by pHill5136** [comment]
verify pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/370

**Comment by dfoll** [comment]
looks to me like it works on 1.4 
![image](https://cloud.githubusercontent.com/assets/5322669/25920015/5125d63c-3585-11e7-8b19-99d090e122b1.png)
[press enter]
![image](https://cloud.githubusercontent.com/assets/5322669/25920026/5f502a78-3585-11e7-811a-89537ed70624.png)

**Comment by dfoll** [comment]
seems ok for 1.4.1 as well, tested using build 1453
