### ISSUE TITLE
Select [an] existing feature(s) as inputs

### ISSUE THREAD

**Issue by joebayles** [Esri/distance-direction-addin-dotnet#330]
As a user, I want to the ability to choose existing features as inputs for Line Start and End Points, and Circle, Ellipse, and Range Ring Center Points.

**Comment by lfunkhouser** [comment]
Not enough information or an understood use case. It is not understood which start points would go with which end point and there would be additional information needed for each center point for circle, rings, ellipses. Will not address at this time.
