### ISSUE TITLE
Deleting Center/Starting/Ending Point does not delete properly (ArcMap)

### ISSUE THREAD

**Issue by rjones0** [Esri/distance-direction-addin-dotnet#331]
Procedure:

Enter 1 1 in Circle tab - Center Point
Select text in Center Point text box
Press Delete

Result:

Text is replaced by 1.0 1.0

Result expected:

Box should be cleared

**Comment by rjones0** [comment]
PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/332

**Comment by elinz** [comment]
@rjones0 @kgonzago I tested ArcMap adding build 23 Feb 2017 13:08 which I believe should have this change however I'm able to reproduce the issue. For me after I entered "1 1" into the Center Point textbox and then selected the text and pressed Delete the center point textbox was populated with "111325.1 111319.5"

**Comment by elinz** [comment]
@rjones0 @kgonzago Same issue for Lines, Ellipse, and Rings. Also same issue in ArcGIS Pro; I'll open a separate issue for Pro.

What's happening is that when you click Delete, the addin is re-displaying the coordinate that the user entered converted into the selected "Display Coordinate" property set on the "Edit Properties" dialog.

**Comment by elinz** [comment]
Pro issue is #334

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
Functionality appears to be working properly now.  I am able to delete the Center Point input without any issues.
