### ISSUE TITLE
Circle tool: can no longer type in diameter distance if I've interactively added the center point (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#333]
Tested on build 23 Feb 2017 09:05

- Set "From" parameter to "Diameter"
- Click on the Map Point tool to interactively set the center point based on a click on the map.
- Try to set the Radius/Diameter parameter by typing in the textbox; the textbox does not allow you to type in a value.

**Comment by pHill5136** [comment]
@elinz please verify. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/357

**Comment by elinz** [comment]
@pHill5136 Issue still exists. When I select "Diameter" in the "From" parameter I can't specify the Radius/Diameter value using the keyboard.

**Comment by pHill5136** [comment]
@elinz please verify

**Comment by pHill5136** [comment]
@elinz  pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/359

**Comment by Dbarnes1** [comment]
verified, closing.
