### ISSUE TITLE
Deleting Center/Starting/Ending Point does not delete properly (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#334]
Procedure:

Enter a coordinate, for example 1 1 in the Center Point, Starting Point, Ending Point parameter on the Line, Circle, Ellipse, and Rings tools.
Select the text in the Center Point, Starting Point, Ending Point textbox.
Press Delete key.

Result:
Instead of the textbox being cleared, the textbox is populated with the entered coordinate converted to the "Display Coordinate" set on the "Edit Properties" dialog.

Same thing in ArcMap. See #331

**Comment by lfunkhouser** [comment]
Assigning to @elinz who originally submitted the issue and the MT PEs to verify.

**Comment by topowright** [comment]
This is still an issue. 

you cannot delete a coordinate by highlighting the text.

**Comment by topowright** [comment]
@pHill5136 just FYI

**Comment by lfunkhouser** [comment]
Assigning to Devs - and adding ```backlog``` label

**Comment by NatalieCampos** [comment]
This has been fixed and verifed in the line, circle, ellipse, and rings tab.
