### ISSUE TITLE
Labels are hard to read over imagery- add a text halo

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#342]
Testing Distance and Direction against an imagery basemap in 10.5.1 is making me realize how hard it is to read the labels over imagery. We should add a halo to our labels so they are easier to read. 

This is what I'm talking about:
![rangeringslabelsimagery](https://cloud.githubusercontent.com/assets/13024357/23915064/3038948a-08a5-11e7-9e76-40faa2ae3cf3.PNG)

**Comment by topowright** [comment]
This will not be fixed. The way that the user can change the color of the labels would be to export to a feature class and then choose the color needed to allow the labels to then be seen better.
