### ISSUE TITLE
draw label along line for DD Add-In

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#343]
The distance and direction widget renders labels along the line (at the centerpoint of the line drawn). Lets do this for the add-in as well. I think that this makes more sense than what we are currently doing, which is placing the labels above the origin point of the line. 

If we want to maintain labeling at the start of the line, I have this enhancement idea as well, although it would be much easier to just draw the labels along the line:

An enhancement that would greatly improve the legibility of distance and direction labels for lines would be to try and have the labels dynamically render in the position that is the opposite of the direction of the line. That way, cases of overlapping lines and labels would go down significantly. Currently, the position of the label is at the center top of the origin line. This is what is currently happening, and in any case of a line that moves slightly north from the origin point, you'll see conflict with the line and labels:
![distancelines](https://cloud.githubusercontent.com/assets/13024357/23916527/c0fe641e-08a9-11e7-8d90-55f7a34b5926.PNG)

**Comment by pHill5136** [comment]
@Dbarnes1 fixed pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/356

**Comment by Dbarnes1** [comment]
@pHill5136 verified fixed, closing.
