### ISSUE TITLE
Create circle from distance calculator: inconsistencies in unit labeling in output. 

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#345]
When creating circles using the distance calculator add-in, the circle units labeled will default to the rate unit (miles per hour, etc.). This seems good, but the Radius/Diameter drop down is still active. This is confusing, an easy solution would be to disable the Radius/Diameter unit drop down. In addition, it doesn't make sense to have the distance calculator operate from a specific diameter, as the distance calculator is all about finding how far something can get from a center point, which indicates a radius.

Regardless of what we do here, we need to make sure it is consistent with the widget, which currently converts the rate unit to the Radius/Diameter unit on the fly and displays that output.

The associated widget issue is located here: 

https://github.com/Esri/solutions-webappbuilder-widgets/issues/831

In this case, do we display output meters or miles?
![metersormiles](https://cloud.githubusercontent.com/assets/13024357/23920986/1b59f5f8-08ba-11e7-9b70-873cf6756a99.PNG)

@elinz thanks for looking into this with me.

**Comment by lfunkhouser** [comment]
Radius/Diameter input is grayed out when the Distance Calculator is active. A user can change the units but not interact with the measurement. Closing. This is functioning as designed.
