### ISSUE TITLE
Create Circle from Diameter using Map Point Tool, circle preview and Map Point cursor don't match.

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#346]
When using the map point tool to create a circle, and when creating a circle from diameter, the map point cursor is twice as large as the circle preview. Once the user clicks enter and the circle is created, the circle reflects the location of the map point cursor, not the circle preview. I think that the circle preview needs to be expanded to reflect the diameter, although this inconsistency could possibly be related to an issue in the diameter output being an incorrect length. 

Tested against 10.5.1 but the issue probably exists on 10.3.1 forward.

**Comment by pHill5136** [comment]
pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/375

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
@pHill5136 Fix hasn't been applied yet, looks like you have a conflict to resolve before being able to merge.

**Comment by pHill5136** [comment]
redid this one

**Comment by ACueva** [comment]
@pHill5136 retesting.

**Comment by ACueva** [comment]
Verified this is working the same as the Radius pull down.  The circle now follows the cursor on the map.
