### ISSUE TITLE
Create circle from Diameter- output label is labeling the radius distance.

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#347]
When creating a circle from diameter in the add-in, the output length labeled is half of what it should be, so the output Diameter label is actually labeling the radius. I figured this out using the measure tool in ArcMap:
![diameterbroken](https://cloud.githubusercontent.com/assets/13024357/23921695/d33b9850-08bc-11e7-8c07-60bde3be9217.PNG)

**Comment by pHill5136** [comment]
fixed please verify. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/354

**Comment by pHill5136** [comment]
@Dbarnes1 fixed please verify. pr: #354

**Comment by Dbarnes1** [comment]
@pHill5136 verified, closing.
