### ISSUE TITLE
Ellipse Tool- create Full Ellipse with map point tool outputs Semi labels

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#348]
When creating an ellipse and setting ellipse type to full, I'd expect that the ellipse would be outputting the full major and minor axis as labels. However, it is still outputting semi major and minor axis labels, which are half of the length of the full axes.

**Comment by Dbarnes1** [comment]
for reference: 
![image](https://cloud.githubusercontent.com/assets/13024357/24047662/a3269f06-0ae3-11e7-9651-ed0966634600.png)

**Comment by pHill5136** [comment]
@Dbarnes1 fixed please verify. pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/355

**Comment by Dbarnes1** [comment]
verified, closing.
