### ISSUE TITLE
Circle Tool: can't specify a decimal point in Radius/Diameter parameter (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/distance-direction-addin-dotnet#358]
I can specify a decimal point in the ArcMap addin.

**Comment by pHill5136** [comment]
![decimalinput](https://cloud.githubusercontent.com/assets/4691261/25863761/e4ac6a18-34a1-11e7-8a85-43e9e2646d5c.png)

**Comment by pHill5136** [comment]
@elinz sending this one back to verify.

**Comment by dfoll** [comment]
this sounds the same as #328  which i verified was fixed this morning. also looked at it again when i came across this issue and from the small amount of detail in the original issue write up, this looks to be fixed
