### ISSUE TITLE
Documentation - improve instructions for adding the stand-alone add-in to ArcMap

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/distance-direction-addin-dotnet#362]
Currently, there is a gap in instructions between adding the add-in to ArcMap and instructions explaining functionality. We need to add these instructions to the documentation for distance and direction, as the add-in doesn't automatically get added to the toolbar.

These are the instructions for Coordinate Conversion. They are identical for what we need for Distance and Direction: 

_Click Customize Mode under Customize menu
Customize window appears._

_Select the Commands tab
Select Add-In Controls from Categories
Drag and drop Coordinate Conversion tool from Commands onto an existing toolbar
Close the Customize window_

**Comment by Dbarnes1** [comment]
related to https://github.com/Esri/visibility-addin-dotnet/issues/180 @dfoll fyi

**Comment by BobBooth** [comment]
Verified that this has been published to Solutions:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/0a8a5293-8d4d-4451-ab29-c94b71c1659f)
Ready to close.
@dfoll  @ACueva

**Comment by topowright** [comment]
This is not done because we need to create this in CMS.

**Comment by dfoll** [comment]
@ACueva @topowright @BobBooth this is ready to verify on DEV.
