### ISSUE TITLE
Error when saving different line types 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#368]
I get the following error message after  saving/exporting graphics to features classes multiple .  To reproduce 
1. save first graphics as any line type:
2.  clear graphics
3. save graphics as a DIFFERENT line type:

![image](https://cloud.githubusercontent.com/assets/5116835/25820976/17e6a67e-33e8-11e7-866b-7d9ed7c2212a.png)

**Comment by NatalieCampos** [comment]
@lfunkhouser @nfeuerstein

**Comment by pHill5136** [comment]
Unable to reproduce this behavior. please verify

**Comment by lfunkhouser** [comment]
@NatalieCampos I cannot follow your steps to reproduce. What do you mean by"feature classes multiple"? Once I complete step 2 listed above, Clear Graphics, there are no graphics in the map to save and the ```Save As``` button is grayed out. I cannot reproduce the issue as logged. I followed these steps with no issue:

1. Chose a line type, such as Geodetic.
2. Click the Map Point Tool, click on the map to start the line
3. Drag to create a line and click on the map at the ending point
4. Click Save As
5. Select Feature Class, click OK
6. Save Lines
7. Select Clear Graphics
8. Click drop down to change line type to Great Elliptic
9. Click the Map Point Tool, click on the map to start the line
10. Drag to create a line and click on the map at the ending point
11. Click Save As
12. Select Feature Class, click OK
13. Save Lines

@NatalieCampos please check again and if it is still an issue for you, add steps to reproduce if different from what is listed above.

**Comment by NatalieCampos** [comment]
@lfunkhouser @pHill5136 I will try to reproduce this in the next day.  I will say that this one was really hard to narrow down. I will get with  @pHill5136 and see if we can reproduce it together

**Comment by NatalieCampos** [comment]
Ok I am able to create the following crash using these methods

1.  Draw Lines 
2. Save as KMZ
3. Clear Graphics
4. Change line type
5. Draw lines
6. Save as Feature Class
I think it has to do with either the saving of different formats or the line type.  

![image](https://cloud.githubusercontent.com/assets/5116835/26078694/2f8ea92e-3975-11e7-962c-5d343f742ef1.png)

**Comment by lfunkhouser** [comment]
@NatalieCampos Following your steps to reproduce, I was able to reproduce the error. Assigning back to @pHill5136

**Comment by ACueva** [comment]
I can get this issue to occur pretty much on demand.  Working with @pHill5136 to see how this can be resolved.

**Comment by ACueva** [comment]
Just tested this issue again.  Wasn't able to get it to crash.
