### ISSUE TITLE
missing features when exporting to kml

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#369]
some graphics are missing after saving as KML.  Steps to reproduce:
1.  create multiple line graphics
2. save as kml
3.  The KML is automatically added to Pro.  
4. Noticed that not all created graphics were saved.  See pic below.

![image](https://cloud.githubusercontent.com/assets/5116835/25821584/94160990-33ea-11e7-98e3-6e9ff2aacbb1.png)

**Comment by NatalieCampos** [comment]
@nfeuerstein @lfunkhouser

**Comment by pHill5136** [comment]
@nfeuerstein @NatalieCampos I have looked into this. I personally have seen the kmz get corrupted once in dozens of tries. This has been reported by several people. I believe that the kmz is occasionally getting corrupted when it is created inside an esri gptool. The shapefile that is created and used to convert to kmz in the gp tool appears to be valid even in cases where the kmz is corrupted. I think this issue goes to core.

**Comment by nfeuerstein** [comment]
Try passing output shapefile to GP Tool to see if this is an issue with how we call the GP tool or if its an issue with the GP tool.

**Comment by topowright** [comment]
I am not able to reproduce this issue: 
![image](https://user-images.githubusercontent.com/5488313/36298359-949466b8-12ac-11e8-899f-70c70731ce02.png)
These are the samples of my work. I attempted to export to shp and KMZ

**Comment by BobBooth** [comment]
I did not see this issue while testing https://github.com/Esri/distance-direction-addin-dotnet/issues/360#issuecomment-366099704

**Comment by lfunkhouser** [comment]
@topowright @BobBooth Was this just an issue with ArcGIS Pro? This was logged at verison 1.4, but non-reproducible on v2.1? Please be clear on which versions and applications were tested.

**Comment by topowright** [comment]
I tested this on version 2.1 and ArcMap 10.6

**Comment by BobBooth** [comment]
I tested on Pro 2.1, non-reproducible there.
@topowright @lfunkhouser
