### ISSUE TITLE
Distance and Direction - Save As not exporting relevant fields (ArcMap)

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#371]
Same issue in Pro: https://github.com/Esri/distance-direction-addin-dotnet/issues/299

Save As is not exporting all the appropriate attributes.

![1-17-2017 3-46-46 pm](https://cloud.githubusercontent.com/assets/3093940/22044940/34239ebe-dccc-11e6-95a8-9a2328fc01db.png)

## Current Behavior
Save As- Export to Feature Class - Only has length.
![1-17-2017 3-38-26 pm](https://cloud.githubusercontent.com/assets/3093940/22044754/155e7702-dccb-11e6-8815-026e70bb2232.png)

Save As - Shapefile - Does not have any fields populated.
![2017-05-10_10-14-41](https://cloud.githubusercontent.com/assets/3093940/25911659/8b5b93bc-3569-11e7-9131-b6e2aa04e5ba.png)

KMZ - Appears to be displaying properly when opened in ArcGIS Earth.  I wasn't able to see any attribute information though.  Not sure if it's an ArcGIS Earth thing or as designed.

**Comment by dfoll** [comment]
with build 1474 these fields are being added to feature class and shapefile. Still at 1474, some of the kmz are seemingly randomly getting corrupted, however the ones that did work did not have the fields added

**Comment by ACueva** [comment]
Removing the Dev label, verified items are exporting properly in ArcMap.  This may have been resolved when #299 was addressed.
![2018-06-01_15-25-48](https://user-images.githubusercontent.com/3093940/40865990-355fc604-65b0-11e8-979d-83c251a4f999.jpg)
![2018-06-01_15-25-55](https://user-images.githubusercontent.com/3093940/40865991-36c1eb08-65b0-11e8-98a8-34bb862480cc.jpg)

**Comment by ACueva** [comment]
Logged an issue pertaining to the KMZ export causing a drawing issue as a result of the layer added to the table on contents.
https://github.com/Esri/distance-direction-addin-dotnet/issues/589

**Comment by ACueva** [comment]
Verified the KMZ export has the relevant attribute data as well.
KMZ was upload to an ArcGIS Online org for verification:
![2018-06-01_16-08-25](https://user-images.githubusercontent.com/3093940/40867055-51adcc42-65b6-11e8-94ca-5749fb428600.jpg)
