### ISSUE TITLE
entering numberic values into the major axis causes crash

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#372]
Procedure:

1. In ArcMap add a world background data source
2. Display Ellipse tab on Distance and Direction addin UI panel
3. Click Map Point tool
4. Move mouse over map but do not click on map
5. Enter values in Major, Minor, Angle text boxes

You can enter in major axis values with no crash if the map point tool is not selected.

**Comment by pHill5136** [comment]
Unable to reproduce. Able to specify maj axis without crash

**Comment by NatalieCampos** [comment]
unable to reproduce on build 1475. Closing issue.
