### ISSUE TITLE
Using Distance and Bearing method of creating a line Mils will not accept values over 360 - ArcMap

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#376]
When creating a line from distance and bearing and using mils, you should be able to enter a value up to 6400. Currently it only accepts values 0-360. 
![image](https://cloud.githubusercontent.com/assets/5322669/26010713/e36a61d8-3702-11e7-817a-097ebafc131a.png)

**Comment by dfoll** [comment]
@pHill5136  i found this specifically on 10.5, let me know if you need me to start reaching back and seeing if it happens elsewhere (i'm assuming it does). Also, i felt like the undesirable behavior, and how to reproduce is pretty straight forward, let me know if you want more description or specific repro steps

**Comment by pHill5136** [comment]
fixed pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/379
please verify

**Comment by dfoll** [comment]
you can now enter a value over 360 for mils, checked to make sure that you are still limited to 360 with degrees
