### ISSUE TITLE
Using Distance and Bearing method of creating a line with Mils will not accept values over 360 - ArcGIS Pro

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#377]
When creating a line from distance and bearing and using mils, you should be able to enter a value up to 6400. Currently it only accepts values 0-360. 
![image](https://cloud.githubusercontent.com/assets/5322669/26010990/05985de0-3704-11e7-97aa-54c10bc1b45a.png)

**Comment by dfoll** [comment]
@pHill5136  i found this specifically on 1.4.1, let me know if you need me to start reaching back and seeing if it happens elsewhere (i'm assuming it does). Also, i felt like the undesirable behavior, and how to reproduce is pretty straight forward, let me know if you want more description or specific repro steps

**Comment by pHill5136** [comment]
please verify pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/380

**Comment by dfoll** [comment]
you can now enter a value over 360 for mils, checked to make sure that you are still limited to 360 with degrees
