### ISSUE TITLE
Using Mils is not drawing correct output in ArcMap

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#386]
In ArcMap when using mils to draw a line, an incorrect output is being draw. I am drawing a line using degrees value of 180, and get an output that looks correct. I then switch to mils draw a line that is 3200 which should resemble the same angle, and i get something way off. Note that the preview draws where you expect it, but when you hit enter, the line zips off in the wrong direction.

![image](https://cloud.githubusercontent.com/assets/5322669/26128825/98b3ca7e-3a42-11e7-928c-1da632bc65e1.png)
preview drawing looks correct

![image](https://cloud.githubusercontent.com/assets/5322669/26128842/a57ff30e-3a42-11e7-9d08-bfb289f00f9c.png)
when you press enter, the line goes off in a different direction.

This seems to work ok in Pro.

**Comment by dfoll** [comment]
@lfunkhouser @nfeuerstein  milestone and backlog labels ?

**Comment by joebayles** [comment]
@dfoll is that angle 320 Degrees?

**Comment by pHill5136** [comment]
fixed pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/388

**Comment by dfoll** [comment]
verified fixed
