### ISSUE TITLE
Ring radials are being created as geodetic lines when they should be created as loxodromes (ArcMap).

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#389]
Radials should reflect a constant bearing, so in a mercator projection they should appear as straight lines that reflect a constant bearing from the center point to the outer ring. In ArcMap they are being created as geodetic lines.   

![image](https://cloud.githubusercontent.com/assets/5322669/26259307/44ffb48c-3c7d-11e7-8981-261127f132a7.png)
ArcGIS Pro

![image](https://cloud.githubusercontent.com/assets/5322669/26259308/4dc2956c-3c7d-11e7-9f2d-d5de8d2ff8b4.png)
ArcMap

@mfunk comments at the end of #180 for further clarification

**Comment by dfoll** [comment]
someone else may want to weigh in and check my logic before going too far into the development effort first, but this is my understanding

**Comment by nfeuerstein** [comment]
Do bearings not follow the curvature of the earth?

**Comment by NatalieCampos** [comment]
The output radials are loxodrome now.  See screen grab below.  Closing issue.
![image](https://cloud.githubusercontent.com/assets/5116835/26331471/e3100ea8-3f05-11e7-97ab-cf38e2926558.png)
