### ISSUE TITLE
unable to save features to kmz sometimes

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#397]
There is an issue with saving features to KMZ that is erratic and only sometimes repeatable.  To reproduce:

1.  Create features as any geometry (line, circle, ellipse, ring)
2. Save as KMZ

The program will hang sometimes and will need to be shut down via task manager.  This issue was first documented in #299 and was seen/observed by multiple team members on different machines.

**Comment by pHill5136** [comment]
please verify pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/399

**Comment by ACueva** [comment]
Waiting for #399 to merge before testing.

**Comment by csmoore** [comment]
@ACueva - Merged, plz kickoff build

**Comment by ACueva** [comment]
Build completed, ready to be tested.

**Comment by topowright** [comment]
I have verified this fix using build 05-31-2017_1540

**Comment by ACueva** [comment]
I've also tested Lines, Rings, Circles, and Ellipses.  Looks good on the latest build.   I did not get it to crash.
