### ISSUE TITLE
Parts (shp.xml and prj )of the shapefile remain when saving rings to kml

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#401]
When saving rings to KML one of the ,shp files used to create the kmz file is not deleted.  To repoduce:

1. Draw rings
2. Save as KMz
3.  Look in the location where the kmzs were saved.  You will see the files associated with .shp.

**Comment by BobBooth** [comment]
I saw this on recent testing of Pro2.2 (11661) and DD 2.2.0.26
![image](https://user-images.githubusercontent.com/3801392/36871086-05d2cfaa-1d6f-11e8-86ae-b0f743e286fc.png)

**Comment by topowright** [comment]
This should be fixed.

**Comment by csmoore** [comment]
Addressed in PR #549

It wasn't mentioned in the original issue which product, but this issue was observed in both ArcMap and Pro with these files left over:

ArcMap: ".cpg", ".dbf"

Pro: "_proj.shp.xml" ".shp.xml"

**Comment by BobBooth** [comment]
I verified that this is fixed.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/260d41b7-3a58-4326-b090-6448aae77f73)
Pro 2.1.0, MT build from 4/20/18.

Added steps to check this to my PR for the checklist test.

**Comment by BobBooth** [comment]
This should move to done after this PR is merged
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/126/files#diff-7e41cc728e3097aa12dfc0350aef91b3

**Comment by BobBooth** [comment]
The PR is merged, this is ready to close.
@ACueva or @dfoll
