### ISSUE TITLE
Make preview for drawing ellipses with the add-in the same experience as the widget - ArcMap

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#405]
The way the mouse is moved is same if you think about what is going on, but the preview feedback makes much more sense the way it is displayed in the widget versus the feedback in Pro. In Pro you click to set your center point, then drag out to create a circle with a diameter that represents your major axis. Click again and you squeeze the circle to shrink it down to get your minor axis.
![image](https://user-images.githubusercontent.com/5322669/27137799-ae9beb9e-50d3-11e7-84ec-074e9d40a00e.png)
![image](https://user-images.githubusercontent.com/5322669/27137801-b2bce764-50d3-11e7-8712-1c145898e2d1.png)
In the widget you draw a line that represents your major axis, then draw a second line perpendicular to that to represent your minor axis
![image](https://user-images.githubusercontent.com/5322669/27138285-0c4cdd6a-50d5-11e7-818e-4d40f568d62e.png)
![image](https://user-images.githubusercontent.com/5322669/27137871-e4e655a4-50d3-11e7-9293-b913105bccf3.png)

As pointed out, the mouse is still moving the same way, however I feel there is more business value here than just thinking the feedback in the widget is cooler. The feedback in the widget makes it much more obvious and easier to understand the orientation of your major axis, as you draw it. After you click and drag in the add-in, the direction you did the first mouse drag in, is still honored as the orientation of the minor axis, however there is no actual feedback about the orientation of the major axis until the second drag is done to give the size of the minor axis. This makes drawing an ellipse accurate to what you wanted much more difficult.

**Comment by dfoll** [comment]
@nfeuerstein @lfunkhouser i spoke with @kgonzago about this, and it may actually turn out to be a decent sized effort, so you guys can take the time to decide when it gets pulled in, but like I mentioned early, I think the business value is there.

**Comment by dfoll** [comment]
I realize I reused screenshots from ArcGIS Pro ... it works exactly the same in ArcMap and Pro

**Comment by lfunkhouser** [comment]
Closing. Won't fix. The behavior in the web will not be reproduced in Desktop.
