### ISSUE TITLE
After pressing enter to create graphics all the input values are cleared from the pane - ArcMap

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#406]
In Distance and Direction after entering all your parameters and pressing Enter to create your graphic, all the inputs you used are cleared out.  I would like to see those values stay there until you explicitly change them. I realize that the graphics are labeled, however you still immediately lose information about the center point of things like ellipses until your export the graphics and get the info from the attribute table

It looks like this behavior happens on all the tabs
- [ ] Line tab
- [ ] Circle tab
- [ ] Ellipse tab
- [ ] Rangs tab

**Comment by topowright** [comment]
We are not going to do this based on the level of effort and it is the current design.
