### ISSUE TITLE
After pressing enter to create graphics all the input values are cleared from the pane - ArcGIS Pro

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#407]
In Distance and Direction after entering all your parameters and pressing Enter to create your graphic, all the inputs you used are cleared out.  I would like to see those values stay there until you explicitly change them.This is a problem because after you press Enter you lose all information about your graphic until you export and get the information from the attribute table.

It looks like this behavior happens on all the tabs
- [ ] Line tab
- [ ] Circle tab
- [ ] Ellipse tab
- [ ] Rangs tab

**Comment by topowright** [comment]
@dfoll I feel that now we write directily to features in the addin we should be able to close this. Can you close this if you feel the same way or explain what work we would need to do to address this issue being that we currently have all actions writing to a feature class?

**Comment by topowright** [comment]
We are not going to do this based on the level of effort and it is the current design.
