### ISSUE TITLE
DD not disabling when moving to CC

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#415]
When working with DD after a while and then moving to CC.  CC will draw DD lines.  This was also repeated by @ACueva .  To reproduce:

1. Draw DD lines 
2. Close DD Pane or Switch to CC
3. Click map point tool on CC pane and begin collecting points
4. At some point, CC will begin creating DD lines.

@ACueva and I tried to switch off the DD map pointer tool to correct the issue.  However, did not fix problem.  I believe that some how the DD map pointer tool gets stuck.

**Comment by lfunkhouser** [comment]
Also test using individual components. Uninstall Military Tools and install both CC and Distance and Direction to help determine the cause of issue.

**Comment by NatalieCampos** [comment]
@kgonzago @topowright @lfunkhouser @nfeuerstein I do not see this happening in the individual addins

**Comment by topowright** [comment]
The experience that you are seeing is as designed; however, we should think about how we could possibly change this going forward.

**Comment by topowright** [comment]
I am currently logging an issue for each add-in to have the same UI experience.
