### ISSUE TITLE
Opening Distance and Direction causes ArcMap 10.5.1 to crash

### ISSUE THREAD

**Issue by adgiles** [Esri/distance-direction-addin-dotnet#416]
Trying to open the tool using the single addIn causes ArcMap 10.5.1 to crash.

**Comment by kgonzago** [comment]
@pHill5136 Can you look at this issue when you have a moment?

**Comment by pHill5136** [comment]
Working for me with latest build.

**Comment by NatalieCampos** [comment]
Just installed 10.5.1 and MT build 1611.  Clicking DD button to bring up the pane causes ArcMap to crash.

**Comment by NatalieCampos** [comment]
The crash does not seem to be happening within the single DD component.

**Comment by topowright** [comment]
I have the same issue on 10.3.1 when trying to access the Distance and Direction component installing Military Tools. I am using build 1611 as well.

**Comment by NatalieCampos** [comment]
Seen in 10.5 as well.

**Comment by kgonzago** [comment]
@NatalieCampos safe to assume issue exists in 10.3.1?

**Comment by NatalieCampos** [comment]
@kgonzago ..yes safe to assume as @topowright see it in 10.3.1

**Comment by kgonzago** [comment]
Oops didn't see @topowright's comment.

**Comment by pHill5136** [comment]
I only get the crash when installing from the addin on jenkins. If I build the addin manually I don't see it.

**Comment by lfunkhouser** [comment]
@NatalieCampos will continue to test previous builds to determine when the crash was introduced. Possibly just an issue with the single add-in.

**Comment by NatalieCampos** [comment]
Build 1591 - does not cause crash.
Build 1592 - does cause crash.  

@kgonzago @pHill5136 @lfunkhouser @nfeuerstein

**Comment by pHill5136** [comment]
@lfunkhouser @nfeuerstein @NatalieCampos @dfoll 
@kgonzago is looking into the jenkins build with this. Our testing has pointed to a likely jenkins related issue. 
fwiw: I noticed that the addin size of the good (built manually) addin is slightly larger than the addin on jenkins (one that crashes dd).

**Comment by NatalieCampos** [comment]
Build 1614 @10:36 does not cause a crash

**Comment by dfoll** [comment]
with MTA build 1614 I no longer have this crash with AM10.3.1
