### ISSUE TITLE
DD addin creates duplicate features when exporting 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#419]
When exporting to (FC, SHP, and kmz) DD creates duplicate features.  See screen grab below. To reproduce:
1.  Create features (lines)
2. Save As file type
3. Open attribute table

![image](https://user-images.githubusercontent.com/5116835/27604776-3be1763a-5b2f-11e7-8953-3bc41f730c08.png)

Edited: This is not seen in circles

**Comment by NatalieCampos** [comment]
This is not seen in Pro.  See screen grab below.

\\ncamposdt\Shared_Folder

**Comment by NatalieCampos** [comment]
The duplicate features seems to only happen with lines created from Distance and Bearing

**Comment by kgonzago** [comment]
currently looking at this issue and it boils down to the action of retrieving graphics from a list was performed twice. I'm hoping to get this narrowed down by COB today.

**Comment by kgonzago** [comment]
Fix is in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/518)

**Comment by BobBooth** [comment]
I built the add-in and tested this functionality.
Created two lines using angle and distance. Output to feature class and shapefile, feature counts match.
![image](https://user-images.githubusercontent.com/3801392/36686189-a69ec14c-1af3-11e8-80c6-0e164e4326a7.png)
Output to KMZ, features drawn in ArcGIS Earth, feature counts match.
![image](https://user-images.githubusercontent.com/3801392/36686271-e4b084f2-1af3-11e8-83da-03dce851c3f2.png)
@kgonzago - looks good.

**Comment by BobBooth** [comment]
This issue is no longer listed on the Known Issues page in the CMS.
Removing QC-Doc tag.
