### ISSUE TITLE
attribute table does not match input values

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#422]
When creating circles the on screen graphics and labeling honors the input values (as in miles), however when the feature is exported the Distance units populated in the attribute table is in kilometers and the Distance values is in kilometers.  Using an online conversion caluclator the populated distance values are correct for Kilometers.  
![image](https://user-images.githubusercontent.com/5116835/27613432-584f11c6-5b50-11e7-9a59-4e3082adc8a8.png)
With additional testing it was found that overall the attributes values for Distance and Distance type are not representative of the original input values.  See example #2 below.  The onscreen grahics say the diameter is 731 km but the Distance Value in the attribute table says that it is 365km with a Distance type of Diameter. 365km would be accurate if the input values was radius and not diameter.
![image](https://user-images.githubusercontent.com/5116835/27613526-df694e38-5b50-11e7-940e-27fd45dab567.png)
Additionally, example 3 shows that the distance units of miles is being honored but that the Distance Values are incorrect.  Once again the Distance values are for radius not diameter.  
![image](https://user-images.githubusercontent.com/5116835/27613585-23afd56c-5b51-11e7-8efc-0b49e22da86e.png)

**Comment by nfeuerstein** [comment]
Is this something that was just introduced or has the output never been tested?

**Comment by nfeuerstein** [comment]
Inaccurate results are a showstopper.

**Comment by NatalieCampos** [comment]
@nfeuerstein I do not know.  I trolled through the closed list and there were a number of attribute based issues.  But I dont know which caused this.

**Comment by NatalieCampos** [comment]
The math is for Distance is close however very very slightly off.  I used a rate 30 miles per hour for 2 hours which should have given me 60 miles (rate * time = distance).  The graffic is correct however the distance value is 59.999979.  

![image](https://user-images.githubusercontent.com/5116835/27647052-39b866ba-5bdf-11e7-9937-3f05a385dd60.png)

**Comment by pHill5136** [comment]
The value in the attribute table is the actual calculated value internally from arcgis. The difference is we round for the label, but the attribute in attribute table is exact.
