### ISSUE TITLE
attribute table does not match input values

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#423]
The values that are populated in the Distance and DistanceType field are not matching the original input values.  The Circle below was created using Diameter as a distance type.  The attribute is correct however the value for the distance type is for the radius.  This was checked with the measure tool which shows a diameter of 162 miles. 
![image](https://user-images.githubusercontent.com/5116835/27613975-70a2e056-5b53-11e7-901b-6eaca1cec1df.png)

Below is a second example of the Distance attribute being populated as a radius when the Distance Type is Diameter
![image](https://user-images.githubusercontent.com/5116835/27614021-cef33fc0-5b53-11e7-89ef-a2fcedfbe79b.png)

**Comment by nfeuerstein** [comment]
Inaccurate results are a showstopper.

**Comment by pHill5136** [comment]
Please verify pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/426

**Comment by dfoll** [comment]
this has been fixed for arcmap, still needs fixed in pro

**Comment by NatalieCampos** [comment]
This has been verified.  See screen grabs below.

![image](https://user-images.githubusercontent.com/5116835/27648188-98aad70e-5be2-11e7-8f8b-224dde62785d.png)
![image](https://user-images.githubusercontent.com/5116835/27648290-ebf3e932-5be2-11e7-8071-4202f395046c.png)
