### ISSUE TITLE
Distance values incorrect in attribute table for rings

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#424]
The distance values for rings is not calculating distance from center when not using the interactive mode.  
In Interactive mode the rings Distance attribute is calculated from the center point.  As seen below.  
![image](https://user-images.githubusercontent.com/5116835/27614938-9c4c2f2c-5b59-11e7-9bf0-92f7b559df1e.png)
When NOT using the interactive mode all rings come out with the distance value used to create them instead of distance from center.  
![image](https://user-images.githubusercontent.com/5116835/27614973-c1a6d934-5b59-11e7-91f1-66819361d1e3.png)
In addition the radial Distance values would be incorrect as 10*100 =1000 and so the radial features should have a distance of 1000.
![image](https://user-images.githubusercontent.com/5116835/27615064-7ee3fb1c-5b5a-11e7-88eb-ce4f39ec363d.png)

**Comment by nfeuerstein** [comment]
Inaccurate results are a showstopper.

**Comment by NatalieCampos** [comment]
This issue has NOT fixed as of build 1621.  When the rings are manually created at a set distance the field is populated.   
![image](https://user-images.githubusercontent.com/5116835/27649026-5b27353c-5be5-11e7-992d-b3029c218c41.png)
 But when using interactive mode attributes are still missing includiung Center X and Center Y as well as distance units.  
see screen grab below. 
![image](https://user-images.githubusercontent.com/5116835/27649199-ecb311c4-5be5-11e7-86d6-61c98f3f1a92.png)

**Comment by NatalieCampos** [comment]
This seems to be fixed in build 1625.  See screen grab below.  
![image](https://user-images.githubusercontent.com/5116835/27661989-14fe43bc-5c11-11e7-85bc-1dc864eb79c0.png)
