### ISSUE TITLE
Distance value for radials incorrect

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/distance-direction-addin-dotnet#425]
When creating a ring using a set distance between rings the resulting radial has an incorrect Distance attribute value.  For the example below, a distance between rings of 100 miles for 10 rings was used.  The Distance attribute for the resulting radial should have a value of 100 *10 =1000 as seen with the measure tool.  However the attribute value for distance in 100.  
![image](https://user-images.githubusercontent.com/5116835/27615307-1c1fbc6c-5b5c-11e7-98e9-040053b8dc54.png)

**Comment by nfeuerstein** [comment]
Inaccurate results are a showstopper.

**Comment by NatalieCampos** [comment]
This is still an issue with build 1621. See screen grab below.

![image](https://user-images.githubusercontent.com/5116835/27648637-0f279254-5be4-11e7-94b9-742371ca0c2e.png)

**Comment by NatalieCampos** [comment]
this has been fixed in 1625.  see screen grab below.

![image](https://user-images.githubusercontent.com/5116835/27662341-432e58de-5c12-11e7-92ab-9a8fb06aa27a.png)
