### ISSUE TITLE
Clean up/Delete feature branches

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#436]
Delete the feature branches that were merged into the code for the June 2017 release of Distance and Direction. If the branch is still accurate, please update the name of the branch using the feature branch naming convention, `<first initial><last initial>/<issue#>-<short description>`.
 
- [x] ProFeedback
- [x] csm/dark-icons
- [x] csm/update-readme
- [x] csmoore/version2.1.1
- [x] darktheme
- [x] ddfail
- [x] ddfix
- [x] feedback
- [x] linefeedback
- [x] pro-sdk-2.0
- [x] refreshdirectory
- [x] updatepro2.0
- [ ] v2.0
- [ ] v2.1
- [x] versionfix

**Comment by csmoore** [comment]
Done

These are the version/release maintenance branches created as part of the release process so should remain:
v2.0
v2.1

**Comment by lfunkhouser** [comment]
Verified as fixed. Closing.
