### ISSUE TITLE
Add mils to radials

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#437]
During the Esri UC 2017 tech workshop for Military Tools for ArcGIS a user requested that we support mils for all locations where we ask for orientation angle.

**Comment by dfoll** [comment]
this needs to be further clarified or closed. radials are always drawn equally spaced around the circumference of the circle. what would the case be that we would enter a directional value for radials?

**Comment by BobBooth** [comment]
The GP tool does output a bearing field 
![image](https://user-images.githubusercontent.com/3801392/42759835-545f5db4-88d6-11e8-8722-abdf741c2213.png)
that is specified in degrees for the radials features.
The addin does not add this field for the features it creates in Pro by default, nor the feature class exported from the graphics in ArcMap.
![image](https://user-images.githubusercontent.com/3801392/42759863-72dda0c0-88d6-11e8-84f4-29c6957bdf58.png)
![image](https://user-images.githubusercontent.com/3801392/42759903-894e8f22-88d6-11e8-96ce-e1e45ddd4808.png)

We could add an option to output radial bearings in mils to the GP tool (if we decide to, should log an issue in that repo), and we could add this field and the option to choose angular units for the addins.

**Comment by dfoll** [comment]
I stand corrected. What we really need, to make this issue something we can move forward with, is for someone on the team, to identify all of these areas where angular unit is displayed, or is a parameter, to make sure we offer the degrees/mils choice in those places. Also need to identify areas that we should have this information but are missing it, for example @BobBooth pointed out that if you use the gp tool, the output has a field that stores radial direction, but exported rings from the add-in do not have that field.

**Comment by topowright** [comment]
Closing this issue. This has been implemented.
