### ISSUE TITLE
Add label info to feature layer featureCollection for D&D widget

### ISSUE THREAD

**Issue by kgonzago** [Esri/distance-direction-addin-dotnet#439]
D&D widget needs to incorporate labelling info in the featureCollection object during the creation of a feature layer that renders lines, circles, ellipses and range rings. This enhancement will remove the need for "showLabels" in the main config.json of a WAB app.

**Comment by topowright** [comment]
We need to remove the documentation about adding the labels to the application.

**Comment by adgiles** [comment]
This work has been completed and the PR has been verified and accepted by @topowright on 30 Nov 17:

https://github.com/Esri/distance-direction-addin-dotnet/commit/8acab103cc9cf9451ab9d0aafd85d6dc1566be4d

All that was left to do was to remove the section in the documentation about adding the labels to the application. On looking at the released documentation (http://solutions.arcgis.com/defense/help/distance-direction/web-appbuilder/get-started-with-distance-and-direction-in-web-appbuilder-for-arcgis.htm) I cannot see this section any more so may have already been completed.

I think this just needs verifying and the issue can be closed.

**Comment by topowright** [comment]
This issue also has to do #444

**Comment by topowright** [comment]
This has been verified via XMetal and our website
