### ISSUE TITLE
Distance and Direction: Distance and Bearing on Line tab produces an inaccurate line.

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#442]
_From @kgonzago on May 12, 2017 13:23_

### Widget
Distance and Direction

### Version of widget
2.0

### Bug or Enhancement
Bug

### Repo Steps or Enhancement details
Creating a line using the Distance and Bearing option produces a line that does not represent the true angle supplied by a user. Here are the steps to reproduce:
1. Select `Distance and Bearing` option
2. Create a center point
3. Set `Length` to 1000
4. Select `Kilometers` for units
5. Set `Angle` to 90
6. Click `Enter`

What is produced is a geodesic line on the map but not at a 90 degree angle. It instead produces a line that is a little more than 90 degrees; a misrepresentation of what was supplied as input parameters. 

_Copied from original issue: Esri/solutions-webappbuilder-widgets#873_

**Comment by csmoore** [comment]
_From @nfeuerstein on May 18, 2017 16:42_

This is an API issue, it has been logged with Core.

**Comment by adgiles** [comment]
I think the results we are seeing are correct, we can replicate the same results in a third party implementation here:

http://www.movable-type.co.uk/scripts/latlong.html

Have a look at the Destination point given distance and bearing from start point example

**Comment by topowright** [comment]
Our tool is designed to draw geodesic features as a default. 
![image](https://user-images.githubusercontent.com/5488313/34787509-636b3c74-f5ec-11e7-9065-a32b281708a2.png)
This is as designed
