### ISSUE TITLE
Implement a drop down to support different workflows for Range Rings

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#443]
_From @topowright on May 4, 2017 19:33_

### Widget
Distance and Direction
### Bug or Enhancement
Currently we need to support multiple workflows for creating Range Rings: 

Allow users to create unequally spaced rings from origin through keyboard 
https://github.com/Esri/solutions-webappbuilder-widgets/issues/822

Allow users to create unequally spaced rings through keyboard from last ring
-
We can use the same approach that we use for lines in this widget to change the dialog for multiple UI views for Range Rings.  

_Copied from original issue: Esri/solutions-webappbuilder-widgets#861_

**Comment by csmoore** [comment]
_From @adgiles on May 12, 2017 13:18_

See my comment in #822

**Comment by dfoll** [comment]
@topowright @adgiles @lfunkhouser i feel like this is just a portion of what is covered in #445  can we just close this issue, because this functionality will be covered.

**Comment by topowright** [comment]
Closing this issue because it is a duplicate as stated above by @dfoll 
https://github.com/Esri/distance-direction-addin-dotnet/issues/445

**Comment by dfoll** [comment]
This is a duplicate issue we should remove in our daily stand up
