### ISSUE TITLE
Distance and Direction: Distance Calculation should label based on units specified in Distance Calculation parameters

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#444]
_From @elinz on February 17, 2017 17:21_

### Widget
Distance and Direction

### Version of widget
1.0 release of Military Tools for ArcGIS

### Bug or Enhancement
Perform distance calculation where center point is on New York City, time is 24 hours, rate is 60 miles per hour, which equals 1440 miles.

The widget labels the output graphic based on the Radius/Diameter units instead of the units set in the Rate parameter. For this example, I specified the rate as "Miles / Hour" so the labeled units should be Miles.

Also when you perform distance calculations the output should be labeled as "Radius" no matter if the "From" parameter is set to Radius or Diameter.

![image](https://cloud.githubusercontent.com/assets/4635490/23075646/1d619be8-f4f2-11e6-8627-1286261df965.png)

@kgonzago FYI.

### Repo Steps or Enhancement details

_Copied from original issue: Esri/solutions-webappbuilder-widgets#831_

**Comment by csmoore** [comment]
_From @adgiles on February 20, 2017 11:1_

@elinz 

The label is set using the units specified by the user in the drop downs. When the distance calculator is used it converts the calculated distance to the correct figure in the distance input box.

So for example if I have the units set to meters and the create circle from radius, and I use the distance calculator to work out 2 hours at 10 kilometres per hour, the units will automatically be filled in as 20,000 meters, and this value and radius will be used for the label:

![1](https://cloud.githubusercontent.com/assets/3740334/23122280/80f3d426-f75b-11e6-904f-73b232ea55fb.png)

if I have the units set to meters and the create circle from diameter, and I use the distance calculator to work out 2 hours at 10 kilometres per hour, the units will automatically be filled in as 10,000 meters, and this value and diameter will be used for the label:

![1](https://cloud.githubusercontent.com/assets/3740334/23122352/c29af5ee-f75b-11e6-85b4-a3bac2b6b191.png)

I personally think this is how the widget should behave

**Comment by csmoore** [comment]
_From @elinz on February 21, 2017 16:19_

@adgiles @kgonzago @nfeuerstein We'll need to discuss this further and make a final decision.

**Comment by csmoore** [comment]
_From @Dbarnes1 on March 14, 2017 20:31_

@adgiles @elinz @kgonzago @nfeuerstein you can see I created an issue in Distance and Direction add-in repo that references this issue. We should address these inconsistencies for the next release.

**Comment by topowright** [comment]
It would also be nice if we start stacking labels so that the label is not bigger than the area/feature that is being labeled.   I also know that we added the capability to the GRG widget that allows for labels to work without having to change the config file on the app that is housing the widget. Could that be done apart of this as well? 

@adgiles how large of an effort would that be?

**Comment by adgiles** [comment]
@topowright there is already an issue (#439) to address the labels to work without changing the config

**Comment by BobBooth** [comment]
@adgiles - is the latest version available on the Try It site?
https://nationalsecurity.esri.com/solutionsweb/DistanceAndDirection/

**Comment by BobBooth** [comment]
@adgiles  - the functionality seems to be working, but there is one usability issue. If you create a circle by clicking a point, then want to change the units of the label (but keep the center point and distance), when you use the dropdown, the value in the distance box does not update. This is not a problem if you click back in the Rate box and hit Enter, but if you click the OK button, you get a new circle of different radius. This seems strange. 
So, for example, I click a point, units are Meters, and in the Distance Calculator, I set the Time for 1 Hour and the Rate for 70 Miles per Hour.
I get:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/2e7718d4-aa1c-4986-9b3d-a002aa2ef221) 
It is the correct size and the right number of meters, but now I realize that I want the label to be in Miles.
I click the radius Units dropdown and set it to Miles.
When I click OK, I get an 112,654.08 mile diameter 'circle'
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/936e3ab6-13ac-4225-8457-7e89647aed17)
If the value in Radius updated when I changed the units, this would not happen.
I can make it work as expected/designed by changing the Units to Miles and then clicking in the Time or Rate boxed and hitting Enter.

**Comment by topowright** [comment]
@adgiles We need to recalculate the radius/diameter value when someone selects a different unit of measure. Currently if you do not update the rate in the distance calculator and you choose a different radius/diameter unit of measure the tool will not update:  
![image](https://user-images.githubusercontent.com/5488313/34799938-9f59b4c0-f616-11e7-81bc-7712b443d21c.png)

**Comment by adgiles** [comment]
Added a check to see if the distance calculator is open when the distance units change, if so, recalculate the radius value based on the time and rate.

The reason why we need the check to see if the calculator is open is we don't want the value to change when a user is not using the calculator 

in PR #485

**Comment by BobBooth** [comment]
I have tested this issue using the latest copy of the widget from the repo on my local machine in WAB 2.6, and it now works correctly.
(thanks @ACueva for the help getting WAB running).
I believe this issue may be closed now.
@topowright  @adgiles

**Comment by BobBooth** [comment]
Added steps to checklist test to exercise these changes.
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/86

**Comment by topowright** [comment]
This needs to be reviewed by a PE before we can move this to done.
