### ISSUE TITLE
Distance and Direction - Rings - Allow user to create unequally spaced rings through keyboard

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#445]
_From @elinz on January 26, 2017 17:59_

### Widget
Distance and Direction 
### Repo Steps or Enhancement details
We allow the user to interactively create unequally spaces rings...
![image](https://cloud.githubusercontent.com/assets/4635490/22343647/be51af6c-e3ad-11e6-8bca-d17f52ed037f.png)

It would be very useful to be able to create unequally spaces rings through the keyboard. For user input the user could enter a delimited list of distances, for example...
![image](https://cloud.githubusercontent.com/assets/4635490/22343732/0906af30-e3ae-11e6-9822-5bf13eaeb057.png)

_Copied from original issue: Esri/solutions-webappbuilder-widgets#822_

**Comment by csmoore** [comment]
_From @adgiles on February 1, 2017 16:56_

@elinz 

Updated please verify that it behaves as expected

**Comment by csmoore** [comment]
_From @lfunkhouser on May 2, 2017 4:52_

Assigning to MT PEs to verify. @dfoll @topowright @ACueva @NatalieCampos

**Comment by csmoore** [comment]
_From @ACueva on May 2, 2017 21:6_

I got this one.

**Comment by csmoore** [comment]
_From @ACueva on May 2, 2017 23:12_

Tested and this sort of works.  I say this because this works:

![2017-05-02_16-10-11](https://cloud.githubusercontent.com/assets/3093940/25642955/e2e25738-2f51-11e7-82e6-79170c33865c.png)

If we add spaces to the entry, it no longer works:

![2017-05-02_16-11-17](https://cloud.githubusercontent.com/assets/3093940/25642995/00c6112c-2f52-11e7-94d0-bfca397cf844.png)

IMO the second would be what a user would enter.
@nfeuerstein @lfunkhouser thoughts?

**Comment by csmoore** [comment]
_From @ACueva on May 2, 2017 23:13_

@kgonzago

**Comment by csmoore** [comment]
_From @topowright on May 2, 2017 23:22_

@ACueva had an issue with this tool not calculating properly. Here is an example of what is happening: 

![image](https://cloud.githubusercontent.com/assets/5488313/25643260/93ef00d4-2f53-11e7-9ba3-a9610bb2f518.png)

The outer circle should be 6000 meters, but it is 3000 meters, which means that the last circle is calculating from the center point and not the second to last ring.

**Comment by csmoore** [comment]
_From @topowright on May 2, 2017 23:26_

Here is another example of this tool calculating it incorrectly: 

![image](https://cloud.githubusercontent.com/assets/5488313/25643333/14b77d68-2f54-11e7-850d-f2138af40469.png)

**Comment by csmoore** [comment]
_From @topowright on May 2, 2017 23:29_

This tool would work if we changed the name of the tool from distance between rings to distance from origin. This is per @ACueva logic of what this tool could be vs. looking at what it is not. 

If we choose to do this we should still log an enhancement from Distance Between Rings.

**Comment by csmoore** [comment]
_From @topowright on May 2, 2017 23:30_

@kgonzago @nfeuerstein @lfunkhouser

**Comment by csmoore** [comment]
_From @lfunkhouser on May 3, 2017 0:0_

Dev work is required either way. 

Including an option to draw rings based on distance from origin would require a UI enhancement. This would give the user an option to select either draw rings based on distance between rings (as currently designed) or draw based on distance from origin (how it is currently behaving). 

If we plan to include this enhancement, it is not working as expected and would require dev work.

My recommendation is to revert this change and add to planned work for a future release. 

FYI @nfeuerstein

**Comment by csmoore** [comment]
_From @kgonzago on May 4, 2017 15:9_

@lfunkhouser I would suggest we stick with what's implemented and change the label to "Distance from Origin". We then tackle "Distance between Rings" functionality in the next iteration. Thoughts?

**Comment by csmoore** [comment]
_From @topowright on May 4, 2017 19:21_

changing the label is not possible because it will affect the other workflow that is already in place.

**Comment by csmoore** [comment]
_From @ACueva on May 10, 2017 15:24_

@nfeuerstein @lfunkhouser If this item is to be addressed this version, PE's will need to sequence diagram and plan for these changes.  Please confirm these changes should be incorporated into this release.

**Comment by csmoore** [comment]
_From @adgiles on May 12, 2017 13:16_

Here is my suggestion, the current widget UI looks something like:

![1](https://cloud.githubusercontent.com/assets/3740334/25999418/f1758d74-371c-11e7-97c4-27a02bfa3f00.png)

I recommend adding a drop down with the following 4 creation types (Interactively | Fixed |
Origin | Cumulative). Then change the UI depending on the choice:

![2](https://cloud.githubusercontent.com/assets/3740334/25999472/24ebf0bc-371d-11e7-9ca2-071b3e96f8fe.png)
![3](https://cloud.githubusercontent.com/assets/3740334/25999475/280a7c3c-371d-11e7-8d08-d01b1cdb8ed3.png)
![4](https://cloud.githubusercontent.com/assets/3740334/25999479/2a3fecda-371d-11e7-9ad7-9a24ef37e322.png)
![5](https://cloud.githubusercontent.com/assets/3740334/25999489/36f3abe2-371d-11e7-9ce7-a4bdfc1f0aee.png)

For Origin and Cumulative the UI element is like a table that allows distances to be added or removed similar concept as the Multl Ring Buffer in desktop

**Comment by topowright** [comment]
@dfoll will take a closer look at this.

**Comment by dfoll** [comment]
@adgiles i'm looking at your UI design while sitting in the meeting right now. I like the design. I'd say go with it, and i'd like to test it. I have one question that i would bring up, and maybe you have thought this through already....when doing "from origin" (which is done through the keyboard) what happens if the value in row 2 is a smaller value than row 1?  would the tool  actually be drawing the values in the order they are in the list, or is that list basically just a collection of values.... another way of asking is does row 1 =ring 1  and row 2 = ring 2 etc.?     .... just thinking forward, wondering if there is a problem if the value in row 2 is smaller than row 1 .... if there is rooms for my input in this, i would say row1 does not need to equal ring 1, that the "table" is just a list of values

**Comment by adgiles** [comment]
@dfoll it would just be a list of values, and loop through them so the order wouldn't really matter

**Comment by dfoll** [comment]
@adgiles cool, sounds good, that's what i figured, just trying to think of what i could, before i have one to physically use, but as far as what you have for your UI design, i like the way it looks and the way i believe it is intended to function

**Comment by adgiles** [comment]
@dfoll 

Development work complete in this PR #486

Should be good to test once merged

**Comment by dfoll** [comment]
@adgiles cool, i'll work with this today, should have something for you when you are back in tomorrow

**Comment by dfoll** [comment]
I am still testing this, looks good so far. tomorrow morning will be more testing and documenting.

**Comment by topowright** [comment]
We are not going to be able to finish the documentation on this item before the end of the sprint. We need to pull this out of the sprint. @lfunkhouser

**Comment by topowright** [comment]
We need to understand what documentation needs to be finished.

**Comment by topowright** [comment]
This needs to be documented for WAB 6.1

**Comment by BobBooth** [comment]
The dev daily build snapshot of web app builder 2.8:  arcgis-web-appbuilder-2.8-snapshot.zip
is broken. Went over this with @kgonzago 
numerous dependencies not present, including:
dbutilities.js
db-engine.js

NPM installs missing:
cookie parser
body parser      
express

JSON:
config.json
log4json.json

Ran out of time trying to get build working.

**Comment by BobBooth** [comment]
A new snapshot file, dated today, is now available. I'm grabbing it and giving that a try.
@kgonzago

**Comment by BobBooth** [comment]
This WAB version from today is working.

**Comment by BobBooth** [comment]
@adgiles   @kgonzago                            
Testing the Origin and Cumulative construction methods of creating Rings, found a few problems. 
1) When I'm adding values to this list, I click in the "Double click to add value" box, and the text is not selected, so I have to manually select and delete it before entering a value.
2) There seems to be no way to delete distance values entered in the Origin/Cumulative methods of creating rings.
Deleting the text gets rid of it temporarily, but pressing Enter or clicking in another box then restores the value.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/a25bcd89-e70d-4704-a752-dec6a760000e)
Clear Graphics, switching to another tab, and switching to another method all also fail to reset the values.
3) After entering a value, pressing Enter does not commit the value and move on to the next box (or next item in the GUI).

tested in daily build (2/20/18 of Web App Builder DE and the latest widget downloaded as a zip from the arcgis-webappbuilder-kevi2741-distance-and-direction branch of the repo.

**Comment by BobBooth** [comment]
Aside from that, the new rings functionality seems to be working correctly.

**Comment by BobBooth** [comment]
Submitted issues:
https://github.com/Esri/distance-direction-addin-dotnet/issues/508
https://github.com/Esri/distance-direction-addin-dotnet/issues/507
https://github.com/Esri/distance-direction-addin-dotnet/issues/506

**Comment by BobBooth** [comment]
Seems like some controls from the earlier design are missing:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/660ac02d-1a7c-44b1-b86d-524b9031ce5f)
vs
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/4cf66057-aaa0-47da-9131-c84c0e18f178)

**Comment by BobBooth** [comment]
After testing in WAB(DE)2.8, I went back and grabbed WAB(DE) 2.7 and set it up with the widget from @kgonzago latest branch.
I am seeing the problem with the color picker that I saw when I initially stared to test on WAB(DE)2.6.
Clicking in the Line Color color patch pops up the color-picker, but then it behaves strangely, the color indicator marker zooms up and down the scale, the picked color does not get applied.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/fe73a6bb-a389-41fb-a3d6-adb00bd815cf)
This may be unrelated to the version, but to some difference in @kgonzago repo and WAB?

**Comment by BobBooth** [comment]
Testing on WAB(DE) 2.7 I am seeing the Origin and Cumulative construction methods work in the same way (but with the same problems for usability) that I saw on 2.8.

**Comment by BobBooth** [comment]
Kevin showed me that this was a problem with localization of labels making the app miss the tools.
He is fixing.

**Comment by kgonzago** [comment]
Fixed in [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11837)

**Comment by kgonzago** [comment]
FYI: ColorPicker issue is a known issue with Dojo 1.9 and not with WAB team.

**Comment by BobBooth** [comment]
I verify that the missing UI elements are back.

**Comment by lfunkhouser** [comment]
@BobBooth Can you give more detail to the environment you are using to verified that the UI elements are back - on 2.8? 2.7? 2.6? Which browsers were tested?

**Comment by BobBooth** [comment]
@lfunkhouser - tested on 2.8 and 2.7 (most recently on 2.7). Tested on Chrome. 
@kgonzago talked me through editing a few strings in one of the js files when I initially found the issue, testing on 2.8. That fixed the problem. Kevin then made the fix in the repo and provided the code in his PR listed above. It now works.

**Comment by BobBooth** [comment]
Have now also tested on FireFox with WAB2.7.
UI elements are back and working correctly on FF too.

**Comment by BobBooth** [comment]
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/a074cad0-18b6-490f-891b-e397d2d880ee)

**Comment by BobBooth** [comment]
PR submitted to update checklist test:
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/88

**Comment by BobBooth** [comment]
So, where this stands is, the code is now merged, test checklist updated.
I found another issue that @adgiles  and @kgonzago  are looking at:
https://app.zenhub.com/workspace/o/esri/distance-direction-addin-dotnet/issues/514
Will test any available fix Friday am, before I head out.

**Comment by dfoll** [comment]
I believe this can be closed. The documentation is in WAB and WAB DE here
https://developersdev.arcgis.com/web-appbuilder/guide/widget-distance-and-direction.htm
http://docdev.arcgis.com/en/web-appbuilder/create-apps/widget-distance-and-direction.htm

**Comment by dfoll** [comment]
moved back to sprint 4 because I realize I never updated the checklist test. Removed Doc-CMS because the workflow has been updated. Removing automated test labels because we don't have automated tests labels because we are not doing any automated testing with the widgets

**Comment by adgiles** [comment]
@dfoll, @bobbooth has a PR above with the updated checklist test

**Comment by dfoll** [comment]
@BobBooth I've got your two pull requests for the widget in now.

**Comment by dfoll** [comment]
verified @BobBooth checklist test is good. I checked the Doc @topowright wrote for the widget... removing both those tags
