### ISSUE TITLE
Allow user to copy information from graphic label created in Distance and Direction Widget

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#447]
_From @lfunkhouser on December 16, 2016 17:59_

_From @kgonzago on November 4, 2016 18:47_

The D&D widget renders graphic labels after a shape is drawn. The labels have information about the shape that was created (ex: length, angle, radius). Provide the ability to copy/past those labels.

_Copied from original issue: Esri/military-tools-webappbuilder#110_

_Copied from original issue: Esri/solutions-webappbuilder-widgets#725_

**Comment by topowright** [comment]
@adgiles how hard would this be. I see the value as a user to be able to quickly copy the length of a line or an area of a polygon.

**Comment by adgiles** [comment]
I have enabled feature popups, from there the user can click on a feature then copy out the information required. The information can also be copied from the attribute table if enabled in the application.

In PR #470

**Comment by topowright** [comment]
Verified: 
![image](https://user-images.githubusercontent.com/5488313/33457204-9c47cd9a-d5d6-11e7-8a3c-33cfd2df6ca6.png)
