### ISSUE TITLE
Create Circle from Radius/Diameter - value entered is always radius

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#448]
If I set the type to Radius and click a point, then type 600 (units = Meters) and press Enter, I get a circle of 1200 m diameter (label says "Radius: 600 Meters").
If I set the type to Diameter and click a point, then type 600 (units = Meters) and press Enter, I get a circle of 1200 m diameter (label says "Diameter: 1200 Meters").
![image](https://user-images.githubusercontent.com/3801392/30926454-39cfe934-a383-11e7-9e0f-0f30a1d3cbff.png)

I initially expected having Diameter selected would make a circle of Diameter equal to the value I typed (e.g. only 600 Meters in diameter).  This could lead to confusion for people not familiar with the tool.
Perhaps the label on the input text box could be set to be only Radius, if that's the real input value?

Testing in ArcMap 10.6 (8184) with Distance and Direction Addin 2.1.1

**Comment by BobBooth** [comment]
This is also an issue in the combined add-in, Military Tools 2.0

**Comment by lfunkhouser** [comment]
@dfoll Also found and logged this issue. I closed it due to being a duplicate. @dfoll @BobBooth was this an issue with the released solution on 10.3.1-10.5.1? Or is it something that just happened? Have you worked with @csmoore to provide additional details as to why this is happening?

**Comment by topowright** [comment]
This issue was present in all releases of the solution, it was not an issue at 10.6. We need to fix this issue going forward.

**Comment by csmoore** [comment]
@BobBooth is correct - this is confusing in ArcMap because the value you enter is always treated as a radius value:

![image](https://user-images.githubusercontent.com/3090809/36804285-1d6c6320-1c88-11e8-847a-8dc13d924c73.png)

Does not behave this way in Pro

**Comment by csmoore** [comment]
Addressed in #530 - should look/behave like this now in ArcMap:

![image](https://user-images.githubusercontent.com/3090809/36904995-27af9ba8-1e00-11e8-80cb-b773a600f430.png)

**Comment by BobBooth** [comment]
This is working for me on ArcMap 10.0.0.8321  Distance And Direction 2.2.0.31.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/905bcd40-0158-4908-b2e7-9b20a5ca8584)

**Comment by dfoll** [comment]
Verified fixed in ArcMap 10.6.0.8321 with MT build 23 (5Mar)
