### ISSUE TITLE
Ellipse tab does not validate that the major axis is larger than the minor axis, resulting in incorrectly labeled ellipses.

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#450]
#### Background
The Ellipse tool does not validate that the typed input to the Major and Minor axes is mathematically correct, allowing you to enter larger values for the Minor axis than the Major one.
This results in an ellipse that is created with an incorrect label, since, by definition, the Major Axis of an ellipse is the longer one.
![image](https://user-images.githubusercontent.com/3801392/30928863-bb14e4c0-a38a-11e7-8652-e8c6425ee9dc.png)
#### Expected Results
The UI validation will not allow a minor axis greater than the major axis

Testing in ArcMap 10.6, Distance and Direction Add-In 2.1.1

**Comment by BobBooth** [comment]
This issue exists in the combined Military Tools 2.0 add-in.

**Comment by dfoll** [comment]
@topowright @kgonzago @lfunkhouser build 12  in ....\Commercial\Solutions\DefenseSolutions\DistanceAndDirection\Testing can be used to test this functionality

**Comment by dfoll** [comment]
I am ready for someone to doc review this

**Comment by BobBooth** [comment]
@dfoll 
I checked, and the issue is correctly mentioned in the DD January 2019 and Military Tools January 2019 pages in the Issues Addressed tables.

**Comment by lfunkhouser** [comment]
@topowright Why v 10.6 for ArcMap? Has Jenkins/build machine been updated for Pro 2.3?

**Comment by lfunkhouser** [comment]
Updated label to v 10.3.1.
