### ISSUE TITLE
Ellipse tool axis labels incorrect in ArcMap with "Semi" Ellipse Type

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#451]
The Ellipse tool has Semi or Full Ellipse Type input values.
If I choose Semi, set an angle of 45 and type a major axis value of 500 Meters and a minor axis value of 250 Meters, I get an output ellipse labeled 
"Major Axis: 500 M 
Minor Axis 250 M
Orientation Angle 45 Degrees"
If I click elsewhere for a new ellipse, choose Full, set an angle of 45 and type a major axis value of 500 Meters and a minor axis value of 250 Meters, I get an output ellipse labeled exactly the same:
"Major Axis: 500 M 
Minor Axis 250 M
Orientation Angle 45 Degrees"
But it is half as long and half as wide.
![image](https://user-images.githubusercontent.com/3801392/30929754-74d70bb6-a38d-11e7-9f02-cee5683ed987.png)
![image](https://user-images.githubusercontent.com/3801392/30929759-7d2e8f32-a38d-11e7-9a7e-bf62cdb30e2a.png)

The input values were interpreted as being the full Major Axis length and the full Minor Axis length.
The labels (at least) should be updated to be 
Semi-Major Axis: 500 M 
Semi-Minor Axis 250 M
for Semi
and 
Major Axis: 500 M 
Minor Axis 250 M
for Full.

Testing on ArcMap 10.6, with Distance and Direction 2.1.1

**Comment by BobBooth** [comment]
The Semi ellipses are labeled incorrectly. With input of 300 m for Major axis, using Semi option, the length of the ellipse is 600 m.

**Comment by BobBooth** [comment]
This is also an issue with the combined add-in, Military Tools 2.0

**Comment by lfunkhouser** [comment]
@BobBooth Was this an issue in 10.3.1-10.5.1?

**Comment by BobBooth** [comment]
This problem still exists, ArcMap 10.6.0.8321 Military Tools 2.0
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/929bb62c-f598-4326-95a8-528e1a977eb6)
The problem is the labeling for the ellipses created using Semi option. They are labeled with the value used in the input boxes for major and minor axes, but with the Semi option, the ellipse that is actually created has Major and Minor axes that are really 2x as large.
This seems like a minor fix, to make the label process aware of whether the Semi or Full option was used.
@kgonzago  @csmoore

**Comment by csmoore** [comment]
Addressed in PR #513 - ready to QA/QC after merge. Labels look like now with same values and semi/full ellipse type applied

![image](https://user-images.githubusercontent.com/3090809/36541605-755cdc62-17ac-11e8-8e86-961e1ff1111f.png)

**Comment by dfoll** [comment]
removing QC - Verify Checklist - there was already a section in the checklist test for ArcMap that the tester draw an ellipse using "semi" and ensures the measurement and labels are correct and then does the same thing for "full".

**Comment by dfoll** [comment]
Verified this issue no longer exists with ArcMap 10.6.0.8321 and Distance and Direction add-in 2.2.0.30 or with ArcMap 10.6.0.8321 and Military Tools 3.0 build 23 (5Mar)
