### ISSUE TITLE
Ellipse that extends outside of basemap extent exports to empty geometry in GDB

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#454]
I used the Distance and Direction Ellipse tool to create an ellipse that extends outside of the basemap extent (Web Mercator, AGOL Topo basemap).
The ellipse draws fine.
When exported to a feature class, there is a row for the feature, but no Shape Length or Area, and Zoom To fails to zoom to the graphic location (zooms to the west coast of Africa).
![image](https://user-images.githubusercontent.com/3801392/31032545-66022050-a52a-11e7-8ef5-1cea71d723bf.png)
Testing on ArcMap 10.6 (8184) and Military Tools add-in 2.0.

**Comment by topowright** [comment]
@BobBooth @kgonzago what is the workflow we are expecting to address? I am not sure if anyone would expect a ellipse being drawn at the small scale in the first screen capture for this issue. This might not be an issue. @dfoll @ACueva please share your thoughts for this issue. I feel like this is not an issue.

**Comment by topowright** [comment]
Moving this to impeded to draw as much attention to this issue before we start doing any work on this issue.

**Comment by kgonzago** [comment]
@BobBooth Could this be an international dateline issue?

**Comment by topowright** [comment]
It is an international dateline issue. I am confused on what we expect to change.

**Comment by topowright** [comment]
Here is an ellipse that crosses the dateline:
![image](https://user-images.githubusercontent.com/5488313/36316444-2f6d0ea0-12ef-11e8-95a8-ca10291f95d5.png)
![image](https://user-images.githubusercontent.com/5488313/36316543-77569a60-12ef-11e8-96cc-a405cbec8aee.png)


From this screen capture in ArcGIS Pro it seems like everything is captured in the feature class. @BobBooth please share what you feel like I am missing.

**Comment by BobBooth** [comment]
I tested on Pro 2.1.0 and I do not see this problem any longer.
![image](https://user-images.githubusercontent.com/3801392/36317155-4cf5ca0a-130a-11e8-933a-85a06a06e643.png)
The problem before was that although the graphic was being created correctly by the tool, when exported to a feature class the geometry was empty or broken.
Seems fixed now.
@topowright  @kgonzago
