### ISSUE TITLE
Static Code Analyzer : Null Dereference

### ISSUE THREAD

**Issue by jmccausland** [Esri/distance-direction-addin-dotnet#456]
the SCA report shows there are possible Null Dereference issues in the code.

Most of the flagged code is due to query interfaces via the 'as' keyword.  When it is safe to do a direct cast to an Esri API Interface, we should do that.  Everywhere else, null check and refactor if needed.

The ReSharper tool can assist with this exercise and minimize these issues in the future.

- when safe, change to direct cast
- add null checks and refactor where needed

**Comment by csmoore** [comment]
We have a better understanding of this now we have the report - this work is progressing in branch: https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23456-SCA

**Comment by csmoore** [comment]
The remaining High Priority SCA issues have been completed in branch: https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23456-SCA

I just need to do some testing/admin and then the SCA issues can be moved to QA.

**Comment by csmoore** [comment]
Issues #456 #457 #458 #459 #460 #461 #462 #463 #464 are all related to the Static Code Analysis(SCA) so for simplicity moving 457-464 to done and attaching all of the verification items to this issue (most of the SCA issues were related to this specific issue and the ArcObjects Query Interface programming pattern).

These are addressed in PR #502

For now, unless the same SCA tool is used, QA/QC would involve reviewing PR #502 and building the code to verify there are no warnings. Note: the Compiler Option: "TreatWarningsAsErrors" has been enabled so warnings will cause the build to fail (now and in the future)

**Comment by csmoore** [comment]
@ACueva @topowright - please verify this with the build after PR #502 is merged - thanks

**Comment by ACueva** [comment]
Service Request #706864 logged to address this issue.  There was maintenance performed Friday on this network share.  It's possible this is related.

**Comment by ACueva** [comment]
Network share has been restored.  I was able to build our addin successfully.  There are 12 warnings left. 6 are for ArcMap, 6 for ArcGIS Pro.  All of these issues appear related to the Coordinate Conversion library. FYI @csmoore 

ArcGIS Pro
```
Helpers\ImportCSV.cs(58,13): warning CS0162: Unreachable code detected [C:\Jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\imribc2i.tmp_proj]
  Models\CoordinateConversionLibraryConfig.cs(77,30): warning CS0168: The variable 'ex' is declared but never used [C:\Jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\imribc2i.tmp_proj]
  Models\CoordinateConversionLibraryConfig.cs(107,30): warning CS0168: The variable 'ex' is declared but never used [C:\Jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\imribc2i.tmp_proj]
```
```
 Helpers\ImportCSV.cs(58,13): warning CS0162: Unreachable code detected [C:\Jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\CoordinateConversionLibrary.csproj]
  Models\CoordinateConversionLibraryConfig.cs(77,30): warning CS0168: The variable 'ex' is declared but never used [C:\Jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\CoordinateConversionLibrary.csproj]
  Models\CoordinateConversionLibraryConfig.cs(107,30): warning CS0168: The variable 'ex' is declared but never used [C:\Jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\CoordinateConversionLibrary.csproj]
```
ArcMap
```
Helpers\ImportCSV.cs(58,13): warning CS0162: Unreachable code detected [c:\jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\kxknv1ww.tmp_proj]
  Models\CoordinateConversionLibraryConfig.cs(77,30): warning CS0168: The variable 'ex' is declared but never used [c:\jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\kxknv1ww.tmp_proj]
  Models\CoordinateConversionLibraryConfig.cs(107,30): warning CS0168: The variable 'ex' is declared but never used [c:\jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\kxknv1ww.tmp_proj]
```
```
Helpers\ImportCSV.cs(58,13): warning CS0162: Unreachable code detected [c:\jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\CoordinateConversionLibrary.csproj]
  Models\CoordinateConversionLibraryConfig.cs(77,30): warning CS0168: The variable 'ex' is declared but never used [c:\jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\CoordinateConversionLibrary.csproj]
  Models\CoordinateConversionLibraryConfig.cs(107,30): warning CS0168: The variable 'ex' is declared but never used [c:\jenkins\workspace\Add-ins\DD\DD_Pipeline\coordinate-conversion-addin-dotnet\source\CoordinateConversion\CoordinateConversionLibrary\CoordinateConversionLibrary.csproj]
```

**Comment by csmoore** [comment]
OK those warning were in the CoordinateConversionLibrary project, which is now included in D&D, and I wasn't sure if we could change - but I guess we should - updated in the PR https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/480 - please retest after that PR is merged

**Comment by ACueva** [comment]
IST just informed me that the network share is down once again.  At this time we are unable to build any of our addins.

**Comment by ACueva** [comment]
Confirmed these warning messages went away.  New warning introduced.
```
  C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "ESRI.ArcGIS.ADF.Connection.Local, Version=10.3.0.0, Culture=neutral, PublicKeyToken=8fc3cc631e44ad86, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [c:\jenkins\workspace\Add-ins\DD\DD_Pipeline\distance-direction-addin-dotnet\source\addins\ArcMapAddinDistanceAndDirection\ArcMapAddinDistanceAndDirection\ArcMapAddinDistanceAndDirection.csproj]

    1 Warning(s)
    0 Error(s)
```
@csmoore Any ideas?  Will log an issue to address this warning.

**Comment by ACueva** [comment]
New issue created to address this issue: https://github.com/Esri/distance-direction-addin-dotnet/issues/509

**Comment by ACueva** [comment]
Verified Warning messages other than Issue: https://github.com/Esri/distance-direction-addin-dotnet/issues/509  have been addressed.

**Comment by ACueva** [comment]
I don't believe this issue warrants a checklist test.  Am I missing something @csmoore ?

**Comment by csmoore** [comment]
@ACueva - sounds good - feel free to remove the label if it doesn't apply (if I added it was probably just force of habit) - the projects are set to fail to build if there is a warning now so automated check is mostly sufficient (though this does not catch the "MSBuild" warnings as you saw above)
