### ISSUE TITLE
Static Code Analyzer : Error Handling : Overly Broad Catch

### ISSUE THREAD

**Issue by jmccausland** [Esri/distance-direction-addin-dotnet#457]
- update code to only handle known exceptions
- let the rest bubble up, remove catch(Exception ex)

**Comment by csmoore** [comment]
There may be more to this issue once we see the report but as it is currently stated I'm not sure we want to do this one. It is basically saying to remove the exception handlers (and let crash?). @kgonzago @lfunkhouser

**Comment by csmoore** [comment]
Addressed in PR #502 and can be verified with #456 (see: https://github.com/Esri/distance-direction-addin-dotnet/issues/456#issuecomment-366808136).
