### ISSUE TITLE
Static Code Analyzer : Empty Catch Block

### ISSUE THREAD

**Issue by jmccausland** [Esri/distance-direction-addin-dotnet#458]
- remove try/catch or comment if needed but does nothing

**Comment by csmoore** [comment]
Addressed in PR #502 and can be verified with #456 (see: https://github.com/Esri/distance-direction-addin-dotnet/issues/456#issuecomment-366808136).

**Comment by ACueva** [comment]
This has been verified.  There are no longer any references to this build warning on the latest build.
