### ISSUE TITLE
Static Code Analyzer : Logging Practice with use of system output stream

### ISSUE THREAD

**Issue by jmccausland** [Esri/distance-direction-addin-dotnet#459]
- remove outputs or wrap with 
```#if DEBUG ```
```#endif```

**Comment by csmoore** [comment]
Addressed in PR #502 and can be verified with #456 (see: https://github.com/Esri/distance-direction-addin-dotnet/issues/456#issuecomment-366808136).

**Comment by ACueva** [comment]
This has been verified.  There are no longer any references to this build warning on the latest build.
