### ISSUE TITLE
Static Code Analyzer : Dead code

### ISSUE THREAD

**Issue by jmccausland** [Esri/distance-direction-addin-dotnet#462]
- remove or ignore

**Comment by csmoore** [comment]
Moving this to impeded just until we can see the original report. 

I did not see an instances of this in the compile warnings

**Comment by csmoore** [comment]
Addressed in PR #502 and can be verified with #456 (see: https://github.com/Esri/distance-direction-addin-dotnet/issues/456#issuecomment-366808136).

**Comment by ACueva** [comment]
This has been verified.  There are no longer any references to this build warning on the latest build.
