### ISSUE TITLE
Static Code Analyzer : Streams

### ISSUE THREAD

**Issue by jmccausland** [Esri/distance-direction-addin-dotnet#463]
- fix with using() statement

```using( var fs = new Stream())```
```{```
```    // do something```
```}```

**Comment by csmoore** [comment]
This looks like it was done already - didn't see any cases without "using"

**Comment by csmoore** [comment]
Moving this to impeded just until we can see the original report and verify this is no longer an issue

**Comment by csmoore** [comment]
@jmccausland was able to provide the SCA report - this has been posted to https://esri.app.box.com/folder/46853195584

**Comment by csmoore** [comment]
Addressed in PR #502 and can be verified with #456 (see: https://github.com/Esri/distance-direction-addin-dotnet/issues/456#issuecomment-366808136).

**Comment by ACueva** [comment]
This has been verified.  There are no longer any references to this build warning on the latest build.
