### ISSUE TITLE
Map Tool does not activate when Re-launching ArcMap from mxd with D&D Dock Window open previously

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#471]
Re-launching ArcMap from mxd with D&D Dock Window open previously causes Map Point to not to work.

Repro Steps:

1. From the Military Tools Toolbar
2. Open Addin Dock Window
3. Close ArcMap 
4. Rerun ArcMap **by double-clicking mxd** (see: https://github.com/Esri/military-tools-desktop-addins/issues/33)
5. Select map point tool on the Addin Dock Window
6. Tool does not activate

Related:
https://github.com/Esri/military-tools-desktop-addins/issues/33
https://github.com/Esri/visibility-addin-dotnet/issues/247
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/427

**Comment by csmoore** [comment]
Ready to QA from `Development\Commercial\MilitaryToolsForArcGIS\12-06-2017_1649`

**Comment by BobBooth** [comment]
Tested with ArcMap 10.5 and MT add-in built 4/20/18.
Works as designed.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/7239d53e-1659-4f48-94f5-680decf148d3)
Saved.
Reopened map, switched to Circle tab. Works as designed.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/23d0f432-1ef2-4862-a06d-d43e44121635)
Saved, reopened map, switched to Ellipse tab. Works as designed.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/6fb956aa-03c4-4fd0-b9c8-84acc22383e6)
Saved, reopened map, switched to Rings tab. Works as designed.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/6caf0210-91f1-46a0-8d04-4062b229b99f)
@dfoll

**Comment by BobBooth** [comment]
Submitted PR https://github.com/ArcGIS/solutions-defense-test-catalog/pull/130 for checklist test.

**Comment by dfoll** [comment]
- [x] Resources page
- [x] Defense What's New page
- [x] What's New section on homepage
