### ISSUE TITLE
Circle results jump between Radius and Diameter values.

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#474]
Environment:
Windows 10. ArcGIS Pro 2.1 build 10224
Using: Military Tools Single add-in installer. Military Tools for ArcGIS 2.0.

Steps to Repro:
1. With the add-in installed, open the Distance and Direction pane.
2. Click on the circle tab.
3. Make sure the From pull down is set to "Radius".
4. Click on the Map Point Tool.
5. Click on a point.
6. Move the mouse outwards, notice the behavior:
  - Behavior is smooth
 7. Click on the map again to finalize the circle.

8. Change the "From" pull down and change it to Diameter.
9. Click on the Map Point Tool.
10. Click on a point.
11. Move the mouse outwards, notice the behavior:
  - Behavior is choppy.
  - The circle bounces between what appears Diameter and Radius values.
  - The Radius/Diameter box values also jump between what appears to be Diameter and Radius Values.

**Comment by topowright** [comment]
Looking closer at this issue I think it is also tied with issue #475 the radius is not populating the distance parameter and it runs smooth. The other is updating the parameter and it is showing a lag from that updating happening.

**Comment by csmoore** [comment]
Should be addressed in #490 - ready for QA/QC

**Comment by topowright** [comment]
I have verfied that this is fixed using ArcGIS Pro 2.1 and Build 38
