### ISSUE TITLE
Radius measurement values not automatically populating

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#475]
Environment:
Windows 10. ArcGIS Pro 2.1 build 10224
Using: Military Tools Single add-in installer. Military Tools for ArcGIS 2.0.

Steps to Repro:

1. With the add-in installed, open the Distance and Direction pane.
2. Click on the circle tab.
3. Make sure the From pull down is set to "Diameter".
4. Click on the Map Point Tool.
5. Click on a point
6. Move the mouse outwards, notice the behavior:
  - The Radius/Diameter box should update as you move the mouse outward.

Repeat the same steps listed above, this time with the From pull down set to "Radius".
Notice the Radius/Diameter box values are not present.

Current behavior for Radius:
![2017-12-08_13-10-05](https://user-images.githubusercontent.com/3093940/33785275-21c7c054-dc19-11e7-8bc0-7b35fa0cfce0.png)

Current behavior for Diameter:
![2017-12-08_13-11-35](https://user-images.githubusercontent.com/3093940/33785328-6030061c-dc19-11e7-8af1-1a33cad71206.png)

**Comment by topowright** [comment]
#474 is also related to this issue.

**Comment by csmoore** [comment]
Should be addressed in #490 - ready for QA/QC

**Comment by lfunkhouser** [comment]
@ACueva Is there more information needed on this issue? This issue should have no dependencies. Issue https://github.com/esri/distance-direction-addin-dotnet/issues/474 was verified and is done.
