### ISSUE TITLE
Cursor location does not match circle diameter

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#476]
Environment:
Windows 10. ArcGIS Pro 2.1 build 10224
Using: Military Tools Single add-in installer. Military Tools for ArcGIS 2.0.

Steps to Repro:
1. With the add-in installed, open the Distance and Direction pane.
2. Click on the circle tab.
3. Make sure the From pull down is set to "Radius".
4. Click on the Map Point Tool.
5. Click on a point.
6. Move the mouse outwards, notice the behavior:
  - The mouse cursor matches the location of the outer circle
 
Perform the same steps listed above, this time change the pull down to "Diameter".  Notice the cursor does not match the location of the circle.

**Comment by ACueva** [comment]
Confirmed this also occurs at ArcGIS Pro 2.0.

**Comment by dfoll** [comment]
On Pro 2.1.0 with MT build 23 (5Mar) the feedback looks ok with Radius and Diameter
