### ISSUE TITLE
Range Rings Radial Support

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#477]
Currently we support the user to be able to create 180 radials, but is there a need for a user to create a radial every 1 degree?

**Comment by BobBooth** [comment]
@topowright - I don't know of a specific use case for radials every one degree, but unless it causes a problem, I don't see why we would cap it at something lower.

**Comment by lfunkhouser** [comment]
Closing the issue with As Designed. Please reopen if there is a use case for limiting the radials.
