### ISSUE TITLE
Stacking labels

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#478]
#### Background
the labels should be stacked for each feature instead of spaning across the feature. This current design makes it very hard to use the labels.  These labels should be the same way when implemented in ArcGIS Pro

#### Expected outcome
We want the ArcMap labels to follow the same patterns as ArcGIS Pro.

**Comment by lfunkhouser** [comment]
@topowright please provide more details to this issue. Does this affect all three applications - ArcMap, ArcGIS Pro and Web AppBuilder? Please add screenshots for clarification.

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/34750662-19765bba-f55d-11e7-8406-4e04e512af03.png)

**Comment by topowright** [comment]
@adgiles @kgonzago What do you guys think about this issue?

**Comment by adgiles** [comment]
@topowright Personally I don't think there is a problem with how the labels are displayed. For the labels on the circles where would you see the break occurring to put it onto two lines?

**Comment by kgonzago** [comment]
@topowright I agree with @adgiles on the fact that more detail is needed. Can you provide how you envision labels should be stacked for both lines and circles? Once we have more information, we'll get a better sense on how to proceed with implementation.

**Comment by topowright** [comment]
Closing this issue based on the current design implemented when we started using features instead of graphics.
