### ISSUE TITLE
Support for Dark Theme

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#482]
- [x] Distance Calculator text hard to read. Possibly just make it like the rest of the text
- [x] Properties dialog box for Save as
- [x] Properties dialog Coordinate dialog format

![image](https://user-images.githubusercontent.com/5488313/34039779-c9c09908-e145-11e7-83dd-4959dda86264.png)

**Comment by topowright** [comment]
Things are moving forward. Issues with the toggle buttons are being addressed.

**Comment by csmoore** [comment]
Current status: 

The dark mode changes are completed in [this branch](https://github.com/Esri/distance-direction-addin-dotnet/compare/csm/%23482-dark-mode)

However, the toggle (MapPoint) buttons don't seem to work reliably/correctly in Pro (Can't toggle off, switching tool doesn't turn off, etc.) making these difficult to test so looking into these issues now.

**Comment by csmoore** [comment]
The issue with the toggle buttons not toggling in Pro has also been resolved and this should be ready for QA/QC after https://github.com/Esri/distance-direction-addin-dotnet/pull/493 is reviewed/merged

**Comment by topowright** [comment]
This can now be tested.

**Comment by topowright** [comment]
Testing this I have found that our hover color for our buttons do not match the rest of the dark theme. When you hover over a button in ArcGIS Pro it is a gray color and ours is a blue. We will need to update this as well. @csmoore

**Comment by topowright** [comment]
Here is an example of how our buttons are different than the rest of ArcGIS Pro: 
![image](https://user-images.githubusercontent.com/5488313/36171676-6707255a-10b8-11e8-975e-f4ff55dfa810.png)

Talking with @csmoore he says that unless we seperate these two projects completely we will end up with this same issue. Also, he stated that if we try and overide any part of the style we will not be able to use the styles.  Currently we are overriding the sytles for ArcGIS Pro in some ways, but not sure what those examples are.  

@csmoore plesae add to where you feel like I have missed or did not give enough information.

**Comment by topowright** [comment]
Here is the difference in colors: 

![image](https://user-images.githubusercontent.com/5488313/36172192-f6c54b80-10b9-11e8-9b11-9d97c4f7869d.png)
