### ISSUE TITLE
Properties button on Distance and Direction support light and  dark theme

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#483]
![image](https://user-images.githubusercontent.com/5488313/34495092-74fdb754-efa8-11e7-86ee-5e1c715bb06b.png)

The desired result would be a properties button that supports dark and light theme

**Comment by csmoore** [comment]
Addressed in #484 

Screen shots now (Dark / Light / ArcMap):

![image](https://user-images.githubusercontent.com/3090809/34572595-c26d944e-f13f-11e7-8fd3-7cfac513c29d.png)

![image](https://user-images.githubusercontent.com/3090809/34572662-f18b7fd4-f13f-11e7-8861-035c76173df9.png)


![image](https://user-images.githubusercontent.com/3090809/34572642-dfefc668-f13f-11e7-88a3-a69c2698fdb5.png)

**Comment by ACueva** [comment]
Verified from Jenkins MT 3.0 Build 76
