### ISSUE TITLE
Enhancement - Escape key should clear operation

### ISSUE THREAD

**Issue by dhagens** [Esri/distance-direction-addin-dotnet#49]
As using a tool in ArcMap, the escape key should cancel the current operation

**Comment by mfunk** [comment]
Testing this one on Build 1057 in ArcGIS Pro 1.4. So what happens now is the Escape key switches focus to Pro's **Explore** tool (pan/zoom). The effect is that the current draw operation is suspended. For example If I choose the *Lines* tab, select the Map Point tool to draw a line, click a starting point on the map, I can then select Esc, and the rubber-band feedback line just freezes in place and I get the Explore tool's clicking-finger icon:
![image](https://cloud.githubusercontent.com/assets/3093182/21691329/f342c30a-d32c-11e6-9d7a-a08efbd7461f.png)

Clicking around with the Explore tool doesn't change or un-freeze the line. I can actually click back on the Map Point button on the Lines tab, and continue creating my line that I started before clicking Escape.

**Comment by rjones0** [comment]
I could not find references to capturing the Escape key in the code, and therefore assumed that the current behaviour is default, and that the hook to capture the Escape key press was required. I have implemented the hook in this commit:

https://github.com/rjones0/distance-direction-addin-dotnet/commit/5a4137038b254ca1f7bfd8ea05128201d13fceee

At the moment it just calls Reset(true) on the tool in lieu of whatever functionality we might choose to implement based on the stage at which Escape is clicked (e.g. Map Tool enabled but no point added, Map Tool enabled and first point added etc.). I will request a review on the hook before proceeding any further.

**Comment by rjones0** [comment]
PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/308

**Comment by rjones0** [comment]
PR with final part of required code i.e. take appropriate action when Escape key is pressed: https://github.com/Esri/distance-direction-addin-dotnet/pull/310

**Comment by rjones0** [comment]
@dhagens as the originator of the case please review and close if fix is satisfactory.

**Comment by dhagens** [comment]
@rjones0, @kgonzago, @NatalieCampos, @topowright 

A few issues that I have found when testing this fix:

- You may be aware of this but Jenkins is no longer building the tools.  Looks like they haven't been built since 1/20

- None of the tools appear to be working from the Military Tools toolbar.  I cloned the military-tools-desktop-addins repo and tested from there and none of the tools capture input when the mappoint tool is enabled.
- To test this, I cloned the D&D repo which has all of the latest changes.
- The fix for this issue should be made in both ArcMap and Pro.  It appears that only a fix was made for Pro and not ArcMap
- Ellipse tool is not working.  You can only draw the Major axis, not the minor.
- Rings fix for the Escape key is not working properly.  The 'Number of Rings' should be set back to 0 when the Escape key is hit.  It currently lists the number of rings that were created, then when starting a new set of Rings, the Number of Rings is incorrect.

**Comment by rjones0** [comment]
@dhagens ok thanks for testing. I thought that the V - Pro 1.4 label meant the fix was required in Pro only, but I guess the label just means the version in which the issue was detected. I will add the fix to ArcMap also.

Ellipse is working fine for me - enable tool, click once to create point, drag out to set major axis, click again to fix that value, drag to set minor axis, click to create feature:

![image](https://cloud.githubusercontent.com/assets/24588999/22839235/817c0a6e-efc0-11e6-9866-ab472bb341d5.png)

Will look at setting Rings to zero on Escape. I have a feeling there was an issue that stopped me doing this as I think otherwise I wouldn't have missed it, but will confirm.

**Comment by rjones0** [comment]
The default value for Number of Rings appears to be 10.

**Comment by dhagens** [comment]
@rjones0, I tested the Ellipse tool again and it does appear to be working correctly.  The Number of Rings should be set back to 0 when in Interactive mode.  The other issue I've found is that the tools are not all consistent.  On some the Escape key turns off the MapPoint tool, on others the tool remains active.  This should be consistent across all of the tools.

**Comment by rjones0** [comment]
Before a point has been created, pressing Escape should deactivate the tool. After a point has been created but the feature not completed, pressing Escape should clear the point and any preview graphic but leave the tool active. Is it not behaving like this?

**Comment by rjones0** [comment]
Ok so it's not working properly for Ellipse, but others look ok to me. Will fix Ellipse.

**Comment by dhagens** [comment]
Correct, looks like Ellipse is the only one not working properly.  Also noticed that the MapPoint tool does not function properly when moving from tab to tab.  For example, if you have the MapPoint tool enabled in the Line tab and move to the Circle tab, when you go back to the Line tab the tool looks as if it is still enabled, but it actually isn't.  I'm not sure if this was broke before or something related to these fixes.

**Comment by rjones0** [comment]
@dhagens I logged #301 for some behaviour involving switching tabs that didn't look quite right. Will see whether my fix has influenced this at all. Thanks!

**Comment by rjones0** [comment]
@dhagens this should now be fully fixed. Please check and close if possible. The switching tabs issue #301 is still present.

**Comment by rjones0** [comment]
As described in #317, automated test cannot be written for this issue therefore manual testing will be required with each release.

**Comment by rjones0** [comment]
@dhagens I am going to go ahead and close this issue as I am confident it is resolved.

**Comment by topowright** [comment]
I have verified that the escape key now is honored in stopping the graphic.
