### ISSUE TITLE
Create the Resources tab for DD 

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#500]
Currently our release notes for this Solutions are not up to date. 
Our release notes now look like this: 
http://solutions.arcgis.com/defense/help/gridded-reference-graphic/resources/release-notes.htm

- [x] Add the resources tab to the solution
- [x] Add the known issues section
- [x] Add the contents section
- [x] Update the structure of the the release notes in CMS
- [ ] Break issues into ArcMap and ArcGIS Pro 
- [ ] remove the readme from the Solutions folder on Defense Solutions: 
https://github.com/ArcGIS/solutions-defense/tree/dev/DistanceAndDirection/Resources

**Comment by topowright** [comment]
@dfoll are we going to update the style of our release notes or keep them the same? I created this epic to track all the known issues that we have been able to address associated to our release notes being updated.

**Comment by topowright** [comment]
These release notes should look like this: 
http://solutions.arcgis.com/defense/help/military-features/resources/release-notes.htm

**Comment by ACueva** [comment]
@dfoll has created the Resources tab for DD.  I'll be populating the rest of the checklist item content.

**Comment by ACueva** [comment]
I've added the Known Issues and Issues addressed section.  Document is not complete. Will work with @dfoll to populate items pertinent to April 2018 release.

**Comment by ACueva** [comment]
April 2018 items have been added.  This includes the search URL for issues addressed.  The URL points to the "r-April 2018" label. https://github.com/Esri/distance-direction-addin-dotnet/issues?q=label%3A%22R+-+April+2018%22+is%3Aclosed

**Comment by ACueva** [comment]
FYI @dfoll @topowright I believe this issue is ready for CMS QC review.
