### ISSUE TITLE
Ambiguous Coord Dialog when using Map Point Tool in GCS Map

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#503]
With the changes in PR #498 - the addin is now showing the Ambiguous Coordinate Dialog while using the Map Point Tool (in both ArcMap and Pro) **if**:

1. the Coordinate Type is set to Default Map Coordinate. 
2. the data frame is using GCS (ex. set data frame to WGS 1984)

The Coordinate was "37.5 -122.8" so does not seem to be ambiguous (so that should be investigated). But we should also prevent this dialog from being shown when the MapPoint tool is being used

![image](https://user-images.githubusercontent.com/3090809/36398402-eaee6afa-1594-11e8-9205-1be03e34d498.png)

Clicking "Don't show me this message again" is necessary to use the tool, but the dialog will be shown again on the next run since the setting does not seem to be saved.

(UPDATE) Additional note - this same issue is also causing several of the unit tests to fail:

![image](https://user-images.githubusercontent.com/3090809/36399461-fee75ec2-1599-11e8-9dd1-d7b3518c19ce.png)

**Comment by csmoore** [comment]
Moving this into next sprint (hopefully this is OK) since it is something that broke while fixing #218, #220, #222

**Comment by csmoore** [comment]
Addressed in #517 and https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/481

Can be QA/QC'd after merge (note: both manual and automated tests)

**Comment by BobBooth** [comment]
Updated checklist test.
PR: https://github.com/ArcGIS/solutions-defense-test-catalog/pull/92

**Comment by lfunkhouser** [comment]
Issue cannot be "done" until the tasks are completed. @BobBooth if you tested this issue and verify that it has been fixed, please add a comment of how this item moved from the Sprint backlog to done, add the closing E-label, and remove the yellow task labels that you completed.

**Comment by BobBooth** [comment]
Completed manual checklist testing, following the steps here:
https://github.com/ArcGIS/solutions-defense-test-catalog/blob/master/Tests/Distance-Direction_ArcMap.md
Issue 503 Check
https://github.com/Esri/distance-direction-addin-dotnet/issues/503 Start a new map, set the data frame coordinate system to WGS84, add a basemap.

 Enter the following coordinate in the Starting Point box on the Line tab: 37.5 -122.8
You should not get an "ambiguous coordinate" warning.
 Enter the following coordinate in the Ending Point box on the Line tab: 37.5 -125
The line should be created.
 Enter the following coordinate in the Starting Point box on the Line tab: 37.5 -122.8
You should not get an "ambiguous coordinate" warning.
 Click the Map Point tool and click to create another line from that start point.
The line should be created.
-=-=

Did not get warning messages, coordinates were accepted, lines were created as desired.

**Comment by lfunkhouser** [comment]
This issue is back with the latest version of dev

**Comment by csmoore** [comment]
This is a new issue discoved while testing #503 - Opened #667 with the specifics of this new issue.
