### ISSUE TITLE
Ellipse labels typographical issues for Distance and Direction widget

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#506]
When I create ellipses in the widget (WAB DE 2.8 2/20/18 snapshot, latest branch copy of @kgonzago for widget)  I am seeing logic implemented to note semi or full lengths, but there are some typos in the labels.
Extra colons 

Full construction method - labels have extra : symbol after Major Axis and Minor Axis
Semi construction method- labels have extra : symbol after Major Axis and Minor Axis, un-matched parentheses for Radius case.
![image](https://user-images.githubusercontent.com/3801392/36442505-06c2e710-1644-11e8-9a9b-3bd50b76897c.png)

**Comment by kgonzago** [comment]
@BobBooth: these issues were fixed and pushed to this [branch](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/tree/kevi2741-distance-and-direction)

**Comment by BobBooth** [comment]
@kgonzago - I've tested these, they're fixed.
image  upload is failing for me, but I took screen shots.

**Comment by BobBooth** [comment]
Also. tested in WAB 2.7 in Firefox browser, for variety.

**Comment by kgonzago** [comment]
@BobBooth Thanks for testing,

**Comment by BobBooth** [comment]
![image](https://user-images.githubusercontent.com/3801392/36503521-633522ba-171b-11e8-8199-cf101b1a1399.png)
![image](https://user-images.githubusercontent.com/3801392/36503544-6e0efe54-171b-11e8-8786-6fc1d3b3d8f3.png)

**Comment by dfoll** [comment]
I looked at this as well, I second what @BobBooth said, I believe this can be closed
