### ISSUE TITLE
Origin and Cumulative input boxes values persist when deleted Distance and Direction widget

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#507]
There seems to be no way to delete distance values entered in the Origin/Cumulative methods of creating rings. Deleting the text gets rid of it temporarily, but pressing Enter or clicking in another box then restores the value.
![image](https://user-images.githubusercontent.com/3801392/36442738-ba1e3f26-1644-11e8-9331-42939ca1e4f2.png)

Tested in daily build (2/20/18 of Web App Builder DE and the latest widget downloaded as a zip from the arcgis-webappbuilder-kevi2741-distance-and-direction branch of the repo.

**Comment by kgonzago** [comment]
This was fixed in this [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11837/commits/c343ed37bc0cf1981a681f3af83ffcddd5032949)

**Comment by dfoll** [comment]
I am no longer seeing the behavior @BobBooth logged, I type a value, press enter to get it to add. Delete it using the keyboard press enter, it stays gone. Using the delete button also works. I believe this can be closed.
