### ISSUE TITLE
Origin and Cumulative input boxed usability issues Distance and Direction widget

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#508]
When I'm adding values to this list, I click in the "Double click to add value" box, and the text is not selected, so I have to manually select (or double-click again) and delete it before entering a value.
Would be nice for text to disappear on click in box.
![image](https://user-images.githubusercontent.com/3801392/36493688-2c6cdeac-16fe-11e8-8525-3a71da1390d7.png)

Also, after entering a value, pressing Enter does not commit the value and move on to the next box (or next item in the GUI). Would be nice for Enter key to commit value. Might also be nice for it to instantiate another input box that would disappear if you clicked outside of it without entering a value.

Another, more serious issue reported as: https://github.com/Esri/distance-direction-addin-dotnet/issues/507

**Comment by BobBooth** [comment]
@adgiles @kgonzago  a couple of usability issues.

**Comment by kgonzago** [comment]
@BobBooth The [SimpleTable](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/blob/develop/client/stemapp/jimu.js/dijit/SimpleTable.js) dijit the D&D widget uses is a core WAB dijit. I will report your findings as an issue in Devtopia.

**Comment by kgonzago** [comment]
@BobBooth Can you add screenshots to this issue?

**Comment by BobBooth** [comment]
@kgonzago - done.

**Comment by kgonzago** [comment]
Thanks @BobBooth

**Comment by kgonzago** [comment]
[Issue](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/11866) submitted in Devtopia.

**Comment by adgiles** [comment]
@kgonzago are you sure we cannot put a onclick event on the row to clear the value if it is still set to ‘Double click to change value’

**Comment by kgonzago** [comment]
@adgiles The watermark being displayed as actual text after a user clicks the textbox is an issue WAB team needs to address. Also, it should be normal behavior to accept a value after the `Enter` key is pressed by the user. Agreed, we can listen to those events and implement the workaround behavior but both these issues should be standard behavior from the SimpleTable dijit. An issue was submitted. Let's see how the WAB team addresses it. If they can't apply a fix in time for 6.1, we'll then just put in the workaround logic.

**Comment by adgiles** [comment]
The ‘watermark’ is actually the value of the cell set when the new row is added

**Comment by kgonzago** [comment]
Ah yes, I see it on this [line](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/blob/develop/client/stemapp/widgets/DistanceAndDirection/views/TabRange.js#L628). I'll edit the Devtopia issue to reflect that.

**Comment by kgonzago** [comment]
After discussing this further, let's take care of this ourselves. I doubt the WAB team will have time to fix these minor issues in time for 6.1. @adgiles Do you have time to look into this?

**Comment by adgiles** [comment]
Yep, can you send me over the latest version of the widget by email

**Comment by adgiles** [comment]
@BobBooth changes made as per your suggestion, @kgonzago is moving code up to Devtopia

**Comment by dfoll** [comment]
enter now commits a value. the watermark text is removed when you single click on the text box  to insert a value. I believe this can be closed
