### ISSUE TITLE
Distance and Direction Circle tool causes ArcMap/Pro go unresponsive click outside basemap extent

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#512]
_From @BobBooth on September 26, 2017 20:39_

Testing DD (2.1.1) Circle tool on ArcMap 10.6 (8184), had added the Topographic Basemap from AGOL.
Clicked add point tool, added a couple of circles by clicking a point on the map, then clicking to define the radius.
Clicked outside of the extent of the basemap. A point is added to the display.
Clicked back on the basemap.
ArcMap become unresponsive. 
![image](https://user-images.githubusercontent.com/3801392/30883062-0dadfca6-a2d9-11e7-8bed-ca0d72328135.png)
![image](https://user-images.githubusercontent.com/3801392/30883073-143725fc-a2d9-11e7-8304-a85c135918fe.png)
![image](https://user-images.githubusercontent.com/3801392/30883088-1a8d1678-a2d9-11e7-9031-4441db4537fa.png)

_Copied from original issue: ArcGIS/solutions-defense#437_

**Comment by lfunkhouser** [comment]
_From @BobBooth on September 26, 2017 20:52_

This problem *does not* affect the interactive tools for adding lines. They seem perfectly happy if you click outside of the basemap extent, and add a line from that (hypothetical?) location if you click somewhere in the basemap extent for the second point.
The Ellipse tool and the  Rings tools both do suffer from this problem.
![image](https://user-images.githubusercontent.com/3801392/30883699-032048f0-a2db-11e7-8be3-d5b706bb5579.png)

**Comment by lfunkhouser** [comment]
_From @BobBooth on September 29, 2017 18:35_

This problem exists in the tools in the combined Military Tools add-in as well.

**Comment by lfunkhouser** [comment]
_From @kgonzago on January 18, 2018 14:4_

@BobBooth I'm looking into this issue. Does this issue occur in 10.5+ as well?

**Comment by lfunkhouser** [comment]
_From @kgonzago on January 18, 2018 14:53_

FYI: I was able to reproduce this issue in ArcMap 10.5.

**Comment by lfunkhouser** [comment]
_From @kgonzago on January 22, 2018 18:51_

Fix is in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/491)

**Comment by lfunkhouser** [comment]
_From @kgonzago on January 22, 2018 19:15_

@BobBooth can you verify when you have a chance?

**Comment by lfunkhouser** [comment]
_From @kgonzago on January 22, 2018 21:0_

I added a step to build MT Desktop add-ins in the [3.0 Build](http://soljenkins:8080/job/MT-3.0/) and encountered [exceptions](http://soljenkins:8080/job/MT-3.0/81/console). Tagged this issue as ***impeded*** since the slave associated with the build does not have ArcObjects SDK installed. AO SDK [issue](https://github.com/ArcGIS/defense-solutions-jenkins/issues/100) has been logged.

**Comment by lfunkhouser** [comment]
_From @topowright on January 24, 2018 0:11_

We need to address this with the new build of Military Tools for ArcGIS .

**Comment by csmoore** [comment]
This was fixed in PR #491 - removing dev label and ready for QA/QC

**Comment by BobBooth** [comment]
This is working correctly.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/92d69eb9-b85
f-4f93-a235-5882d2bbc4d0)

**Comment by BobBooth** [comment]
Added test to cover this to my PR on DD checklist test.
@ACueva  @topowright

**Comment by csmoore** [comment]
Also note that in PR #528 - @garys-esri found a similar issue in Pro so please test in both ArcMap and Pro:

Repro steps:
"To test this behavior and this fix, build the add-in, deploy in ArcGIS Pro, and use the Circle tab of the Distance and Direction add-in to draw a circle on a 2D map. When you move the mouse west of -180 degrees longitude, ArcGIS Pro crashes without this fix. With the fix, the circle stops drawing and the distance value stops changing until the mouse is back on the map."

**Comment by garys-esri** [comment]
That PR number is #538, not 528.

**Comment by topowright** [comment]
This is still an issue in ArcGIS Pro being that we do not get the same message box that we get in ArcMap
##### Steps to Reproduce: 

1. Open ArcGIS Pro
2. Add a map
3. Open the DD Tool
4. Select the circle tab
5. Drop a point outside the map
6. Enter in a size of the circle
7. Hit enter

Here is my results:
![image](https://user-images.githubusercontent.com/5488313/38778444-a6369b1c-406e-11e8-95ad-bc8e3209315d.png)

**Comment by csmoore** [comment]
Addressed in PR #546 

Should look like this now in both ArcMap & Pro - and reset if 1st point out of bounds:

![image](https://user-images.githubusercontent.com/3090809/38873833-b2fd991a-4224-11e8-9fdb-066b57cf1bb8.png)

![oobam](https://user-images.githubusercontent.com/3090809/38873899-d976876e-4224-11e8-8aba-f3b7e3846269.PNG)

**Comment by BobBooth** [comment]
Tested latest build MT (4/17/18) Circle tool in ArcMap 10.5.  Circle tool is fixed. 
Tested on Pro 2.1, tool works the same way, gives "out of bounds" error message.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/40c04126-d1da-46a8-ae85-fd3933329aac)

**Comment by BobBooth** [comment]
@dfoll  @ACueva  I believe this can be moved to Done, once the two checklist test PRs are merged.
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/121
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/122

**Comment by ACueva** [comment]
PR https://github.com/ArcGIS/solutions-defense-test-catalog/pull/121 and https://github.com/ArcGIS/solutions-defense-test-catalog/pull/122 reviewed and merged.

Moving issue to Done.

**Comment by topowright** [comment]
@ACueva I think this needs a verified tag on this item. Can you place a verified tag on this?

**Comment by topowright** [comment]
Awesome.
