### ISSUE TITLE
D&D Widget - CSS issues with Dart Theme and Dark Dashboard Theme 

### ISSUE THREAD

**Issue by adgiles** [Esri/distance-direction-addin-dotnet#516]
Before the code was moved into the core build we handled the css for the Dart Theme and Dashboard theme within the widget. These have been removed and need to be handled within the relevant theme css files.

For example: Number Input Boxes in dashboard theme:

![capture](https://user-images.githubusercontent.com/3740334/36604738-7d5deef0-18b6-11e8-9136-4b8fb509c096.PNG)

And various icon issues in Dart theme:

![capture1](https://user-images.githubusercontent.com/3740334/36604755-8a58b3d8-18b6-11e8-8474-1b4c2c1ab96a.PNG)

**Comment by lfunkhouser** [comment]
@adgiles Is this an issue we can address or does this need to be addressed by the WAB team?

**Comment by adgiles** [comment]
@lfunkhouser it is for our team to complete. Work has been done and pushed up to Devtopia in this PR https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11973

**Comment by adgiles** [comment]
@topowright @dfoll @ACueva

now showing in the daily build (01 Mar 18), good to test

**Comment by BobBooth** [comment]
This looks like it is behaving correctly now.

**Comment by dfoll** [comment]
Looked at these as well with Bob in Dart theme and Dashboard. The fixes look good, need to get the checklist test to incorporate these two themes and Firefox, Chrome, and IE.

**Comment by dfoll** [comment]
I believe this can be moved to Done. Just want some clarification on the G-QC Release label. I don't think it needs to be on this item, but don't want to remove it if i'm just missing something.
