### ISSUE TITLE
Inconsistent naming of buttons on the Line tab for the widget

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#520]
When creating lines from known coordinates, using "From: Points" the tool used to create the Start Point is called "Draw Line" but the tool used to create the End Point is called "Add Point" both should be called "Add Point"

**Comment by lfunkhouser** [comment]
@adgiles please add an estimate to this issue.

**Comment by adgiles** [comment]
Fixed, pushed up to Devtopia in this PR https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11973

**Comment by adgiles** [comment]
@topowright @dfoll @ACueva

now showing in the daily build (01 Mar 18), good to test

**Comment by dfoll** [comment]
verified fixed on the daily snapshot

If this needs tested explicitly on devext we need to move this back. Was not able to text on devext because I could not log in because I could not figure out what the password is.

**Comment by ACueva** [comment]
@topowright Still impeded due to this topic being checked out.
![2018-03-09_10-26-09](https://user-images.githubusercontent.com/3093940/37223096-51388dfc-2384-11e8-9eaf-12754bec49a2.png)

**Comment by ACueva** [comment]
Doc changes made and checked back in. FYI @dfoll 
![2018-03-09_11-35-37](https://user-images.githubusercontent.com/3093940/37226205-08327b18-238e-11e8-817b-7900dbdd0771.png)

**Comment by dfoll** [comment]
verified it's fixed on docdev ... removing G - QC Doc. changes should appear in the portal doc overnight
