### ISSUE TITLE
Typo on the Circle tab for the widget and disappearing text box

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#521]
On the circle tab for Distance and Direction there is an issue with the label for the "Center Point" input box. Until you press Enter to input coordinates, the label reads "Center Point/label>" Once you press the enter key and it has to parse out what coordinate type it is, the text box disappears You can also get this behavior just by changing the input format. For example, change it to DD, which it was already displaying as.

1. Refresh your browser window.
2. Click the Circle tab. Notice the label for the enter point input box.
3.  Click the Draw Circle tool as many times on the map as you want, it does not change
4. Paste in coordinates, and the text box disappears from the widget
5. Refresh the browser note the incorrect label. Do not enter coordinates.
6. Click the Input Format button. 
7. Do not change anything, just leave it as DD and click OK
8. Center point text box disappears.

![image](https://user-images.githubusercontent.com/5322669/36644643-22597454-1a12-11e8-848d-4ce1f6b449ed.png)
incorrect label after using the draw circle tool

![image](https://user-images.githubusercontent.com/5322669/36644659-68925a44-1a12-11e8-85d2-4a437c063bca.png)
tried pasting in coordinates after using the draw circle tool

**Comment by dfoll** [comment]
@adgiles

**Comment by dfoll** [comment]
@lfunkhouser

**Comment by dfoll** [comment]
I only noticed this on the Circle tab

**Comment by adgiles** [comment]
@dfoll Within the TabCircle.html on line 15 there is a < missing on the closing tag for label, the line should read:

<label data-dojo-attach-point="coordInputLabel">${nls.centerPointLabel}**<**/label>

not

<label data-dojo-attach-point="coordInputLabel">${nls.centerPointLabel}/label> 

@kgonzago can you update the repo on devtopia

**Comment by kgonzago** [comment]
Devtopia updated with this [PR](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11921)

**Comment by dfoll** [comment]
The PR in devtopia is merged. Used the 2.8 snapshot from 0400 this morning and I am not seeing this behavior any longer
