### ISSUE TITLE
Temporary line disappears and becomes unresponsive after clicking "Clear Graphics"

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#522]
Reproduced on the following environment:
ArcMap 10.6
Distance and Direction individual addin.
![2018-02-26_13-39-10](https://user-images.githubusercontent.com/3093940/36697720-c6d83e76-1afc-11e8-98d9-5158ca73a3df.png)

Steps to reproduce:
From the Line tab, paste the following:
Starting Point: 34.73N 116.948W
Ending Point:  60.236869N 24.895304E

Notice the temporary line that is created:
![2018-02-26_13-57-50](https://user-images.githubusercontent.com/3093940/36697817-0c528da8-1afd-11e8-949e-0cc1d0fa710d.png)

Press Enter.
The line should turn red.
![2018-02-26_13-58-22](https://user-images.githubusercontent.com/3093940/36697868-1f4fdffa-1afd-11e8-9c3c-231468225f63.png)

Enter starting point and ending point again.
Starting Point: 34.73N 116.948W
Ending Point:  60.236869N 24.895304E
![2018-02-26_13-59-25](https://user-images.githubusercontent.com/3093940/36697925-44b87464-1afd-11e8-8c6d-c52623dfcedb.png)

Click clear graphics.
The temporary line goes away.

Try modifying the starting or ending point text box, the line will appear momentarily and then disappear.

The work-around is to delete the contents of the starting and ending point and entering the content again.

**Comment by lfunkhouser** [comment]
This is non-reproducible. Features are being drawn instead of graphics. Clicking the Clear button will clear the features from the map.
