### ISSUE TITLE
Crash when entering the same value for Starting Point and Ending Point

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#523]
Make sure you have a basemap set.

From the line tab:

Enter the following:
Starting Point: 34.73N 116.948W
Ending Point: 34.73N 116.948W
Press Enter.

ArcMap will then crash.

**Comment by ACueva** [comment]
FYI @lfunkhouser.  Unsure about showstopper tag, it is a crash, just not sure how likely a customer is to do this.

**Comment by dfoll** [comment]
if this did not crash/hang indefinitely, I would say we leave it. I would like for us to work with the rest of the team to figure out what best way to avoid the crash, my instinct is just a validation that will tell the user they have entered the same point twice, before the tool even attempts to run, but I'm just one opinion, let's discuss in the next time the team have a forum where this is appropriate discussion.

**Comment by dfoll** [comment]
@kgonzago has shown me the fix he will be submitting for the PR for this issue. What happens is the user enters a starting point, if the user enters the exact coordinates for the ending point, there is automatic validation of the values and the ending point box is highlighted red. The highlighted box has a tool tip that you can click on that informs the user that they should enter different starting and ending points. If the user does not change one of the values, and tries to proceed, nothing happens upon pressing enter. This does not count as the verification for this issue. This issue still needs to verified after the PR has been submitted and merged.

**Comment by dfoll** [comment]
used build 31 (the number assigned when it is on ....\defensesolutions) to verify this is fixed in ArcMap and works as described above.
