### ISSUE TITLE
Update Distance & Direction Widget based on UI Feedback on from WAB Dev team

### ISSUE THREAD

**Issue by kgonzago** [Esri/distance-direction-addin-dotnet#525]
We need to incorporate the suggested changes from the UI/UX lead from WAB team. 

Changes are embedded in these zips:
1. [icons (1).zip](https://github.com/Esri/distance-direction-addin-dotnet/files/1763403/icons.1.zip)
2. [Distance and Direction (1).zip](https://github.com/Esri/distance-direction-addin-dotnet/files/1763405/Distance.and.Direction.1.zip)

Actions needed to complete this issue:
- [x] Review changes
- [x] Fold in changes
- [x] Test changes
- [x] Push to Devtopia

**Comment by lfunkhouser** [comment]
@kgonzago you added the QC Verify (Automated) label. Is there an automated test being created?

**Comment by lfunkhouser** [comment]
@adgiles @kgonzago What is the level of effort associated with the changes?

**Comment by adgiles** [comment]
Dev effort complete, pushed up to Devtopia in this PR https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11973

**Comment by adgiles** [comment]
@topowright @dfoll @ACueva

now showing in the daily build (01 Mar 18), good to test

**Comment by dfoll** [comment]
Step 6 of "Create ellipses interactively" needs updated to say something to the effect of "Use the Draw Ellipse tool to designate the ellipse center."

**Comment by dfoll** [comment]
Looks good.
