### ISSUE TITLE
Distance and Direction holds on to previous coordinate system, bad results

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#527]
- If you open ArcMap
- open Distance and Direction add-in 
- add a basemap (sets the data frame to Web Mercator)
- change the data frame to WGS84,

 the add-in seems to be mis-handling the current coordinate system for line construction. 

- Create a line interactively.
- Add two points in different hemispheres.
- The line is labeled plausibly, but the resulting feature is invisible unless you zoom in many times to the center of the label.
Using the ArcMap measure tool, the distance I got in my test case is 171 meters.
![image](https://user-images.githubusercontent.com/3801392/36748148-fcac0c62-1bc4-11e8-8f85-0d1d6b240f05.png)

ArcMap 10.6.0.8321 
DD 2.2.0.26

**Comment by BobBooth** [comment]
@csmoore @kgonzago - I just found this while setting up to do a checklist test for ttps://github.com/Esri/distance-direction-addin-dotnet/issues/503
I feel like I've seen this before, but didn't see it in the issues.

**Comment by csmoore** [comment]
@BobBooth - you are correct this is a previous/known issue (with all of the addins) - recorded here: https://github.com/Esri/visibility-addin-dotnet/issues/248 - but a good time to see if there is any progress on this

**Comment by BobBooth** [comment]
@csmoore - thanks, I didn't think to look in Visibility.

**Comment by BobBooth** [comment]
If you set the coordinate system to WGS84 before adding the basemap, the tool works as expected.
![image](https://user-images.githubusercontent.com/3801392/36749637-58eb96ec-1bc9-11e8-8f36-d8dac90c80b5.png)

**Comment by topowright** [comment]
We need to understand if this happens with LInes, Circles, Ellipses and Rings.

**Comment by topowright** [comment]
@saip I am able to replicate this issue with ArcMap 10.7 and ArcMap 10.6.1

**Comment by topowright** [comment]
Currently multiple users are not able to replicate this issue. @lfunkhouser can you take a closer :eyes:

**Comment by BobBooth** [comment]
This appears to be working correctly now. Tested switching between Web Mercator and WGS84 Geographic, was able to draw lines, circles, ellipses in ArcMap 10.3.1 with the 1/7/19 build of Military Tools.

**Comment by kgonzago** [comment]
After more testing of this issue, here are the versions that work and don't:

Works in:
1. 10.3.1
2. 10.4
3. 10.5

Does not work in:
1. 10.5.1
2. 10.6
3. 10.6.1

**Comment by kgonzago** [comment]
FYI @lfunkhouser, further discussions are needed to properly handle this issue.

**Comment by lfunkhouser** [comment]
Add workaround documentation for 10.5.1-10.6.1 for this release. Issue will be addressed for next release.

**Comment by BobBooth** [comment]
Added workaround sentence to DD and MT Resources doc.

**Comment by BobBooth** [comment]
Moving from In Progress to March release backlog, because the work-around instructions have been added to the doc for January release.  We will look at fixing the actual problem in 10.5.1+ in the March release.

**Comment by csmoore** [comment]
This issue is resolved with the released addin on 10.7.1.

This issue was similar to https://github.com/Esri/visibility-addin-dotnet/issues/327 , 
https://github.com/Esri/visibility-addin-dotnet/issues/327#issuecomment-516572086 but no changes were needed to the D&D addin.

**Comment by dfoll** [comment]
For our supported range of versions (10.4.1-10.7.1) I only found this to be reproducible on 10.6-10.6.1. Added the specific version number to the known issue.

- [Distance and Direction October Resources](https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/october-2019-distance-and-direction.htm)
- \DefenseSolutions\DistanceAndDirection\October2019\Dev\104\
- [Military Tools October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\328\

**Comment by dfoll** [comment]
|ArcMap Version|Military Tools Version|Reproducible|
|---|---|---|
|10.4.1|3.5/317| |
|10.4.1|3.5/317| |
|10.4.1|3.5/317| |
|10.4.1|3.5/317| |
|10.4.1|3.5/317| |
|10.4.1|3.5/317| |
|10.4.1|3.5/317| |

**Comment by dfoll** [comment]
Ready to qc the doc and move to done

**Comment by csmoore** [comment]
Doc verified (D&D 105, MT 329) :

1. Distance and Direction October Resources
 
![image](https://user-images.githubusercontent.com/3090809/62391190-25e0ea00-b532-11e9-80d3-e0a6e0ee5120.png)

2. D&D pdf:

![image](https://user-images.githubusercontent.com/3090809/62391944-237f8f80-b534-11e9-90fe-bb684e9ce393.png)

3.  Military Tools October Resources
 
![image](https://user-images.githubusercontent.com/3090809/62392014-5033a700-b534-11e9-97ad-11ed25e42c50.png)

4. MT pdf:

![image](https://user-images.githubusercontent.com/3090809/62391898-077bee00-b534-11e9-91dd-60162d285cc8.png)
