### ISSUE TITLE
Distance and Direction - Rings tab misalignment

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#528]
https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/11960

Distance and Direction widget
Rings tab

On the rings tab there are four options to create rings that are accessed by switching the value in the "Type" drop-down list.  Dialog UI elements do not stay aligned when switching between the four options.

"Interactive", "Cumulative", and "Origin" UI elements all appear to be center-aligned on the dialog. "Fixed" UI elements appear to be left-aligned.

1. Open widget
2. Click the Rings tab
3. Select "Interactive" as the type.
4. Select "Fixed" as the type.
**_note the shift of all UI elements when switching between the two_**
All four options should be aligned the same.

![image](https://user-images.githubusercontent.com/5322669/36754410-bb16486e-1bbd-11e8-9ab6-7581fd1642d8.png)

![image](https://user-images.githubusercontent.com/5322669/36754422-c57d7930-1bbd-11e8-902f-634631b369fd.png)

**Comment by dfoll** [comment]
@kgonzago @adgiles

**Comment by adgiles** [comment]
@dfoll I will fix this as part of the CSS changes that are required from the Dev Team UI Feedback (https://github.com/Esri/distance-direction-addin-dotnet/issues/525) and issue https://github.com/Esri/distance-direction-addin-dotnet/issues/516

**Comment by adgiles** [comment]
Fixed, pushed up to Devtopia in this PR https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/pull/11973

**Comment by dfoll** [comment]
- verified UI elements are all aligned the same using the daily snapshot.

If this needs tested explicitly on devext we need to move this back. Was not able to text on devext because I could not log in because I could not figure out what the password is.
