### ISSUE TITLE
Drawing ellipse, circle, or ring graphics across the International Date Line results in confusing label placement

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#533]
ArcMap 10.6.0.8321 Military Tools 3.0 build 23 (5Mar)
ArcMap 10.6.0.8321 Distance and Direction 2.2.0.31

When creating ellipses/circles/rings across the International Date Line, the label is placed, centered between the two "pieces" of the graphic instead of being tied to a center point.

![image](https://user-images.githubusercontent.com/5322669/36995232-5ce5b824-2068-11e8-9fc1-7ce11956f462.png)
![image](https://user-images.githubusercontent.com/5322669/36995744-be0adc82-2069-11e8-9b8a-c90060b304ad.png)
![image](https://user-images.githubusercontent.com/5322669/36996632-1d7102bc-206c-11e8-8f95-7bad33c0f0a5.png)

This becomes particularly confusing if you have an ellipse/circle/rings that has a center point based along the same line of latitude that does not cross the International Date Line.

![image](https://user-images.githubusercontent.com/5322669/36995322-98ba7718-2068-11e8-94a7-f2496f759a42.png)

Even when the labels do not overlap it is confusing which label belongs to which graphic.

**Comment by kgonzago** [comment]
The international dateline is causing more issues with labeling than anticipated when creating circles, ellipses, and rings. Labeling lines over the dateline was fixed but the same fix cannot be applied to the other shapes. For example, the center of the circle is used for labeling. The dateline causes an issue where the center of the circle is not truly the center of the circle. Hence labels are rendered no where close to the newly created circle. This also applies to both ellipses and range rings.

**Comment by kgonzago** [comment]
@csmoore mentioned using [LabelPoint](http://help.arcgis.com/en/sdk/10.0/arcobjects_net/componenthelp/index.html#//002m0000009q000000) for labeling text which **worked** for circles and ellipses. Range rings is a bit more complicated given labels should be rendered on the outside of the ring and conforming to the curvature of the ring.

**Comment by kgonzago** [comment]
@dfoll @ACueva The fix for circle and ellipse labeling is fixed in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/536). The international dateline is still an issue for rendering labels for Range Rings and will work further on it.

**Comment by kgonzago** [comment]
@dfoll and I discussed the range rings issue and concluded labels will not be created for rings that cross the international dateline. A logic check will be implemented for the range ring feedback when crosses the dateline. If so, then do not label that ring.

FYI @dfoll and @ACueva This needs to be documented as a `Known Issue`

**Comment by dfoll** [comment]
Verified the fix for circles and ellipses. Range rings are still labeling even when they cross the International Date Line. Included both a circle and range rings in the screenshot to show that the build I have has the fix for circles and ellipses in there, the fix for #534 is working as well

**Comment by kgonzago** [comment]
I got labels working over international dateline
![image](https://user-images.githubusercontent.com/6391826/37122225-b0ff1394-222d-11e8-90fa-b48ef94a2d9d.png)

**Comment by kgonzago** [comment]
@dfoll @ACueva Please test once [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/537) is merged.

**Comment by dfoll** [comment]
- updated the checklist test to note that rings should label
- verified the fix with the checklist test
-cursory check of the other fixes from this issue that were previously addressed
