### ISSUE TITLE
Range Ring graphics are not showing when creating rings interactively

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#534]
ArcMap 10.6.0.8321 and Military Tools build 23 (5Mar)
ArcMap 10.6.0.8321 and Distance and Direction 2.2.0.31

1. Open the Rings tab
2. Ensure Interactive checkbox is checked
3. Click a center point
4. Drag to where you want the next ring and click to create that ring
5. Draw two more rings
6. Double-click to finish

**_labels are created, but graphics are not displayed_**

I also noted that if i tried to create a feature class from this results of the steps above, a feature class is created but it has no features.

![image](https://user-images.githubusercontent.com/5322669/36996480-cf2087a4-206b-11e8-9e25-f2240ce17712.png)

**Comment by kgonzago** [comment]
Issue fixed in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/536)

**Comment by kgonzago** [comment]
Re-opening for PEs to verify

**Comment by dfoll** [comment]
- checklist test already exists to verify rings draw, have correct labels, and correct radius length.
