### ISSUE TITLE
Distance and Direction Ring [and ellipse] tool causes ArcMap to go unresponsive click outside basemap extent 

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#535]
ArcMap 10.6.0.8321 Distance and Direction 2.2.0.31 (3/5/18)
ArcMap 10.6.0.8321 and MT build 23 (5Mar)
When you create a set of rings and radials (non-interactive mode), set a distance, number of rings, number of radials and click outside the extent of the map, add a point, it is not handled, and you can hit enter to start creating range rings, but ArcMap goes unresponsive. This also affects Ellipses.
We should handle this like we do Circles (https://github.com/Esri/distance-direction-addin-dotnet/issues/512).

![image](https://user-images.githubusercontent.com/3801392/36997088-8682d928-2086-11e8-9776-22c8a8594f7f.png)
![image](https://user-images.githubusercontent.com/3801392/36997120-9ed9ae7a-2086-11e8-9490-6bb54cb5e7b8.png)
![image](https://user-images.githubusercontent.com/3801392/36997355-67598186-2087-11e8-85e5-7f0cdf30bbd7.png)
![image](https://user-images.githubusercontent.com/3801392/36997415-8b3bba10-2087-11e8-8ede-eff2e7d3f8f9.png)

**Comment by csmoore** [comment]
Addressed in #546 - ready for QA/QC

While testing this I saw another, less common issue - written up in a new issue #547

**Comment by ACueva** [comment]
I have tested this on ArcMap 10.6, the fixes appear to have worked, however, I'm noticing the following:

![2018-04-20_13-53-26](https://user-images.githubusercontent.com/3093940/39074677-41520bea-44a7-11e8-8919-adbf6589fd27.jpg)

The label appears to be inverse while zoomed way out.  Once you zoom in, it appears fine.
![2018-04-20_14-31-20](https://user-images.githubusercontent.com/3093940/39074748-84e6ee3e-44a7-11e8-98aa-70efc1c69df0.jpg)

I'll log another issue to address these findings.

FYI @csmoore @kgonzago

**Comment by ACueva** [comment]
Remaining work: 
- [ ] https://github.com/ArcGIS/solutions-defense-test-catalog/pull/127 Reviewed and merged.
- [ ] Possible CMS work (@acueva is still looking into this)

**Comment by ACueva** [comment]
@dfoll @topowright I believe this can be moved to done.  Do we need a Verify tag to verify my CMS changes?

**Comment by dfoll** [comment]
verified list as an issue addressed. was never listed as a known issue, so nothing to remove there

**Comment by dfoll** [comment]
@ACueva I forgot to add that this should be added to the What's New page for Defense and the What's New section on the homepage.

- [x] Resources page
- [x] Defense What's New page
- [x] What's New section on homepage

**Comment by dfoll** [comment]
[df - 24Apr -- verified the fix is a message box that the point is out of bounds]
