### ISSUE TITLE
DD widget could have better zoom support for circles, ellipses, rings

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#539]
Enhancement request:  I find that the mouse-wheel zoom functionality in web apps is disabled while you are creating some geometries (circle, ellipse, rings) interactively in the Distance and Direction widget.
Normally, in a WAB app you can zoom/pan in and out by setting the cursor location and moving the scroll wheel.  In the Distance and Direction widget, once you start using the add circle/add ellipse/center point for rings buttons to create a geometry on the map, this functionality is disabled. It works when you are adding a line interactively. It would be nice for the scroll wheel zoom functionality to remain enabled for circles, ellipses, and rings so you could more easily zoom to the precise location of your target point and then zoom out to finish it outside of the (small) extent of the zoomed in map.

**Comment by BobBooth** [comment]
@adgiles @kgonzago

**Comment by kgonzago** [comment]
This issue should be moved over to Devtopia. Also, similar issue logged: [#12673](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12673)

**Comment by lfunkhouser** [comment]
@BobBooth Provide an example of a widget for reference that has this functionality. @kgonzago this will move to the other repo if we will address this.

**Comment by BobBooth** [comment]
@lfunkhouser - the Smart Editor widget behaves this way.
https://nationalsecurity.esri.com/portal/apps/webappviewer/index.html?id=e09c068208384f1fb8542344c7b50c1c

![image](https://user-images.githubusercontent.com/3801392/44874702-0bd7c100-ac6a-11e8-9f52-33c0991716b7.png)

**Comment by kgonzago** [comment]
@BobBooth @lfunkhouser Map navigation by design is disabled during line, circle, ellipse or range ring creation. We can look into implementing it if map navigation is needed; should be an easy LOE.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/solutions-defense-widgets#209
