### ISSUE TITLE
Label DD Circles in Pro - Create a layer package for Distance and Direction Feature Classes

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#541]
### Background
Users need to have labels on features created by Distance and Direction. Creating this layer package will enable us to advance development on creating labels in ArcGIS Pro.

### Current State
We are unable to create labels for any features being created for Distance and Direction in ArcGIS Pro.

### Expected Result
- [x] Have a schema (layer package) that will allow a developer to understand what should be used to write features to
- [x] Sample data for circles

**Comment by dfoll** [comment]
Done. Sent work to @csmoore I'm hesitant to move this to done, because I would like to see the issue for this stuff getting into Pro.

**Comment by csmoore** [comment]
Now successfully using this layer package in the addin in branch: https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23541-pro-features ( and the current lpkx is [here](https://github.com/Esri/distance-direction-addin-dotnet/tree/csm/%23541-pro-features/source/addins/ProAppDistanceAndDirectionModule/ProAppDistanceAndDirectionModule/Data) )

Hopefully this is the output expected - if so you can probably mark issue as complete.

![image](https://user-images.githubusercontent.com/3090809/39196225-9120e276-47af-11e8-859e-f20c43165723.png)

Note: there were a couple small changes to the original lpkx provided ( @dfoll and I did this together over screenshare) :

1. Renamed layer to "Circles"
2. Put layer in a group layer called "Distance And Direction" 
3. Renamed lpkx to `Distance_And_Direction.lpkx`

![image](https://user-images.githubusercontent.com/3090809/39196272-ad990686-47af-11e8-9d6d-2df6b68adf54.png)

**Comment by topowright** [comment]
Closing this issue. We should have made this a task in the other issue that identifies value. This was my mistake.

**Comment by lfunkhouser** [comment]
This issue is a task to provide labels on output, #540
