### ISSUE TITLE
Poor Performance and Hangs Experienced for some projections at 10.6.1 with ConstructGeodesicXXX

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#547]
Using the addin at **10.6.1** (does not seem to be an issue at 10.4-10.6) I am experiencing poor performance with the feedback graphics and occasional hangs when clicking outside the bounds of the basemap. This is similar but not identical to issue #512 #535 , also this issue only seems to occur with certain maps/coordinate systems (for example it does not occur when using the online basemaps).

Upon further investigation, the lock up / hang occurs in the ArcObjects methods `ConstructGeodeticLXXX`: ex `IConstructGeodetic.ConstructGeodesicCircle / ConstructGeodesicEllipse / ConstructGeodeticLineFromPoints' when the point is outside of the projection. 

Repro case 1 (simple repo case):

1. Launch ArcMap, start with a new, empty map
2. Add a local basemap: C:\Program Files (x86)\ArcGIS\Desktop10.6\TemplateData\TemplateData.gdb\World\continents 
3. Open the Distance and Direction Addin
4. From Distance and Direction Circle Tab (you can actually do this from any tab)
5. Select the Interactive method (its the default)
6. Click to create a center point
7. Using the feedback circle, try to create a circle that is outside of the basemap
8. Note poor performance of the feedback circle
9. Hang once the circle is outside of the basemap extent

Repro case 2 (more complex repo case where point falls within layers but outside projected map):

0. Build the addin from this repo and add the addin to ArcMap
1. Launch ArcMap
2. Add a local basemap: C:\Program Files (x86)\ArcGIS\Desktop10.6\TemplateData\TemplateData.gdb\World\continents 
3. Set the Data Frame coordinate system (Layers | Properties | Coordinate System) to Projected | World | UTM | WGS 1984 UTM Zone 10
4. Restart ArcMap (because of Issue #527)
4. Open the Distance and Direction Addin
5. Distance and Direction Circle Tab
6. Click on Map Point Tool
7. Click on point outside of visible map 
8. ConstructGeodetic.ConstructGeodesicCircle fails to return

For case 1 we could add more checks for basemap extents (even though this was not necessary prior to 10.6). However for case 2, I am not sure how to test for since the point falls within the layers of the map. So this issue/lock-up may need to be addressed in the ConstructGeodetic code itself and should be reported to core to see if they can address or suggest a workaround.

![image](https://user-images.githubusercontent.com/3090809/38947074-6fce0ad6-4309-11e8-9fff-747926c2b356.png)

Point is valid (though outside projection), but this function does not return:

![image](https://user-images.githubusercontent.com/3090809/38947121-8fc23a1a-4309-11e8-8189-eec06994b411.png)

@dfoll @ACueva @topowright @lfunkhouser

**Comment by csmoore** [comment]
This issue was noticed again during January 2019 release testing. The title and issue comments were updated (sorry if that impacted the doc @dfoll @BobBooth )

**Comment by lfunkhouser** [comment]
Workaround: Use ArcGIS Pro.
