### ISSUE TITLE
The Delete key on the Line, Ellipse, and Ring tabs removes all zeros if the leading nonzero digit is deleted.

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#548]
In issue https://github.com/Esri/distance-direction-addin-dotnet/issues/278 it was reported that the circle tab had unexpected behavior of setting the distance to "0" when the first digit was deleted from a distance string with multiple zeros. So, for e.g., delete the 2 before 200,000 should leave the 00,000 in the box, so I can add a 3 to make 300,000.
This was corrected for the circle tab in PR#529 but the issue applies to the other distance fields on the Line, Ellipse, and Rings tabs.

Tested ArcMap 10.5, MT 2.0 build from 4/17/18.

**Comment by topowright** [comment]
We need to update this issue to identify exactly where the fix needs to be applied.

**Comment by dfoll** [comment]
@topowright @kgonzago @lfunkhouser build 12  in ....\Commercial\Solutions\DefenseSolutions\DistanceAndDirection\Testing can be used to test this functionality

**Comment by dfoll** [comment]
There is still a problem with this on the Line tab in ArcMap. All tabs in Pro work correctly, and the Circle, Ellipse and Ring tab work correctly in ArcMap.

Line tab does not draw in ArcMap:
1. Select From: Distance and Bearing
2. Enter a starting point
3. Enter a distance/length of 10,000
4. Enter an angle of 32
_preview draws_
5. Change the distance/length to 20,000 by deleting the 1 and typing a 2
_preview updates_
6. Press Enter
_no line draws_
