### ISSUE TITLE
Range Ring radials distorted when they would pass near the poles

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#551]
I'm seeing an issue with the angle of the radials being wrong, the radial features distorted, when range rings are created that have radials that pass near the poles.
For example, if I create two range rings sets with 10 rings, 200 km spacing, and 4 radials but put one centered near Thompson Manitoba, and another near the pole in the arctic, you can see some distortion of the east-west oriented radials in the first case, but the arctic case is highly distorted.
![image](https://user-images.githubusercontent.com/3801392/39065607-5a7ee0ea-44a0-11e8-921e-decdab707bf1.png)
also see a larger set of rings further south.
![image](https://user-images.githubusercontent.com/3801392/39065628-697e3f14-44a0-11e8-971e-3193feb9ebc9.png)

ArcGIS Pro 2.1.0 Military tools build from April 17, 2018.
Web Mercator coordinate system

**Comment by lfunkhouser** [comment]
Closing. Expected behavior for using this projection in the issue. Recommendation - use different projection for this case.
