### ISSUE TITLE
Distance and Direction addin UI should not have decimals in outputs for measurements

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#567]
- [ ] UI will display up to 2 decimal places
- [ ] Labels will be whole numbers

@kgonzago and @csmoore can distance and direction interactive outputs in the UI not be crazy lengths for each measurement? Crazy being more than four decimal places

**Comment by lfunkhouser** [comment]
@topowright please rewrite the question above as an issue if it is not behaving as expected. Add a screenshot showing the current behavior and how you want the results to be for expected results.

**Comment by kgonzago** [comment]
@topowright A simple one liner fix, we can definitely limit the display of numeric values to four (4) significant digits.

**Comment by kgonzago** [comment]
Changes to address this issue is in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/598)

**Comment by ACueva** [comment]
Verified #598.

**Comment by lfunkhouser** [comment]
@ACueva @kgonzago @topowright This implementation was not correct. The display was not supposed to be to two decimal places. The issue was specifically for the feedback in the UI not on the map. The display on the map was to remain as whole numbers.
