### ISSUE TITLE
Distance Calculator labels Diameter incorrectly

### ISSUE THREAD

**Issue by ACueva** [Esri/distance-direction-addin-dotnet#569]
Environment:
ArcGIS Pro 2.2 Daily
Distance and Direction 3.0 Build 6 from Military Tools

Steps to reproduce:
1. From the Circle Tab select "Radius"
2. Enter Center Point: 32° 41' 41.87"N 117° 7' 30.39"W
3. Expand Distance Calculator
4. Enter a Time of: 2 hours
5. Rate of 60 Miles/hour

A circle with a label of Radius: 120 Miles should draw.

Repeat the same steps listed above, this time change the Radius to Diameter.
A circle of the same size will draw, the label will be Diameter: 120 Miles.

The attribute field for the circles created will show the distance listed as "120" for both of these circles created.
![2018-05-24_16-21-46](https://user-images.githubusercontent.com/3093940/40518649-82d80ba8-5f70-11e8-891c-ad788aa5dd23.jpg)

FYI @csmoore, Can you chime in with a level of effort to address this issue?

**Comment by csmoore** [comment]
@topowright asked me to look at this issue. I can reproduce the issue.  As shown above - the radius is the correct measurement and the diameter is incorrect (should be doubled).

@topowright - is this the next issue I should work on?

![image](https://user-images.githubusercontent.com/3090809/40556063-4239ef2c-6019-11e8-83fb-81b6f82eeaea.png)

**Comment by csmoore** [comment]
Was asked by @topowright to work on this next so dependent circle issue #540 could be closed out - moving to in progress for dev work

**Comment by csmoore** [comment]
Addressed in PR #578

**Comment by ACueva** [comment]
Tested locally on Esri/csm/#569-bad-diameter-label branch:
![2018-05-29_9-40-43](https://user-images.githubusercontent.com/3093940/40672920-172b6716-6325-11e8-8315-7156afce12d0.jpg)

**Comment by ACueva** [comment]
Verified in Military Tools build 8.
![2018-05-29_10-11-03](https://user-images.githubusercontent.com/3093940/40674144-d101aee0-6328-11e8-9bc6-f7a1deeab6a6.jpg)
![2018-05-29_10-10-50](https://user-images.githubusercontent.com/3093940/40674147-d2c1d5d4-6328-11e8-9251-b03006c126c7.jpg)
