### ISSUE TITLE
Distance and Bearing Does not draw lines

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#576]
### Background

With the changes made to distance and direction using feature classes distance and bearing does not produce a line to the map. 

### Expected Results
Distance and Bearing should produce lines on the map

**Comment by csmoore** [comment]
I see what is happening here. For some odd reason lines created with these options lack Z values so can't be stored in Z-aware feature class ( which is the opposite of the problem we had here: https://github.com/Esri/distance-direction-addin-dotnet/issues/542#issuecomment-391740330 ) - we'll have to look into how to make these all created with a consistent Z attribute.

**Comment by csmoore** [comment]
This should be fixed in PR #577 and look like this after fix - not sure if this should be brought into sprint but seemed like a significant failure:

![image](https://user-images.githubusercontent.com/3090809/40665982-aadfb938-632c-11e8-825e-ca74e0f745b9.png)
