### ISSUE TITLE
Update Clear button to remove "Graphics" 

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#581]
#### Tasks to be done

The word graphics is removed from all doc pertaining to the clear workflow - Lyle

- [x] Intro
- [x] Lines
- [x] Rings
- [x] Ellipses
- [x] Circles

UI changes
- [x] Change the string to just say clear

#### Verify
- [x] UI says Clear

No graphics statement in the doc
- [x] Intro
- [x] Lines
- [x] Circles
- [x] Rings
- [x] Ellipses

**Comment by ACueva** [comment]
PR #582 in and ready for review.  FYI @topowright @dfoll @csmoore @kgonzago @BobBooth

**Comment by topowright** [comment]
UI is now good based on the PR from @ACueva. Now updating the doc.

**Comment by topowright** [comment]
- Topic for introduction has been versioned and changes are ready to be reviewed.
- Range Rings topics need to be reviewed
- Line topics that have been versioned are now ready for review
- Ellipse topics that have been versioned are now ready for review
- Create Circles interactively is the only topic that had the word graphics in the content and that needs to be reviewed
