### ISSUE TITLE
Distance and Direction "Clear"/"Save As" buttons temporarily disabled

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#591]
## Background
The "Clear" and "Save As" buttons on any of the Distance and Direction add-in tabs for ArcGIS Pro are disabled after creating a feature, until a third click is made with the mouse. The click can be either switching to another tab and switching back,  or clicking on the map to start another feature.  It seems that there is some logic that the add-in does not register that there is a feature to clear or save until some sort of refresh by either starting a new feature or switching to another tab and back

## Steps to Reproduce/requirement
_ArcGIS Pro 2.2 MT build 15 or later_

1. On the Distance and Direction add-in click the circle tab
2. Enter a staring point (paste in 13SEV9029499629)
3. Enter a radius value of 2000 meters
4. Press Enter
_Note that the feature is created but the clear and save as buttons are disabled_
5. Paste in a different center point (15SUB6826466534)
_Now the clear and save as buttons are active_

_There are a couple other behaviors you can do to get the buttons to become active like interactively clicking another point, or switching to a different tab and switching back. Also I experienced this behavior regardless of what tab I started with. I tried to write repro steps that narrowed down interactions with the software as much as possible hoping that might put more focus on what the problem is with the code._

## Expected results/behavior
Clear and Save As buttons should be active as soon as a single feature is created

## Version
ArcGIS Pro 2.2 Military Tools build 15

**Comment by csmoore** [comment]
I can reproduce the scenario above - but only the first time from a new project when the layer package is loaded. However I do see some bad behavior and left-over code from the previous graphics elements implementation so can remove to see if that fixes your problem.

**Comment by ACueva** [comment]
PR #595 Reviewed and merged.  Verifying fix on MT Build.

**Comment by csmoore** [comment]
Another issue has surfaced related to this: if an existing project with existing D&D features is opened the Clear button is not enabled (should be). Looking into this...

**Comment by csmoore** [comment]
Addressed the [additional issue found above on project load with existing items](https://github.com/Esri/distance-direction-addin-dotnet/issues/591#issuecomment-394788888) in PR #599
