### ISSUE TITLE
New feature dataset is added to the default geodatabase if the layers are not present in the table of content

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#594]
#### Background: 
Distance and Direction is adding a feature dataset if the layers are not present in the ToC

#### Expected Behavior
When the layers are not present in the ToC the Addin will check to see if the featureset exists. If it exists then the user will be prompted to either connect the layers that will be added to the ToC to the featuredata set that exists or create a new feature dataset.

**Comment by csmoore** [comment]
Can you provide some more information on this end-to-end scenario? Perhaps starting from a new project.

I *think* the scenario is the Distance and Direction feature dataset is already in the project default database so you don't want to add it a second time - but how did it get there if not added by the addin? Is this an anticipated scenario or just something you encounter during the initial creation of the lpkx?

The problem with not adding the layer from the lpkx is that the layer package not only contains the data but all the characteristics of the layer (ex. symbology, labeling, etc.). Also, we have been [unable to get ApplySymbologyFromLayer to work as expected from API](https://github.com/Esri/distance-direction-addin-dotnet/issues/559#issuecomment-394450498) + #592 so adding the data and applying the lpkx may not be possible.

**Comment by topowright** [comment]
We have logged an issue in the Pro SDK: 
ArcGISPro/SDK/issues/42

**Comment by lfunkhouser** [comment]
More info needed - steps to reproduce and expected behavior required

**Comment by lfunkhouser** [comment]
Closing, as designed. User may wish to create a new FC and new feature dataset. Closing until further requirements are presented.
