### ISSUE TITLE
Exporting to KMZ leaves lockfile in folder preventing next KMZ export in folder

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#601]
When I export Range Rings, Ellipses, Circles, or Lines from ArcMap 10.3.1 using MT v3, build 22, I am seeing a lock file persist in the output folder that prevents the next export to KMZ from working correctly. The KMZ file is created for the second attempt, but it is empty of geometry (the first try works fine, the geometry is created, so I think it is this persistent lock file that is messing things up).

Repro Steps:

1. In ArcMap
2. Create a circle graphic, export to KMZ, exports normally, file size as expected
3. Create a ring graphic, export to KMZ, exports **incorrectly** file size 1KB

![image](https://user-images.githubusercontent.com/3801392/41005286-d9cb17ce-68ea-11e8-85a2-f895d4d86cc5.png)

Initially reported as a comment in https://github.com/Esri/distance-direction-addin-dotnet/issues/589

**Comment by BobBooth** [comment]
I think this could be addressed by cleaning up the .lock file (probably simplest solution) or by varying the name of the tmpShapefile that is used to construct the KMZ.

**Comment by BobBooth** [comment]
@csmoore - this should be an easy fix, correct?

**Comment by topowright** [comment]
Current repo steps: 

1. start up arcmap
2. create graphic from dd
3. export graphic as a kmz
4. open in earth
5. close earth
6. close armap
7. reopen arcmap

result is arcmap normal mxt is curropted and does not open back up. 

Symbology is not correct in ArcGIS Earth as well

**Comment by csmoore** [comment]
@BobBooth - there is not much we can do about the schema lock (.sr.lock) files - these only release when the process exits - but we can probably solve this specific issue by making sure the "tmpShapefile.shp" filename is unique and not reused.

@topowright - also wanted to just confirm that the repro steps above involving ArcEarth go with this issue.

**Comment by BobBooth** [comment]
@csmoore - about the lock file only releasing when the process exits - is that when ArcMap gets closed? I would think it would be when the KMZ file was finished being written. Maybe there is some object that needs to be deleted/released at the end of the export to KMZ that would trigger the deletion of the sr.lock file?

**Comment by topowright** [comment]
From the traffic above and the testing today I think this issue needs to be closed based on the work that was done by @CTLocalGovTeam. The sr lock file is removed after ArcMap is closed. @csmoore has added the idea above that this issue will only be addressed by closing ArcMap. Closing this as verified based on those ideas.

**Comment by BobBooth** [comment]
This was addressed by Cybertech - the shapefile name is now unique, so KMZ can be made in spite of lock file, which is removed when ArcMap closes.
@lf
