### ISSUE TITLE
Line tab label placement is far off from graphic when using keyboard entry

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#607]
Both the "From: Distance and Bearing" and "From: Points" options are not labeling the resulting graphic when using only keyboard entry.

1. Use the Line tab and the "From: Points" functionality
2. Paste in a starting (10UDB4539650854) and ending (17SLS5178599938)  point
3. Press Enter.
4. The line that draws appears to have no label
5. Zoom out to the full extent of the map, you can see that it was labeled, but a good deal away from the graphic
5. Use the map point tool to select a starting and ending point. 
6. The resulting graphic labels close to the line

Did not observe this style of behavior for any of the other tabs.

10.4.1 MT build 42

**Comment by dfoll** [comment]
Mentioning @kgonzago  because I'm not sure if this may have had something to do with the work we did trying to resolve the issue we were having with labeling graphics that are close to the IDL. Mentioning @lfunkhouser to prioritize and decide if we want to fix this

**Comment by lfunkhouser** [comment]
@dfoll Adding to the issues to be fixed for this release since it sounds like something we introduced since the last release.

**Comment by kgonzago** [comment]
Fix implemented in this [PR](https://github.com/Esri/distance-direction-addin-dotnet/pull/613)

**Comment by topowright** [comment]
This issue is now drawing the labels at the beginning of the line. @kgonzago will you log an issue for changing the labels to be along the line?
  
![image](https://user-images.githubusercontent.com/5488313/41689765-2bcedfac-74a7-11e8-8301-c02401923a5f.png)
