### ISSUE TITLE
Distance unit in feature tables is not based on resource value

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#608]
The addin is placing the non-localized/resource version of the Enumeration string in the table/feature attribute vs. using the localized/resource value.

As a result the values will always be the same value (Enumeration) regardless of the Resource Value.

In the example below the resource value is "Nautical Miles"(with space in Addin UI on left) but the Enumeration Value of "NauticalMiles" (no space on table at bottom) is placed in the Table/FeatureClass attribute for DistUnit 

![image](https://user-images.githubusercontent.com/3090809/41436010-78c69c04-6fee-11e8-8626-a8eabc876c22.png)

#### Expected result:
the unit in the DistUnit attribute should match the units selected in the Distance/Length drop-down on the Distance and Direction pane

**Comment by csmoore** [comment]
Seeing the "Nautical Miles" correctly in PR #658 

![image](https://user-images.githubusercontent.com/3090809/59067055-9810b780-887e-11e9-81c6-71a5b8001d61.png)

**Comment by dfoll** [comment]
- DD june release topic updated
- MT june release topic updated

**Comment by dfoll** [comment]
G-Doc (CMS) label can be removed when publishing/building tasks are completed

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/june-2019-distance-and-direction.htm
https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
 - \\...\DefenseSolutions\DistanceAndDirection\Dev\88\
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\307\

**Comment by lfunkhouser** [comment]
Verified doc updates on solutionsdev for MT and DD and PDFs for MT (dev build 3.5.0.308) and DD (dev build (88).
