### ISSUE TITLE
Pro Nautical Miles Unit label not showing in feature label

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#609]
In Pro the Nautical Miles Unit portion of the label is not showing in the feature's label.

This is because the feature's unit is "NauticalMiles" (no space) vs. "Nautical Miles" (space) as noted in issue #608

![image](https://user-images.githubusercontent.com/3090809/41435810-f6e0b3d2-6fed-11e8-8c12-4b52a06e0274.png)

**Comment by csmoore** [comment]
Addressed in PR #610 by removing space from NauticalMiles in label expressions of DistanceAndDirection layers

After change should look like: 

![image](https://user-images.githubusercontent.com/3090809/41436683-5ef9bae8-6ff0-11e8-935f-cefd19d321b7.png)

**Comment by topowright** [comment]
This is fixed and has been tested in 2.2: 
![image](https://user-images.githubusercontent.com/5488313/41689943-1c4f5632-74a8-11e8-9d94-a0b73092ce0b.png)

**Comment by lfunkhouser** [comment]
n.m. is not a symbol for nautical mile. They symbol for nautical mile is M, NM, or nmi

Removing the `verified `label, and adding back `development `and `qc (manual)`.

**Comment by csmoore** [comment]
Change made in PR #615

Should look like this with PR - layer label expression change highlighted below:

![image](https://user-images.githubusercontent.com/3090809/41856304-b956a652-7862-11e8-8306-2b64e2541278.png)

**Comment by dfoll** [comment]
Verified on build 20 of DD. Can test from MT build when it finishes.
![image](https://user-images.githubusercontent.com/5322669/41858359-897a68e2-784e-11e8-933a-0d8146a41004.png)
