### ISSUE TITLE
Enhance label placement for lines

### ISSUE THREAD

**Issue by kgonzago** [Esri/distance-direction-addin-dotnet#614]
Labels are currently created at the starting point of a newly created line. This approach was taken to solve #533. Labels should be created in the middle and follow the curvature of a line. This enhancement will follow labeling standards in ArcMap and ArcGIS Pro.

**Note: With this new approach, labels created for lines crossing the international dateline will be an issue (please see #533)**

**Comment by lfunkhouser** [comment]
@kgonzago Can you provide additional information on how this change will affect circles, rings, and ellipses in #533

**Comment by kgonzago** [comment]
@lfunkhouser This feature will not affect those other shapes you mentioned; only lines.

**Comment by lfunkhouser** [comment]
@kgonzago please provide a level of effort to label the lines along the line drawn.

**Comment by lfunkhouser** [comment]
Closing. Current implementation will not be updated at this time.
