### ISSUE TITLE
Add support for Cumulative to the Rings tab

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#624]
#### Background
Currently the Distance and Direction widget has a support for creating cumulative rings from a given cetnerpoint. 
![image](https://user-images.githubusercontent.com/5488313/44767035-061a9800-ab11-11e8-8284-feedb83e144a.png)

##### Current State
Adding the cumulative feature to the addin will allow our users to do a workflow in desktop that currently can only be done in the web. 
This widget can be viewed at the following url for awareness: 
http://esrifederal.maps.arcgis.com/home/item.html?id=08c8e2eee1284a4682fe5b8db66fba8f

#### Expected Resulst
- [x] Add a drop-down list that allows a user to select a type of Rings analysis
- [x] Enable cumulative support to the rings tab
- [ ] Document the new functionality **(in progress @kgonzago)**
- [ ] Verify that the functionality is correct

**Comment by dfoll** [comment]
@topowright @kgonzago @lfunkhouser build 12  in ....\Commercial\Solutions\DefenseSolutions\DistanceAndDirection\Testing can be used to test this functionality

**Comment by kgonzago** [comment]
Drop-down list with options: 

![image](https://user-images.githubusercontent.com/6391826/47020785-1e2d9180-d128-11e8-934e-520e6d7d32a2.png)

**Comment by kgonzago** [comment]
Cumulative Testing:
![image](https://user-images.githubusercontent.com/6391826/47020972-76649380-d128-11e8-91b9-efe8c6a66d31.png)

**Comment by kgonzago** [comment]
When selecting either `Cumulative` or `Origin` from the ring analysis type drop-down list, you will need to provide distances first before supplying a coordinate. If a user tries to create a point on the map without supplying distances, they will receive this message:
![image](https://user-images.githubusercontent.com/6391826/47021747-0820d080-d12a-11e8-9190-f26363739e4a.png)

**Comment by dfoll** [comment]
This new functionality should be added to the Military Tools 3.3 cms release topic as well

**Comment by kgonzago** [comment]
I will work on the workflow topic for this issue

**Comment by BobBooth** [comment]
@kgonzago and I just added the workflow topic and republished to solutionsdev and the PDF. revoved the Doc CMS and QC Doc tags.

**Comment by BobBooth** [comment]
I believe the Doc Website tag can be removed after https://github.com/ArcGIS/arcgis-solutions-website/pull/7237 is merged.

**Comment by BobBooth** [comment]
This is impeded - needs review and merge by @dfoll or @topowright who are not available.

**Comment by dfoll** [comment]
Reviewed and merged
