### ISSUE TITLE
Updating the Range Rings functionality

### ISSUE THREAD

**Issue by topowright** [Esri/distance-direction-addin-dotnet#627]
Range Rings needs to support four custom workflows that currently are supported in the widget, which can be found here: 

http://esrifederal.maps.arcgis.com/apps/webappviewer/index.html?id=08c8e2eee1284a4682fe5b8db66fba8f

Those workflows are 
**Interactive**
Allowing the user to select the range rings by clicking on the map
**Fixed** 
User can select or input a center point and then create a set number of rings equally spaced from the start point. 
**Cumulative**
A user can enter a start point and then create rings spaced based on the placement of the last placed ring. 
**Origin**
A user creates a set of rings at different distances all distances originating from the start point

**Comment by topowright** [comment]
@saip I would like to discuss this functionality further. Lets set up a time to talk this coming week.

**Comment by csmoore** [comment]
This issue looks like it was addressed in PR #631 - that added fixed/cumulative options to rings tab
