### ISSUE TITLE
Range rings creation method drop-down menu should have a label

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#632]
#### Background
Distance and Direction Rings tab has a drop-down menu for the type of rings you want to create, however this drop-down has no label to it

#### Current behavior
![image](https://user-images.githubusercontent.com/5322669/47045429-a2434180-d147-11e8-83b1-1c711fd5edd6.png)

#### Expected behavior
The drop-down should have a label to it, the same way that the other inputs do

![image](https://user-images.githubusercontent.com/5322669/47045856-b471af80-d148-11e8-9bf2-a525634c1a57.png)

**Comment by csmoore** [comment]
Addressed in PR: #646
Should look like this after PR:

![image](https://user-images.githubusercontent.com/3090809/53191666-667b2580-35da-11e9-9ec6-0f5006459afe.png)

**Comment by BobBooth** [comment]
Built from dev. The Ring type dropdown control now has a label.
ArcGIS Pro 2.3
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/4c7a9775-322d-46df-99db-b85e3e526c9a)
and in ArcMap 10.3.1
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/fe36ef7a-8692-4c17-bdfa-4d5f6a0471bf)
