### ISSUE TITLE
Line creation method drop-down menu should have a label

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#633]
#### Background
Distance and Direction Line tab has a drop-down menu for the type of line you want to create, however this drop-down has no label to it

#### Current behavior
![image](https://user-images.githubusercontent.com/5322669/47046138-5396a700-d149-11e8-8528-a58c1d728915.png)

#### Expected behavior
The drop-down should have a label to it, the same way that the other inputs do

**Comment by csmoore** [comment]
Addressed in PR: #646
Should look like this after PR:

![image](https://user-images.githubusercontent.com/3090809/53190537-d20fc380-35d7-11e9-927c-b6aa55e9899e.png)

**Comment by BobBooth** [comment]
Built Dev, this is fixed:
ArcGIS Pro 2.3:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/3de23042-642f-4bc3-aa44-f08679e02f08)
ArcMap 10.3.1
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/478582e2-e3e4-4f9f-8504-1bb9aadae776)

**Comment by BobBooth** [comment]
This is fixed on dev
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/e9f7c6a2-5064-489f-a2d6-eb849d7be61b)
