### ISSUE TITLE
Out of bounds clicks for Lines tab interactive construction not handled correctly

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#634]
In Pro, the Distance and Direction addin is not handling "out of bounds" clicks when interactively constructing lines.  
I can click in the Pacific, zoom out to see the western edge of the basemap, drag a line across it, and click in the whitepace outside of the basemap extent. Should get an "out of bounds" message, but do not. The line is created with incorrect "nan" length.
![image](https://user-images.githubusercontent.com/3801392/47047688-3d4b1400-d166-11e8-845d-c111f4924690.png)

In contrast, the interactive construction methods for Circles, Ellipses, Rings are behaving correctly, popping up the out of bounds error when you stray outside of the basemap extent.

![image](https://user-images.githubusercontent.com/3801392/47047744-6ec3df80-d166-11e8-906c-36f45d2716f1.png)

We have fixed "out of bounds" issues before, here:
https://github.com/Esri/distance-direction-addin-dotnet/issues/512 
and here:
https://github.com/Esri/distance-direction-addin-dotnet/issues/535

I tested the released version of Distance and Direction on Pro 2.1, and I am seeing the same behavior (click out of bounds creates line with nan length). 
I also tested the released version in ArcMap 10.3.1 and the "out of bounds" message is displayed correctly in ArcMap. This seems to be an issue that was found and fixed in ArcMap, but not identified in Pro. It is not a new issue in Pro with the recent PR.

____

**UPDATE**: This is also an issue on Rings Tab when the "Origin" and "Cumulative" options are used

**Comment by csmoore** [comment]
While testing this with an existing Pro project I got the dreaded "Spatial Index Grid Size" error that we have seen previously in Pro with lpkxs ( https://github.com/Esri/military-features-data/issues/287 ) - not sure if this is a new issue at Pro 2.3, but will write a new issue for this:

![image](https://user-images.githubusercontent.com/3090809/53256757-9f78d000-3696-11e9-83e3-cc1ef7913aa8.png)

**Comment by csmoore** [comment]
Addressed in PR #650

**Comment by dfoll** [comment]
Built
- Solutions\DefenseSolutions\DistanceAndDirection\March2019\Dev\44 and 
- Solutions\DefenseSolutions\MilitaryToolsForArcGIS\March2019\Dev\216
for testing

Doc updated 
- Solutions\DefenseSolutions\DistanceAndDirection\March2019\Dev\44
- https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/march-2019-distance-and-direction.htm
- Solutions\DefenseSolutions\MilitaryToolsForArcGIS\March2019\Dev\216
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/march-2019-military-tools-for-arcgis.htm

**Comment by dfoll** [comment]
@BobBooth ready for doc qc

**Comment by BobBooth** [comment]
Verified issue in tables on solutions dev MT and DD and in PDFs for each.
