### ISSUE TITLE
Cannot drag row to bottom in Range Rings Distances table

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#635]
In the new multiple distances table, when creating range rings from "Origin" or "Cumulative", the rows in the table should permit you to drag a distance to a new position in the table.
Sometimes when you click on a row and drag it up or down, the row will move up. Sometimes it will not.
To reproduce: 
1. Click Rings tab.
2. Click Origin.
3. Add a series of distance values (5 of them, for example).
4. Click the three dot button to the left of one of the rows
5. Drag it to below the last entry.
![image](https://user-images.githubusercontent.com/3801392/47102438-c7e54f00-d20a-11e8-8d26-dd11981eeae4.png)

I cannot drag a row below item in the bottom row.  In the image, above, cannot drag the "400" row below the "70000" row.
This happens in ArcGIS Pro and in ArcMap.

**Comment by csmoore** [comment]
I saw this behavior with the Sept, 2018 release also - it seems like the behavior is you can't drag an item to the last row

**Comment by csmoore** [comment]
Verified that with PR #658 dragging from bottom (and other) rows work as expected now in ArcMap and Pro

**Comment by dfoll** [comment]
- updated DD june 2019 release topic
- updated MT june 2019 release topic

**Comment by dfoll** [comment]
G- Doc (CMS) can be removed when publishing/building  tasks are completed

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/june-2019-distance-and-direction.htm
https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
 - \\...\DefenseSolutions\DistanceAndDirection\Dev\88\
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\307\

**Comment by lfunkhouser** [comment]
Verified doc updates on solutionsdev for MT and DD and PDFs for MT (dev build 3.5.0.308) and DD (dev build (88).
