### ISSUE TITLE
Add gradian as an angle unit of measure

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#639]
From GeoNet, https://community.esri.com/thread/225811-military-analyst-geodesy-graphic-tool

Enhance angle unit of measure to include the gradian. Also known as gon, grad, and grade. The international standard symbol for this unit is "gon". Other symbols include "gr", "grd", and "g". 

The gradian is 1/400 of a turn (360 degrees).

Use cases: surveying, used in France

**Comment by dfoll** [comment]
#657  has a .lpkx that should have the required changes to the Arcade scripts for lines and ellipses

**Comment by csmoore** [comment]
Verified with #658 in ArcMap (10.6.1) and Pro (2.4.19921)

![image](https://user-images.githubusercontent.com/3090809/59104681-2711e400-8900-11e9-91e0-142276bc7a45.png)

![image](https://user-images.githubusercontent.com/3090809/59104885-b3bca200-8900-11e9-8b71-9692ae0ccf57.png)

**Comment by dfoll** [comment]
### Doc updates:
- added to What's New under both DD and MT [PR](https://github.com/ArcGIS/arcgis-solutions-website/pull/7876)
- added to DD june release
- added to MT june release

**Comment by dfoll** [comment]
G - Doc (CMS) can be removed when end of day publishing/building tasks are completed.

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/june-2019-distance-and-direction.htm
https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
 - \\...\DefenseSolutions\DistanceAndDirection\Dev\88\
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\307\

**Comment by lfunkhouser** [comment]
Verified doc updates on solutionsdev for MT and DD and PDFs for MT (dev build 3.5.0.308) and DD (dev build (88).
