### ISSUE TITLE
Distance and Direction rounds input coordinate values to two decimal places

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#644]
Distance and direction input coordinate text box is rounding coordinate values to two decimal places (behind the scenes... values look right in box, but are rounded in output geometry) this happens on all tabs that create point locations (start points for Distance and Bearing lines, center points of circles, ellipses, rings.
For example, if you enter:
-121.842673,36.589155
it gets rounded to 
-121.84,36.59

Tested with MT test data, created Distance and Bearing lines using the GP tool and the Table to Line of Bearing CSV.
The first row of that table creates a line of bearing starting at -121.842673,36.589155
If you open up Distance and Direction and create a Line using Distance and Bearing, and enter the starting value of
-121.842673,36.589155
and the Distance of 2081.72 and angle of 100.29
and create the line, you will get two parallel lines.
![image](https://user-images.githubusercontent.com/3801392/52304794-83b8be80-2961-11e9-8cb3-49e04e8c3f4c.png)

If you switch to Circle and enter a center point of -121.842673,36.589155, you will see the spot for the center of the circle at the start point of the DD created bearing line.
![image](https://user-images.githubusercontent.com/3801392/52304812-8a473600-2961-11e9-96cb-ee4b80d4adfe.png)

Zoom in close to it and hover pointer over it, and you will see it is at 
-121.84,36.59

Click Identify on line, OriginX and OriginY are rounded.
![image](https://user-images.githubusercontent.com/3801392/52305338-e8c0e400-2962-11e9-927c-e27fce1b43b5.png)

Zip of a PPKX with repro data attached.
[DD_Input_value_rounding.zip](https://github.com/Esri/distance-direction-addin-dotnet/files/2833922/DD_Input_value_rounding.zip)

Patrick S pointed this out to me, and I confirmed it is happening.
He saw it with MT 3.3.0.199, Pro 2.3
I verified it is happening with DD 4.1.1.41 (recent dev build), Pro 2.3

Also seeing this in ArcMap 10.3.1 with MT 3.3.0.199
![image](https://user-images.githubusercontent.com/3801392/52306518-368b1b80-2966-11e9-88d0-5e7010fe9d33.png)

This defect was present in the September 2018 build of MT.

**Comment by csmoore** [comment]
This was an issue in Coordinate Conversion Library call GetCoordinateString that was addressed in a PR in that repo https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/576

This issue can be tested after that PR is merged and D&D add is rebuilt

**Comment by BobBooth** [comment]
Tested from DD Dev after merging CC RE#576, this issue is fixed on ArcGIS Pro 2.3:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/6ae4e09c-2394-4d80-83a0-f6dc9c34c649)
and on ArcMap 10.3.1:
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/d360d5dc-b676-46c1-9421-cd9bb2f0b73a)

**Comment by BobBooth** [comment]
I have updated the doc to include, on the Resources tab, a Distance and Direction March 2019 page, listing the issue addressed. Also updated the PDF and the MT Resources for March 2019.
Nav on DD will work after YAML edits and DD will be listed in the What's New after PR (https://github.com/ArcGIS/arcgis-solutions-website/pull/7549) gets merged by @dfoll

**Comment by BobBooth** [comment]
Added checklist test for this issue, PR here:
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/200
@dfoll

**Comment by BobBooth** [comment]
Leaving Doc tag on until tab nav is working.
Removing QC- manual tag, as I built it from Dev and check, it was working.

**Comment by BobBooth** [comment]
Tab nav issue is now fixed.  Only waiting on the PR to be merged for What's New content to show up.

**Comment by BobBooth** [comment]
The doc is now current on Dev.
