### ISSUE TITLE
Clear and Save As buttons should have a hover action

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#647]
### Current behavior
The `Clear` and `Save As` buttons on the Distance and Direction pane do not have a hover action to indicate to the user that those buttons will do something when clicked. They do have tooltips that appear. 

### Expected behavior
Requesting that they also have a hover action that occurs to help the user understand that the button does something when clicked. These buttons should behave the way the `Add Favorite` button behaves on the Military Symbol Editor pane.

![image](https://user-images.githubusercontent.com/5322669/53257461-36925780-3698-11e9-9ee5-3d6e3e58697f.png)

This should exist on all four tabs of the Distance and Direction pane
Screenshot is of Dark theme, but the same example/expected behavior should apply to Light theme

**Comment by csmoore** [comment]
Verified with #658 in ArcMap (10.6.1) and Pro (2.4.19921)

![image](https://user-images.githubusercontent.com/3090809/59105252-91775400-8901-11e9-8a44-bdbcd454cf04.png)

**Comment by dfoll** [comment]
@lfunkhouser is this something you want to put in the doc? no sweat either way, just seems minor, and not previously listed as a known issue
