### ISSUE TITLE
Rename Clear and Save As buttons

### ISSUE THREAD

**Issue by dfoll** [Esri/distance-direction-addin-dotnet#649]
### Current behavior
Distance and Direction has `Clear` and `Save As` buttons, The same functionality on the Coordinate Conversion pane are named `Clear All` and `Export`. Requesting a change to match Coordinate Conversion.

### Expected behavior
Rename `Clear` and `Save As` buttons to `Clear All` and `Export`

**Comment by lfunkhouser** [comment]
Research to see if standard way/terminology is used across Pro

**Comment by dfoll** [comment]
looks good

![image](https://user-images.githubusercontent.com/5322669/64434775-4f3fe900-d08f-11e9-843a-8b941e7d7984.png)

**Comment by dfoll** [comment]
- [ ] [Defense What's new page](https://solutionsdev.arcgis.com/defense/what-is-new/) [PR8015](https://github.com/ArcGIS/arcgis-solutions-website/pull/8015) must be merged and built first
- [ ] [Distance and Direction October Resources](https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/october-2019-distance-and-direction.htm)
- [ ] \DefenseSolutions\DistanceAndDirection\October2019\Dev\108\
- [ ] [Military Tools for ArcGIS October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\333\
