### ISSUE TITLE
Distance Calculator on Circle tab - Need to add "Miles" as a choice in Rate section

### ISSUE THREAD

**Issue by pshowalter** [Esri/distance-direction-addin-dotnet#65]
Distance Calculator on Circle tab - Need to add "Miles" as a choice in Rate section where the units are selected.  This will allow the mph rate calculation listed in Acceptance Criteria in task.
![image](https://cloud.githubusercontent.com/assets/6842145/13225394/b5ecccca-d95a-11e5-8c99-d781e15b16eb.png)

**Comment by jmccausland** [comment]
@pshowalter please review and verify

**Comment by pshowalter** [comment]
Time: Seconds, Minutes, Hours - **OK**
Rate: Miles, Meters, KM, Feet, Nautical Miles - per second or per hour **OK**
