### ISSUE TITLE
ArcGIS Pro crashes when you add a point with Distance and Direction on Pro 2.1

### ISSUE THREAD

**Issue by BobBooth** [Esri/distance-direction-addin-dotnet#651]
Open ArcGIS Pro (2.1) with latest (3.4.0.226) MT addin (or DD 4.1.1.48) with a new map.
Open Distance and direction.
Click the Map point tool (on Line or Circle tabs).
Click on the map.
Pro crashes.

Does not affect Circle or Ellipse tabs.
Does not affect Pro 2.3
Does not affect Pro 2.2

**Comment by BobBooth** [comment]
@csmoore @dfoll @kgonzago @lfunkhouser - crash with DD on Pro 2.1

**Comment by csmoore** [comment]
I see the problem (that was introduced in [this PR/line](https://github.com/Esri/distance-direction-addin-dotnet/pull/650/files#diff-b7a999da509b42d8a917fa9a2a002aa3R689) with some odd behavior on 2.1 - map point clicks don't seem to have same SR as the map) and will PR in a bit

**Comment by dfoll** [comment]
confirming now, so i can understand when we look at it to see the fix

**Comment by csmoore** [comment]
Addressed in PR #652

**Comment by dfoll** [comment]
Solutions\DefenseSolutions\DistanceAndDirection\Testing\csm-651-crash-on-map-point-tool-2-1\28   to test fix

**Comment by dfoll** [comment]
with Solutions\DefenseSolutions\DistanceAndDirection\Testing\csm-651-crash-on-map-point-tool-2-1\28 i'm not seeing the above behavior on 2.1 (but i did not repro for myself before installing this build). @BobBooth what are you finding?

**Comment by dfoll** [comment]
i went back and installed the old version and observed the crash, then installed testing\...\28  and confirmed it is fixed... merging and building to dev

**Comment by dfoll** [comment]
Solutions\DefenseSolutions\DistanceAndDirection\March2019\Dev\49 
is built to test before we
1. ask for another version to be signed
2. build into MT

**Comment by dfoll** [comment]
Dev\49 looks good. going to rebuild MT then try to get another version of DD and MT signed

**Comment by BobBooth** [comment]
@dfoll  Dev\49  worked for me.

**Comment by dfoll** [comment]
Solutions\DefenseSolutions\MilitaryToolsForArcGIS\March2019\Dev\227 exists now  to test the MT build

**Comment by BobBooth** [comment]
@dfoll  MT Dev 227 works.

**Comment by dfoll** [comment]
MT 227 and DD 49 both work for me

**Comment by dfoll** [comment]
going to send both off to ask to have them signed again
