### ISSUE TITLE
User should be presented with warning when using invalid names to export

### ISSUE THREAD

**Issue by ljuru** [Esri/distance-direction-addin-dotnet#660]
## Background 
An issue was created (#385) to warn a user when they are using an invalid feature class name, but it only catches some of the cases. 

## Current behavior
If you enter a special character `*,&,!,(,<` in any portion of the name, you are presented with a warning.
![image](https://user-images.githubusercontent.com/50921068/58720200-5f587600-8386-11e9-8dca-31e85be550f9.png)

If you start the name with a number, [this is not allowed](https://pro.arcgis.com/en/pro-app/tool-reference/tool-errors-and-warnings/001001-010000/tool-errors-and-warnings-00426-00450-000447.htm), you get an error instead of a warning.   
![image](https://user-images.githubusercontent.com/50921068/58720286-9464c880-8386-11e9-8a7e-b15d1885c568.png)

## Expected behavior 
The user should the warning anytime the filename is invalid. 

## Additional information
This is found on ArcGIS Pro 2.4. beta 1  
Distance and Direction build 68

**Comment by dfoll** [comment]
- [ ] [Distance and Direction October Resources](https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/october-2019-distance-and-direction.htm)
- [ ] \DefenseSolutions\DistanceAndDirection\October2019\Dev\108\
- [ ] [Military Tools for ArcGIS October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\333\

**Comment by lfunkhouser** [comment]
doc QC'd
@dfoll can you confirm the build you tested on and add the verified and appropriate application version labels. Issue can be closed after that.
