### ISSUE TITLE
Incorrect axes labels for ellipses in ArcGIS Pro

### ISSUE THREAD

**Issue by ljuru** [Esri/distance-direction-addin-dotnet#661]
### Current Behavior 
This bug was discovered while doing Certification Testing for the Distance and Direction add in for ArcGIS Pro 2.4. 

### Repro steps:
0. Install ArcGIS Pro 2.4 + Distance and Direction Addin 4.1.2.68 
1.  Using the Distance and Direction Tool to create an ellipse (either by using the map point tool or manually entering the values) 
2. Select Semi for the Ellipse Type drop-down box 

![image](https://user-images.githubusercontent.com/50921068/58993384-38dd7500-87a2-11e9-97a1-f27e2fa21bd6.png)

a) Optional: Enter 3000 for the Major Axis box and 1500 for the Minor Axis box and 30 for Angle (though any angle will do because the angle label works correctly).

3. Ellipsoid is created. The core measure tool is set to Geodesic and used to confirm the issue.

![image](https://user-images.githubusercontent.com/50921068/58993137-7b528200-87a1-11e9-8b00-5d66ced885ee.png)

b) Selecting Full:
![image](https://user-images.githubusercontent.com/50921068/58995021-5fea7580-87a7-11e9-99d9-65170c5093b5.png)

![image](https://user-images.githubusercontent.com/50921068/58994937-1f8af780-87a7-11e9-87f7-9da74e8aa08b.png)

Note: The labels being displayed for this feature show semi major and minor axis values instead of full major and minor axis values 

### Expected Behavior 

The labels displayed when an ellipsoid is created should reflect major and minor axis values. The core measure tool set to Geodesic is used to confirm results. 

![image](https://user-images.githubusercontent.com/50921068/58919094-b5f4e580-86e1-11e9-9079-9b77e7301ded.png)

### Additional Notes: 
•   Observed in ArcGIS Pro 2.3 with released version of MT/DD
•   Did not observe on ArcMap 10.7.1

**Comment by csmoore** [comment]
Addressed in PR #664 - should behave the same in Pro and ArcMap now (i.e. the label shown is the "full" axes values)

Pro and ArcMap for same values used for both "full"(left) and "semi"(right) inputs:
Pro:
![image](https://user-images.githubusercontent.com/3090809/59381685-0693c080-8d2a-11e9-9683-8b14f94de8e0.png)

ArcMap:
![image](https://user-images.githubusercontent.com/3090809/59381656-f4b21d80-8d29-11e9-92f6-73277b10b982.png)

**Comment by lfunkhouser** [comment]
@ljuru @csmoore Was this just on Pro 2.4 and introduced new at MT 3.5? or was this an issue in previous versions of Pro/MT?

**Comment by ljuru** [comment]
@lfunkhouser I noticed the issue was in Pro 2.3 as well.

**Comment by csmoore** [comment]
I should have mentioned in my comments - it looked like this issue may have been present since we switched the graphics to features (June, 2018)

**Comment by dfoll** [comment]
![image](https://user-images.githubusercontent.com/5322669/59518738-52627900-8e94-11e9-8c61-1ff93c78c257.png)
![image](https://user-images.githubusercontent.com/5322669/59518746-58585a00-8e94-11e9-998b-f74c1d08bb7a.png)
![image](https://user-images.githubusercontent.com/5322669/59518753-5db5a480-8e94-11e9-837b-3000ada690e3.png)

**Comment by dfoll** [comment]
### Doc work:
- [ ] Update What's new page
   - [ ] MT section
   - [ ] Distance and Direction section
- Update DD homepage
- Update DD Resources
- Update MT Resources
- Publish DD Resources tab
- Publish MT Resources tab
- Publish DD pdf
- Publish MT Release notes (pdf)

**Comment by dfoll** [comment]
- 
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
-
-

**Comment by dfoll** [comment]
removed G-qc verify because i forgot to do it when i made [this comment](https://github.com/Esri/distance-direction-addin-dotnet/issues/661#issuecomment-502145076)

**Comment by dfoll** [comment]
Doc [PR](https://github.com/ArcGIS/arcgis-solutions-website/pull/7833) is still open

**Comment by lfunkhouser** [comment]
PR has been approved and merged.

**Comment by lfunkhouser** [comment]
Verified doc updates on solutionsdev for MT and DD and PDFs for MT (dev build 3.5.0.308) and DD (dev build (88).
