### ISSUE TITLE
Entering Lat/Lon Points for line in Web Mercator map produces inaccurate results and a crash in ArcMap

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#667]
This issue was found while certification testing #503 

1. Start ArcMap with a new project, add the Topographic basemap (any map in Web Mercator will work)
2. On the Lines Tab
3. Enter the following coordinate in the Starting Point: 37.5 -122.8
4. Enter the following coordinate in the Ending Point: 37.5 -125.0
5. Press Enter

Result: Crash

Expected Result: Line in Pacific near San Francisco coast

Tested on ArcMap 10.6.1 and 10.7.1

**Comment by csmoore** [comment]
Addressed in PR #669

**Comment by lfunkhouser** [comment]
Was this also an issue at 10.4-10.6? Need to test on all supported versions. Adding `doc` labels.

**Comment by dfoll** [comment]
This needs verified from testing branch
Listed as an issue addressed
Find out where else this might have been an issue

**Comment by dfoll** [comment]
On 10.4.1 this was not causing a crash, but was exhibiting odd behavior. The given repro points were drawing a line across the prime meridian from the origin near san francisco. Confirmed with DD build 93 (created from [this branch](https://github.com/Esri/distance-direction-addin-dotnet/tree/csm-667-crash-on-enter-line-tab) that the results are as expected and match ArcGIS Pro.

![image](https://user-images.githubusercontent.com/5322669/60024917-ade7f000-9666-11e9-9e77-3218f6b5e2a8.png)

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\313\
- https://solutionsdev.arcgis.com/defense/help/distance-direction/resources/june-2019-distance-and-direction.htm
- \\...\DefenseSolutions\DistanceAndDirection\Dev\95\

**Comment by lfunkhouser** [comment]
Doc verified on dev builds DD 95 and MT 314 and solutionsstg
