### ISSUE TITLE
"Point is out of bounds" message does not appear for south outside extent in ArcMap

### ISSUE THREAD

**Issue by ljuru** [Esri/distance-direction-addin-dotnet#668]
## Current Behavior
This bug was discovered while doing Certification Testing for the Distance and Direction add in for ArcMap 10.7.1.

![image](https://user-images.githubusercontent.com/50921068/59807941-e5454e00-92ae-11e9-8295-08bf79dd361a.png)

2. Repro steps:

0. Install ArcMap 10.7.1 + Distance and Direction Addin 2.3.2.88
1. Add a Web Mercator basemap
2. Zoom out so whitespace shows around basemap extent. 
3. Create a circle using the map point tool, click outside of the south extent of a Web Mercator basemap.

**Comment by dfoll** [comment]
need to provide some images to @saip  of exactly where the clicks were. there will be some whitespace tolerance where the cursor may be outside the map, but will not register as outside of the map extent

**Comment by dfoll** [comment]
@saip this is a screenshot of where I am able to draw lines with Distance and Direction. I was only able to draw these lines on the "bottom"/south of the map ... trying to place any points just barely off the edge to the north, east, or west gave the warning that the point was out of bounds. You can tell from how the graphics draw, where the "border" ends, but it is much larger than on the other three sides. While looking at this i could not repro in ArcGIS Pro.

![image](https://user-images.githubusercontent.com/5322669/62876665-78b95f00-bcf3-11e9-823d-bcb234a59d86.png)

**Comment by lfunkhouser** [comment]
User is able to click outside the extent to the south of a web mercator basemap. Other projections do not allow user to click outside the extent to the south of the basemap. This is only in ArcMap and not a showstopper. Workaround: Do not click outside the extent.
