### ISSUE TITLE
Opening saved .mxd with add-in from file explorer causes ArcMap crash

### ISSUE THREAD

**Issue by csmoore** [Esri/distance-direction-addin-dotnet#672]
While testing a fix for this issue: https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/626 

I noticed that the same problem that was fixed in CC for this issue: 
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/427 also exists with the DD addin:

1. Install the stand-alone add-in on ArcGIS (tested on 10.6.1) (Note: problem seems to also exists with MilitaryTools addin)
2. Open the add-in in ArcMap, so the DD window is open.
3. Save the map as an MXD.
4. Close ArcMap.
5. In Windows File Explorer, open the MXD by double-clicking it.
6. ArcMap crashes.

Note: The fix applied to https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/626 seems to fix this also so will add that fix to this repo, just opening an issue to attach fix to.

**Comment by csmoore** [comment]
Addressed in PR #673

**Comment by dfoll** [comment]
Observed reported behavior with released build

**Comment by dfoll** [comment]
- [x] update October resources topic
- [ ] publish  DD Resources
- [ ] publish MT Resources 
- [ ] publish pdf
- [ ] publish MT release notes pdf
- [ ] build .zip

**Comment by dfoll** [comment]
### Doc review:
- [ ] [Distance and Direction October Resources]()
- [ ] [Distance and Direction homepage]()
- [ ] Distance and Direction build location
- [ ] [Military Tools October Resources]()
- [ ] Military Tools build location
- [ ] [Defense What's new]()

**Comment by csmoore** [comment]
**Distance and Direction October Resources** (Release Notes added bug to table)

![image](https://user-images.githubusercontent.com/3090809/62296423-074cf700-b43d-11e9-95ac-098b9688f82b.png)

**Distance and Direction homepage** - Added to Release Table

**DistanceAndDirection.pdf** - added bug to table:

![image](https://user-images.githubusercontent.com/3090809/62300378-ade8c600-b444-11e9-96f8-b47161188276.png)

**Military Tools October Resources** - Bug added to Issues addressed Military Tools for ArcGIS 3.6 Release Notes

**Military Tools for ArcGIS Release Notes.pdf**

![image](https://user-images.githubusercontent.com/3090809/62300432-c8bb3a80-b444-11e9-8dd9-5009b32932e0.png)

**Defense What's new**

![image](https://user-images.githubusercontent.com/3090809/62300711-48e1a000-b445-11e9-9ba1-4c79fa743805.png)
