### ISSUE TITLE
Center point inputted in DDM format is placed in wrong location

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/distance-direction-addin-dotnet#681]
Center point when entered manually in DDM format results in features drawn at inaccurate locations.

MT build 3.6.342 and Pro 2.5
### Repro steps
1. Add the center point (in DDM format) 40 26.3033N 079 59.5243W
2. Enter 500km radius
3. Press enter

Result:
Circle created off the coast of Chile

Also tested on:
Released version of MT 3.5.0.317 and Pro 2.4 Final
DEV MT 3.6.342 and Pro 2.4 Final:
Entering same coordinates, 40 26.3033N 079 59.5243W
Same results:
![image](https://user-images.githubusercontent.com/3800729/65555366-55342780-dee1-11e9-8024-320dfa2066a4.png)

### Expected Result
Circle should be drawn, with center point in Pittsburgh, PA 
![image](https://user-images.githubusercontent.com/3800729/65554012-33d13c80-dedd-11e9-957d-81853d832467.png)

This can be confirmed by using the following formats for the center point of the circle: 
DD: 40.438389N 079.992071W
DMS: 40 26 18.20N 079 59 31.46W
MGRS: 17TNE8548476903
USNG: 17T NE 85484 76904
UTM: 17N 585484 4476903

**Comment by lfunkhouser** [comment]
@csmoore could you take a look at this? Seems like a familiar issue, https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/575...

**Comment by lfunkhouser** [comment]
Retested with 40 26.3033N 079 59.5243W and it is off coast of Chile. Not sure how I got it in Russia as originally written in the issue. But now consistently reproduced in Pacific Ocean off of Chile.

**Comment by csmoore** [comment]
Thanks for reconfirming - that makes a little more sense since I could not see where [this code had been changed since the last release](https://github.com/Esri/coordinate-conversion-addin-dotnet/commits/dev/source/CoordinateConversion/CoordinateConversionLibrary/Models/CoordinateDDM.cs) and you are correct that this definitely looks like a reoccurrence of https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/575

**Comment by csmoore** [comment]
Still looking at this issue - see comment at: https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/575#issuecomment-535283948

**Comment by csmoore** [comment]
Can retest after:

https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/636 
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/575

**Comment by dfoll** [comment]
Testing using MT build 346 ArcGIS Pro 2.4
