### ISSUE TITLE
Can this repo be made public?

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/distance-direction-addin-dotnet#79]
This repo is 'private' so very few people have access to it, can it be shared in the same manner as coordinate conversion?  https://github.com/Esri/coordinate-conversion-addin-dotnet

**Comment by topowright** [comment]
This repo is now been made public

**Comment by topowright** [comment]
@nfeuerstein please verify

**Comment by nfeuerstein** [comment]
Verified.
