### ISSUE TITLE
Writing Columns and Values from Graphics to Saved Features

### ISSUE THREAD

**Issue by mcalamito** [Esri/distance-direction-addin-dotnet#90]
Saving graphics as features (shapefile, feature class, and KML) is crucial, but so is saving the attributes that correspond to these features. The user will be inputting information into the Distance and Direction form or drawing on the map interactively. These values must be present in the attribute table when the graphic is saved to a feature or the user will not have values associated with each feature.

For any input field that has a unit, the corresponding Column/Field header name in the attribute will end with "_x" where x = the unit in which defines the input field.

The following columns and values should be included when writing graphics to features:

Lines: Start_Pt, End Pt, Dist_x, Angle_x   - where x is the unit the user chose from the unit dropdown.

Circle: Center_Pt, Radius_x OR Diameter_x - depending on if the user chose Radius or Diameter

Ellipse: Center_Pt, Minor_x, Major_x, Orient_x - where x is the unit the user chose from the unit dropdown.

Rings: Center_Pt, Rings, Dist_x, Radials - where x is the unit the user chose from the unit dropdown.

These are only suggested column names and I welcome any discussion.

**Comment by rjones0** [comment]
PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/309

**Comment by rjones0** [comment]
@mcalamito @pshowalter the basics of the functionality have been added. Please review and provide comments or close if appropriate. Note that saving from Pro is a little slow with this fix - this is due to a limitation in the API (the fields have to be added to the output Feature Class one by one).

**Comment by rjones0** [comment]
@mcalamito @pshowalter I am going to close this issue as I am confident it is resolved. Please let me know if you disagree.

**Comment by pshowalter** [comment]
@rjones0 
Would it make sense to copy an existing empty schema, and then populate with features, rather than building up the schema by adding fields one at atime?

**Comment by rjones0** [comment]
@pshowalter I think that is a superior approach, and I referred to similar/same in my PR: https://github.com/Esri/distance-direction-addin-dotnet/pull/309

I think the obvious method is to include files with template schema i.e. Shapefile/FGDB containing FC with appropriate fields as embedded resources in the solution. I would have to check if this approach works with an AddIn. Happy to investigate this, especially as the Pro SDK doesn't seem to have what I need to build up the schema fully in code, and the method I used seemed very slow in testing.

@kgonzago what is your opinion on above?

**Comment by kgonzago** [comment]
@rjones0 an empty shapefile with a predefined schema and executing the FC to FC tool to create output FC. Seems like a good approach which might be more efficient than calling the add field tool numerous times over.

**Comment by NatalieCampos** [comment]
This enhancement recommended the following fields be added when graphics are saved.

Lines: Start_Pt, End Pt, Dist_x, Angle_x - where x is the unit the user chose from the unit dropdown.
Circle: Center_Pt, Radius_x OR Diameter_x - depending on if the user chose Radius or Diameter
Ellipse: Center_Pt, Minor_x, Major_x, Orient_x - where x is the unit the user chose from the unit dropdown.
Rings: Center_Pt, Rings, Dist_x, Radials - where x is the unit the user chose from the unit dropdown.

However, only the following fields are added:
Lines: Angle, Distance
Circle: Distance, DistanceType
Elipse: Minor, Major, Angle
Rings: Rings, Distance, Angle

The following fields are still missing from the enhancement request:
Lines: Start_Pt, End Pt
Circle: Center_Pt
Ellipse: Center_Pt
Rings: Center_Pt

@nfeuerstein @lfunkhouser  Do these fields need to be added?

**Comment by lfunkhouser** [comment]
Assigning back to developers to add the fields @NatalieCampos pointed out that are still missing.

**Comment by pHill5136** [comment]
pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/378
please verify

**Comment by NatalieCampos** [comment]
I got this one.

**Comment by dfoll** [comment]
with build 1474 these fields are being added to feature class and shapefile. Still at 1474, some of the kmz are seemingly randomly getting corrupted, however the ones that did work did not have the fields added

**Comment by pHill5136** [comment]
please verify

**Comment by NatalieCampos** [comment]
@pHill5136 
There are differences in attribute when written to shp vs feature class.  The lines are missing the DestinationX and DestinationY fields.

**Comment by NatalieCampos** [comment]
@pHill5136 Also my KMZs still have no attributes when saved from Pro 1.4

https://github.com/Esri/distance-direction-addin-dotnet/issues/90

**Comment by pHill5136** [comment]
please verify pr: https://github.com/Esri/distance-direction-addin-dotnet/pull/391

**Comment by NatalieCampos** [comment]
The missing fields have been added. Closing issue.
