### ISSUE TITLE
Circle, Ellipses, and Rings Must be of Geometry Type Polygon, Not Polyline

### ISSUE THREAD

**Issue by mcalamito** [Esri/distance-direction-addin-dotnet#92]
All Circle, Ellipse, and Ring graphics and feature layers (using the Save As button) are creating polylines as their geometries. These geometries must be of type polygon.

**Comment by dhagens** [comment]
@mcalamito, please review

**Comment by mcalamito** [comment]
@dhagens reviewed and still am producing Polylines.

**Comment by mcalamito** [comment]
@dhagens tested the new update and verified it is creating polygons. closing ticket. well done.
